Repository openshift/managed-cluster-config, pull requests merged in 2019-08, with the labels that each got.

#66 Create an alert for the cluster operator being down
  deploy/sre-prometheus/100-cluster-operator.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#65 SRE can approve CSR
  deploy/sre-authorization/01-osd-sre-admin.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/S

#67 SRE can temporarily elevate permissions to cluster-admin
  README.md
  deploy/sre-authorization/00-osd-sre-cluster-admins.ClusterRoleBinding.yaml
  deploy/sre-authorization/00-osd-sre-cluster-admins.Group.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#68 Apply curated operators
  README.md
  deploy/osd-curated-operators/00-cvo-overrides.patch.yaml
  deploy/osd-curated-operators/10-curated-certified-operators.patch.yaml
  deploy/osd-curated-operators/10-curated-community-operators.patch.yaml
  deploy/osd-curated-operators/10-curated-redhat-operators.patch.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, size/M

#69 Add patch to wipe users from hive
  deploy/sre-authorization/20-osd-sre-cluster-admins.patch.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/S

#70 Do not manage CatalogSourceConfig from Hive
  README.md
  deploy/osd-logging/00-installed-redhat-openshift-logging.catalogsourceconfig.yaml
  deploy/osd-logging/00-installed-redhat-openshift-operators.catalogsourceconfig.yaml
  deploy/osd-logging/03-elasticsearch-operator.subscription.yaml
  deploy/osd-logging/04-cluster-logging.subscription.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, size/L

#71 Add cblecker to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#72 Remove prometheus alert links to access.redhat.com
  deploy/sre-prometheus/100-machine-api.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XS

#74 added logging quota overrides from the default, and added a specific quota targeting the openshift-logging namespace so that the customer may provision ES with PV's.
  Makefile
  deploy/osd-logging/01-namespace.yaml
  deploy/osd-logging/03-storage-quota.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#75 fixed bad formatting in the quota resource
  deploy/osd-logging/03-storage-quota.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/M

#64 Always cleanup syncset, don't log error for oc delete
  scripts/cluster-upgrade.sh
Labels: approved, lgtm, size/S

#76 Enable default route for registry.
  deploy/osd-registry/registry-defaultRoute.patch.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#78 Change upgrade script to add capacity to OSD cluster as part of upgrade
  scripts/cluster-upgrade.sh
Labels: approved, lgtm, size/L

#79 Create alert if telemeter-client isn't forwarding data to telemeter server
  deploy/sre-prometheus/100-telemeter-client.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/M

#80 Fix osd-sre-cluster-admins group to use empty array
  deploy/sre-authorization/00-osd-sre-cluster-admins.Group.yaml
  deploy/sre-authorization/20-osd-sre-cluster-admins.patch.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/S

#83 Require target version <= default CIS
  scripts/cluster-upgrade.sh
Labels: approved, lgtm, size/M

#81 Use safe loading in pyyaml
  scripts/generate_syncset.py
Labels: approved, lgtm, size/XS

#82 Add manifests for managed-velero-operator
  deploy/velero-configuration/050-velero.CustomResourceDefinition.yaml
  deploy/velero-configuration/100-velero.Namespace.yaml
  deploy/velero-configuration/105-velero.ServiceAccount.yaml
  deploy/velero-configuration/110-velero.ClusterRole.yaml
  deploy/velero-configuration/110-velero.Role.yaml
  deploy/velero-configuration/115-velero.ClusterRoleBinding.yaml
  deploy/velero-configuration/115-velero.RoleBinding.yaml
  deploy/velero-configuration/120-velero.ServiceAccount.yaml
  deploy/velero-configuration/125-velero.RoleBinding.yaml
  deploy/velero-configuration/130-velero.CredentialRequest.yaml
  deploy/velero-configuration/135-velero.Deployment.yaml
  deploy/velero-configuration/140-velero.Velero.yaml
  deploy/velero-configuration/150-velero.Schedules.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#84 Split velero operator install from configuration
  deploy/managed-velero-operator/050-velero.CustomResourceDefinition.yaml
  deploy/managed-velero-operator/100-velero.Namespace.yaml
  deploy/managed-velero-operator/105-velero.ServiceAccount.yaml
  deploy/managed-velero-operator/110-velero.ClusterRole.yaml
  deploy/managed-velero-operator/110-velero.Role.yaml
  deploy/managed-velero-operator/115-velero.ClusterRoleBinding.yaml
  deploy/managed-velero-operator/115-velero.RoleBinding.yaml
  deploy/managed-velero-operator/120-velero.ServiceAccount.yaml
  deploy/managed-velero-operator/125-velero.RoleBinding.yaml
  deploy/managed-velero-operator/130-velero.CredentialRequest.yaml
  deploy/managed-velero-operator/135-velero.Deployment.yaml
  deploy/velero-configuration/100-velero.Velero.yaml
  deploy/velero-configuration/110-velero.Schedules.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#85 Bump velero image tag
  deploy/managed-velero-operator/135-velero.Deployment.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XS

#88 Push fix for cluster-config-v1 permissions
  deploy/managed-velero-operator/111-velero.Role.yaml
  deploy/managed-velero-operator/116-velero.RoleBinding.yaml
  deploy/managed-velero-operator/135-velero.Deployment.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/M

#89 Provide SRE permissions to create needed velero objects
  deploy/sre-authorization/01-osd-sre-admin.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/S
