Repository openshift/managed-cluster-config, pull requests merged in 2019-04, with the labels that each got.

#11 SREP-1119: Add CronJobs & RBAC to prune Builds and Deployments
  deploy/sre-pruning/100-pruning.Namespace.yaml
  deploy/sre-pruning/105-pruning.rbac.yaml
  deploy/sre-pruning/110-pruning-builds.CronJob.yaml
  deploy/sre-pruning/110-pruning-deployments.CronJob.yaml
  deploy/sre-pruning/110-pruning-images.CronJob.yaml
Labels: size/L

#12 Updated schedule to not run every minute
  deploy/sre-pruning/110-pruning-builds.CronJob.yaml
  deploy/sre-pruning/110-pruning-deployments.CronJob.yaml
  deploy/sre-pruning/110-pruning-images.CronJob.yaml
Labels: lgtm, size/XS

#8 SREP-924 Add deployment script for prom exporters and rules
  .gitignore
  scripts/deploy_assets.py
Labels: lgtm, size/M
