Repository openshift/managed-cluster-config, pull requests merged in 2019-09, with the labels that each got.

#87 Upgrade script updated to check state of cluster as upgraded.
  scripts/cluster-upgrade.sh
Labels: approved, lgtm, size/M

#90 Add namespace to all SRE prometheus alerts
  deploy/sre-prometheus/100-check-full-cust-pv.PrometheusRule.yaml
  deploy/sre-prometheus/100-cluster-operator.PrometheusRule.yaml
  deploy/sre-prometheus/100-configure-alertmanager-operator.PrometheusRule.yaml
  deploy/sre-prometheus/100-dedicated-admin-operator.PrometheusRule.yaml
  deploy/sre-prometheus/100-dns-latency.PrometheusRule.yaml
  deploy/sre-prometheus/100-ebs-iops-burstbalance.PrometheusRule.yaml
  deploy/sre-prometheus/100-machine-api.PrometheusRule.yaml
  deploy/sre-prometheus/100-node-unschedulable.PrometheusRule.yaml
  deploy/sre-prometheus/100-router-health.PrometheusRule.yaml
  deploy/sre-prometheus/100-stuck-builds.PrometheusRule.yaml
  deploy/sre-prometheus/100-stuck-volumes.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  hack/app_sre_pr_check.sh
Labels: approved, lgtm, size/XXL

#91 Added logic to limit $CLUSTER_NAME to 15 chars
  scripts/cluster-upgrade.sh
Labels: approved, lgtm, size/XS

#92 🎨: Refactor vercomp and fix minor :bug:
  scripts/cluster-upgrade.sh
Labels: approved, do-not-merge/hold, lgtm, size/M

#94 Update oc image for pruning jobs
  deploy/sre-pruning/110-pruning-builds.CronJob.yaml
  deploy/sre-pruning/110-pruning-deployments.CronJob.yaml
  deploy/sre-pruning/110-pruning-images.CronJob.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#95 Revert "Update oc image for pruning jobs"
  deploy/sre-pruning/110-pruning-builds.CronJob.yaml
  deploy/sre-pruning/110-pruning-deployments.CronJob.yaml
  deploy/sre-pruning/110-pruning-images.CronJob.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, size/XXL

#96 Update oc image for pruning jobs
  deploy/sre-pruning/110-pruning-builds.CronJob.yaml
  deploy/sre-pruning/110-pruning-deployments.CronJob.yaml
  deploy/sre-pruning/110-pruning-images.CronJob.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, do-not-merge/hold, lgtm, size/XXL

#97 Update image pull policy for pruning jobs
  deploy/sre-pruning/110-pruning-builds.CronJob.yaml
  deploy/sre-pruning/110-pruning-deployments.CronJob.yaml
  deploy/sre-pruning/110-pruning-images.CronJob.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XS

#98 Use openshift/cli imagestream for pruner
  deploy/sre-pruning/110-pruning-builds.CronJob.yaml
  deploy/sre-pruning/110-pruning-deployments.CronJob.yaml
  deploy/sre-pruning/110-pruning-images.CronJob.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/S

#99 Upgrade script supports variable 'compute' names in clusterdeployment
  scripts/cluster-upgrade.sh
Labels: approved, lgtm, size/XS

#100 If prune job doesn't start, replace it
  deploy/sre-prometheus/100-sre-pruning.PrometheusRule.yaml
  deploy/sre-pruning/110-pruning-builds.CronJob.yaml
  deploy/sre-pruning/110-pruning-deployments.CronJob.yaml
  deploy/sre-pruning/110-pruning-images.CronJob.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#101 Update SRE pruning error metric
  deploy/sre-prometheus/100-sre-pruning.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#102 Fix variable for pruning alert
  deploy/sre-prometheus/100-sre-pruning.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XS

#103 Fix another typo
  deploy/sre-prometheus/100-sre-pruning.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XS

#104 Use namespace as part of kubeconfig file instead of cluster name
  scripts/cluster-upgrade.sh
Labels: approved, lgtm, size/S

#106 Update managed-velero-operator prometheus role
  deploy/managed-velero-operator/112-velero.Role.yaml
  deploy/managed-velero-operator/117-velero.RoleBinding.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/M

#107 SREP-1932: Quote the quota limits
  deploy/resource-quotas/15-resource.clusterresourcequota.yaml
  deploy/resource-quotas/templates/15-resource.clusterresourcequota.yaml.tmpl
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, kind/bug, lgtm, size/S

#108 Create custom KubeAPILatencyHIgh rule
  deploy/sre-prometheus/100-kubeapilatencyhigh-custom.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XL

#109 Various updates to cluster-upgrade.sh
  scripts/cluster-upgrade.sh
Labels: approved, lgtm, size/M
