Repository openshift/managed-cluster-config, pull requests merged in 2019-10, with the labels that each got.

#110 Update value of 'custom-kubelet' label to empty string ("")
  deploy/kubelet-config/01-patch.machineconfigpool.yaml
  deploy/kubelet-config/02-patch.machineconfigpool.yaml
  deploy/kubelet-config/03-kubelet-config.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#111 No longer cut CLUSTER_NAME in upgrade script
  scripts/cluster-upgrade.sh
Labels: approved, lgtm, size/XS

#112 Remove log that was trying to indicate an upgrade couldn't start
  scripts/cluster-upgrade.sh
Labels: approved, lgtm, size/XS

#114 Adding new bits for crw operator
  deploy/osd-codeready-workspaces/00-operatorgroup.yaml
  deploy/osd-codeready-workspaces/01-namespace.yaml
  deploy/osd-codeready-workspaces/05-role.yaml
  deploy/osd-codeready-workspaces/06-rolebinding.yaml
  deploy/osd-logging/00-operatorgroup.yaml
  deploy/osd-logging/05-role.yaml
  deploy/osd-logging/06-rolebinding.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/L

#113 Add prometheus rule for excessive system container memory
  deploy/sre-prometheus/100-excessive-memory.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#116 Remove 'list' on 'secrets' in 'openshift-codeready-workspaces'
  deploy/osd-codeready-workspaces/05-role.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XS

#117 Fix spelling error
  deploy/osd-codeready-workspaces/05-role.yaml
Labels: approved, lgtm, size/XS

#118 Updated OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#119 Update link to use v4 SOP
  deploy/sre-prometheus/100-check-full-cust-pv.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#124 SREP-2178 - Add objects and permission for customer managed monitoring
  deploy/osd-customer-monitoring/00-namespace.yaml
  deploy/osd-customer-monitoring/01-operatorgroup.yaml
  deploy/osd-customer-monitoring/05-role.yaml
  deploy/osd-customer-monitoring/06-rolebinding.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#125 SREP-2178 Add PodMonitor and turn Prometheus/AlertManager into plural in Role def
  deploy/osd-customer-monitoring/05-role.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm

#120 Add project-request template
  deploy/osd-project-request-template/00-clusterrole.project-config.yaml
  deploy/osd-project-request-template/01-clusterrolebinding.project-config.yaml
  deploy/osd-project-request-template/02-role.dedicated-admins-project-request.yaml
  deploy/osd-project-request-template/03-rolebinding.dedicated-admins-project-request.yaml
  deploy/osd-project-request-template/04-patch.label-default-namespace.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL
