Repository openshift/managed-cluster-config, pull requests merged in 2019-03, with the labels that each got.

#1 SREP-923: Copy over SRE alerting rules
  deploy/prometheus/100-check-full-cust-pv.PrometheusRule.yaml
  deploy/prometheus/100-dns-latency.PrometheusRule.yaml
  deploy/prometheus/100-ebs-iops-burstbalance.PrometheusRule.yaml
  deploy/prometheus/100-router-health.PrometheusRule.yaml
  deploy/prometheus/100-stuck-builds.PrometheusRule.yaml
  deploy/prometheus/100-stuck-volumes.PrometheusRule.yaml
Labels: size/L

#3 SREP-693: Add alert rule for unschedulable nodes
  deploy/prometheus/100-node-unschedulable.PrometheusRule.yaml
Labels: kind/feature, lgtm, size/S

#4 Restrict rules to openshift-monitoring namespace
  deploy/prometheus/100-check-full-cust-pv.PrometheusRule.yaml
  deploy/prometheus/100-dns-latency.PrometheusRule.yaml
  deploy/prometheus/100-ebs-iops-burstbalance.PrometheusRule.yaml
  deploy/prometheus/100-router-health.PrometheusRule.yaml
  deploy/prometheus/100-stuck-builds.PrometheusRule.yaml
  deploy/prometheus/100-stuck-volumes.PrometheusRule.yaml
Labels: kind/cleanup, lgtm, size/XS

#5 Added osd-sre-admin ClusterRole
  README.md
  deploy/sre-authorization/01-osd-sre-admin.ClusterRole.yaml
  deploy/sre-authorization/02-osd-sre-admin.ClusterRoleBindings.yaml
Labels: size/L

#2 Add console branding artifact
  deploy/console-branding/cr-console.operator.config.yaml
Labels: lgtm, size/S

#7 Moved read verbs to osd-sre-admin clusterrole
  deploy/sre-authorization/01-osd-sre-admin.ClusterRole.yaml
  deploy/sre-authorization/02-osd-sre-admin.ClusterRoleBinding.yaml
  deploy/sre-authorization/02-osd-sre-admin.ClusterRoleBindings.yaml
Labels: lgtm, size/M

#9 Reformat README.md to use Markdown
  README.md
Labels: kind/bug, size/XS
