Repository openshift/managed-cluster-config, pull requests merged in 2019-05, with the labels that each got.

#13 Added selectorsyncset generation
  Makefile
  project.mk
  scripts/generate_syncset.py
  scripts/templates/selectorsyncset.yaml
Labels: size/L

#14 [WIP] Added scripts required for app-sre pipeline
  hack/app_sre_build_deploy.sh
  hack/app_sre_pr_check.sh
Labels: do-not-merge/work-in-progress, size/S

#16 Updated OWNERS to be consistent with SRE operators
  OWNERS
Labels: lgtm, size/XS

#15 Make selectorsyncset destination file location explicit
  .gitignore
  Makefile
  project.mk
Labels: lgtm, size/XS

#17 Update severity 'warn' to 'warning'
  deploy/prometheus/100-ebs-iops-burstbalance.PrometheusRule.yaml
  deploy/prometheus/100-router-health.PrometheusRule.yaml
  deploy/prometheus/100-stuck-builds.PrometheusRule.yaml
  deploy/prometheus/100-stuck-volumes.PrometheusRule.yaml
Labels: lgtm, size/S

#18 fixed typo in file name
  .gitignore
  project.mk
Labels: approved, size/XS

#19 Modify template to be of kind template
  .gitignore
  Makefile
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  project.mk
  scripts/generate_syncset.py
  scripts/templates/selectorsyncset.yaml
Labels: size/XL

#21 Updated check scripts to make sure they pass
  hack/app_sre_build_deploy.sh
  hack/app_sre_pr_check.sh
Labels: approved, size/XS

#22 Added image_tag to template
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  scripts/templates/selectorsyncset.yaml
Labels: lgtm, size/S

#24 Add branding for console login.
  .gitignore
  Makefile
  deploy/osd-console-branding/osd-branding.console.yaml
  deploy/osd-oauth-templates-errors/osd-oauth-templates-errors.secret.yaml
  deploy/osd-oauth-templates-login/osd-oauth-templates-login.secret.yaml
  deploy/osd-oauth-templates-providers/osd-oauth-templates-providers.secret.yaml
  deploy/osd-oauth-templates/osd-oauth-templates.patch.yaml
  deploy/sre-prometheus/100-check-full-cust-pv.PrometheusRule.yaml
  deploy/sre-prometheus/100-dns-latency.PrometheusRule.yaml
  deploy/sre-prometheus/100-ebs-iops-burstbalance.PrometheusRule.yaml
  deploy/sre-prometheus/100-node-unschedulable.PrometheusRule.yaml
  deploy/sre-prometheus/100-router-health.PrometheusRule.yaml
  deploy/sre-prometheus/100-stuck-builds.PrometheusRule.yaml
  deploy/sre-prometheus/100-stuck-volumes.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  project.mk
  scripts/generate_syncset.py
  scripts/templates/selectorsyncset.yaml
  scripts/templates/template.yaml
  source/html/errors.html
  source/html/login.html
  source/html/providers.html
Labels: lgtm, size/XXL
