Repository openshift/managed-cluster-config, pull requests merged in 2019-12, with the labels that each got.

#147 add loadbalancer quota SelectorSyncSets
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  scripts/templates/template.yaml
Labels: approved, lgtm, size/L

#150 Update label name for storage quota
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  scripts/templates/template.yaml
Labels: approved, lgtm, size/S

#151 Created OperatorGroup resource for AquaSec deployment
  deploy/osd-aquasec-operator/01-operatorgroup.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#141 update the applymode to AlwaysApply for osd-oauth-templates and osd-r…
  deploy/osd-oauth-templates/osd-oauth-templates.patch.yaml
  deploy/osd-registry/registry-defaultRoute.patch.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#153 Adding "patch" verb to aqua-sa serviceAccount, renamed files to follow convention
  deploy/osd-aquasec-operator/02-role.yaml
  deploy/osd-aquasec-operator/03-rolebinding.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XS

#154 Allow dedicated-admins to manage PVCs in openshift-logging
  deploy/osd-logging/05-role.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#138 Add dedicated rbac configurations
  deploy/rbac-permissions-operator/00-dedicated-admin.Namespace.yaml
  deploy/rbac-permissions-operator/00-dedicated-admins-cluster.ClusterRole.yaml
  deploy/rbac-permissions-operator/00-dedicated-admins-cluster.ClusterRoleBinding.yaml
  deploy/rbac-permissions-operator/00-dedicated-admins-project.ClusterRole.yaml
  deploy/rbac-permissions-operator/00-dedicated-admins.SubjectPermission.yaml
  deploy/rbac-permissions-operator/01-dedicated-admins-operators.Role.yaml
  deploy/rbac-permissions-operator/01-dedicated-admins-operators.RoleBinding.yaml
  deploy/rbac-permissions-operator/02-dedicated-admins-marketplace.Role.yaml
  deploy/rbac-permissions-operator/02-dedicated-admins-marketplace.RoleBinding.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#156 Change image used by sre pruner
  deploy/sre-pruning/110-pruning-builds.CronJob.yaml
  deploy/sre-pruning/110-pruning-deployments.CronJob.yaml
  deploy/sre-pruning/110-pruning-images.CronJob.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#157 Prepend -config to sss name for rbac-permissions-operator
  deploy/rbac-permissions-operator-config/00-dedicated-admin.Namespace.yaml
  deploy/rbac-permissions-operator-config/00-dedicated-admins-cluster.ClusterRole.yaml
  deploy/rbac-permissions-operator-config/00-dedicated-admins-cluster.ClusterRoleBinding.yaml
  deploy/rbac-permissions-operator-config/00-dedicated-admins-project.ClusterRole.yaml
  deploy/rbac-permissions-operator-config/00-dedicated-admins.SubjectPermission.yaml
  deploy/rbac-permissions-operator-config/01-dedicated-admins-operators.Role.yaml
  deploy/rbac-permissions-operator-config/01-dedicated-admins-operators.RoleBinding.yaml
  deploy/rbac-permissions-operator-config/02-dedicated-admins-marketplace.Role.yaml
  deploy/rbac-permissions-operator-config/02-dedicated-admins-marketplace.RoleBinding.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#155 Add wanghaoran1988 reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#159 Remove alerts for dedicated-admin-operator
  deploy/sre-prometheus/100-dedicated-admin-operator.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#160 SREP-2178 - Give App-SRE permissions to do pod/poft-forward in customer monitoring NS
  deploy/osd-customer-monitoring/05-role.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#161 Added RbacPermissionsOperatorOfflineSRE alert
  deploy/sre-prometheus/100-rbac-permissions-operator.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#162 SREP-2140 - alert when sre stays in cluster-admin more than 2 hours
  deploy/sre-prometheus/100-sre-elevation.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#163 Fix regex for rbac subjectpermissions
  deploy/rbac-permissions-operator-config/00-dedicated-admins.SubjectPermission.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#164 Delete RbacPermissionsOperatorOfflineSRE alert until we have metrics
  deploy/sre-prometheus/100-rbac-permissions-operator.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#165 Fix permissions that were not correctly ported from dedicated-admin
  deploy/rbac-permissions-operator-config/00-dedicated-admins-cluster.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/S

#166 SREP-2535 Update RBAC setup for customer monitoring
  deploy/osd-customer-monitoring/05-prometheus-k8s-role.yaml
  deploy/osd-customer-monitoring/05-role.yaml
  deploy/osd-customer-monitoring/06-prometheus-k8s-rolebinding.yaml
  deploy/osd-customer-monitoring/06-rolebinding.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#167 SREP-2532: Ignore Prometheus specific memory usage
  deploy/sre-prometheus/100-excessive-memory.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#168 SREP-2535 Fix to address change to RBAC binding in v4
  deploy/osd-customer-monitoring/06-rolebinding.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#149 Add dedicated-admin SA to logging rolebinding
  deploy/osd-logging/06-rolebinding.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#169 Add dedicated-admin serviceaccounts permissions
  deploy/rbac-permissions-operator-config/00-dedicated-admins-serviceaccounts.SubjectPermission.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#170 Remove loadbalancer quotas 1-3
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  scripts/templates/template.yaml
Labels: approved, lgtm, size/L

#172 Add API group
  deploy/osd-aquasec-operator/10-clusterrole-image-scanner.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#173 Tune ExcessiveContainerMemorySRE alerts
  deploy/sre-prometheus/100-excessive-memory.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL
