Repository openshift/managed-cluster-config, pull requests merged in 2019-11, with the labels that each got.

#127 SREP-2178 Add dedicated-admins permissions to customer monitoring NS
  deploy/osd-customer-monitoring/05-role.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#129 SREP-2345 Use a different Cincinnati channel for 4.2: fast-4.2
  scripts/cluster-upgrade.sh
Labels: approved, lgtm, size/S

#128 Update base docs URL to hit v4 specifically
  deploy/osd-console-branding/osd-branding.console.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#130 SREP-2355 Add group field into ClusterVersion Overrides
  deploy/osd-curated-operators/00-cvo-overrides.patch.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#131 SREP-2351 Pre-patch channel in ClusterVersion before starting upgrade to v4.2
  scripts/cluster-upgrade.sh
Labels: approved, lgtm, size/XS

#133 SREP-2359 Changes to support the new v4.2 features to manage OLM overrides
  deploy/UPSERT/osd-operatorhub-crd/00-operatorhub.crd.yaml
  deploy/osd-curated-operatorsources/00-operatorhub.cr.yaml
  deploy/osd-curated-operatorsources/10-curated-certified-operators.OperatorSource.yaml
  deploy/osd-curated-operatorsources/10-curated-community-operators.OperatorSource.yaml
  deploy/osd-curated-operatorsources/10-curated-redhat-operators.OperatorSource.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  scripts/generate_syncset.py
Labels: approved, lgtm, size/XXL

#134 SREP-2359 Fix typo in source display name
  deploy/osd-curated-operatorsources/10-curated-redhat-operators.OperatorSource.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XS

#135 enable excessive-memory alerts
  deploy/sre-prometheus/100-excessive-memory.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#136 add cloud platform labelling
  deploy/cluster-monitoring-config/cluster-monitoring-config.yaml
  deploy/sre-prometheus/aws/100-ebs-iops-burstbalance.PrometheusRule.yaml
  deploy/sre-prometheus/aws/100-stuck-volumes.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  scripts/generate_syncset.py
Labels: approved, lgtm, size/XXL

#137 Allow view events in openshift-{logging,codeready-workspaces} and vie…
  deploy/osd-codeready-workspaces/05-role.yaml
  deploy/osd-logging/05-role.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#140 Add arch and version params to upgrades_info call
  scripts/cluster-upgrade.sh
Labels: approved, lgtm, size/XS

#139 Automate putting clusters in maint for an upgrade
  scripts/cluster-upgrade.sh
Labels: approved, lgtm, size/L

#143 Enable dedicated-admins to deploy AquaSec operator
  deploy/osd-aquasec-operator/00-namespace.yaml
  deploy/osd-aquasec-operator/01-role.yaml
  deploy/osd-aquasec-operator/02-rolebinding.yaml
  deploy/osd-aquasec-operator/10-clusterrole-image-scanner.yaml
  deploy/osd-aquasec-operator/11-clusterrolebinding-image-scanner.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#144 SREP-2426 Fix apiVersion for ClusterRole(Binding)
  deploy/osd-aquasec-operator/10-clusterrole-image-scanner.yaml
  deploy/osd-aquasec-operator/11-clusterrolebinding-image-scanner.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#145 Removed service-lb-quota-exempt label from aquasec namespace
  deploy/osd-aquasec-operator/00-namespace.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#146 Update managed-velero-operator to v0.1.53-3ef2ade
  deploy/managed-velero-operator/050-velero.CustomResourceDefinition.yaml
  deploy/managed-velero-operator/130-velero.CredentialRequest.yaml
  deploy/managed-velero-operator/135-velero.Deployment.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL
