Repository openshift/managed-cluster-config, pull requests merged in 2019-07, with the labels that each got.

#42 SRE can use oc debug node
  deploy/sre-authorization/01-osd-sre-admin.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: lgtm, size/XXL

#43 added a Dockerfile and made small changes in Makefile
  Dockerfile
  Makefile
  README.md
  project.mk
Labels: size/M

#44 Install logging and ES operator and pre-configure curator
  README.md
  deploy/osd-logging/00-installed-redhat-openshift-logging.catalogsourceconfig.yaml
  deploy/osd-logging/00-installed-redhat-openshift-operators.catalogsourceconfig.yaml
  deploy/osd-logging/00-openshift-logging.operatorgroup.yaml
  deploy/osd-logging/01-namespace.yaml
  deploy/osd-logging/02-curator.configmap.yaml
  deploy/osd-logging/03-elasticsearch-operator.subscription.yaml
  deploy/osd-logging/04-cluster-logging.subscription.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: lgtm, size/L

#45 Dockerfile update, No more need for epel
  Dockerfile
Labels: lgtm, size/S

#47 Dockerfile for integretating managed-cluster-config with openshift/release
  Dockerfile
Labels: lgtm, size/XS

#49 Manage telemeter server URL
  deploy/cluster-monitoring-config/cluster-monitoring-config.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  scripts/templates/template.yaml
Labels: lgtm, size/XS

#50 Oauth template
  deploy/osd-oauth-templates-login/osd-oauth-templates-login.secret.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  source/html/login.html
Labels: lgtm, size/XXL

#48 Dockerfile for integretating managed-cluster-config with openshift/release
  Dockerfile
Labels: lgtm, size/XS

#53 Dockerfile for integretating managed-cluster-config with openshift/release
  Dockerfile
Labels: lgtm, size/S

#54 Oauth template
  deploy/osd-oauth-templates-providers/osd-oauth-templates-providers.secret.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  source/html/providers.html
Labels: lgtm, size/XS

#55 Dockerfile for integretating managed-cluster-config with openshift/release
  Dockerfile
Labels: lgtm, size/XS

#51 Add pods/exec permission for sre admin.
  deploy/sre-authorization/01-osd-sre-admin.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: size/L

#56 Script SRE can use to manage upgrades of clusters.
  README.md
  scripts/cluster-upgrade.sh
Labels: lgtm, size/L

#60 RBAC so SRE can administer logging
  Makefile
  README.md
  deploy/sre-authorization/01-osd-sre-admin.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  scripts/generate_syncset.py
Labels: size/XXL

#61 Makefile failing in CI workflow
  project.mk
Labels: size/XS

#62 Updating Dockerfile to reflect changes done to generate_syncset.py
  Dockerfile
Labels: lgtm, size/XS
