Repository openshift/managed-cluster-config, pull requests merged in 2019-06, with the labels that each got.

#23 SREP-1368: Support quotas & exemptions
  Makefile
  README.md
  deploy/resource-quotas/10-patch.namespace.openshift-etcd.yaml
  deploy/resource-quotas/10-patch.namespace.openshift-monitoring.yaml
  deploy/resource-quotas/15-resource.clusterresourcequota.yaml
  deploy/resource-quotas/Makefile
  deploy/resource-quotas/README.md
  deploy/resource-quotas/functions.mk
  deploy/resource-quotas/templates/10-patch.selectorsyncset.namespace.yaml.tmpl
  deploy/resource-quotas/templates/15-resource.clusterresourcequota.yaml.tmpl
  deploy/resource-quotas/values.mk
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  scripts/generate_syncset.py
  scripts/jsonify.awk
Labels: do-not-merge/hold, size/L

#25 Allow sre-admins to upgrade and use who-can
  deploy/sre-authorization/01-osd-sre-admin.ClusterRole.yaml
Labels: lgtm, size/S

#26 Added persistent storage for the monitoring stack
  README.md
  deploy/cluster-monitoring-config/cluster-monitoring-config.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: size/XL

#27 Fix patch issue
  deploy/resource-quotas/10-patch.namespace.openshift-etcd.yaml
  deploy/resource-quotas/10-patch.namespace.openshift-monitoring.yaml
  deploy/resource-quotas/templates/10-patch.selectorsyncset.namespace.yaml.tmpl
  scripts/jsonify.awk
Labels: lgtm, size/S

#28 Fix PV quota to 100Gi
  deploy/resource-quotas/15-resource.clusterresourcequota.yaml
  deploy/resource-quotas/values.mk
Labels: lgtm, size/XS

#29 Use scoped labels for resource quota exemption
  deploy/resource-quotas/10-patch.namespace.openshift-etcd.yaml
  deploy/resource-quotas/10-patch.namespace.openshift-monitoring.yaml
  deploy/resource-quotas/functions.mk
  deploy/resource-quotas/values.mk
  scripts/jsonify.awk
Labels: lgtm, size/S

#31 Regenerate and fix resource-quota and template
  deploy/resource-quotas/15-resource.clusterresourcequota.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: lgtm, size/XL

#33 Update KubeletConfig for OSD
  deploy/kubelet-config/01-patch.machineconfigpool.yaml
  deploy/kubelet-config/02-patch.machineconfigpool.yaml
  deploy/kubelet-config/03-kubelet-config.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: lgtm, size/XL

#32 Add pr check
  .kubeconfig
  Makefile
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  hack/app_sre_pr_check.sh
  project.mk
  scripts/generate_syncset.py
Labels: lgtm, size/XL

#34 Fix REPO_NAME and use it to set SELECTOR_SYNC_SET_DESTINATION
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  project.mk
Labels: size/XS

#30 Prune what sre-admins can do in OSD clusters.
  deploy/sre-authorization/01-osd-sre-admin.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, size/L

#38 SREP-1539: Add Machine API Exporter Prometheus Rule
  deploy/sre-prometheus/100-machine-api.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: size/XL

#37 Adding SRE's identity provider configuration
  .gitignore
  deploy/sre-authorization/10-osd-ldap-ca-configmap.ConfigMap.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  scripts/templates/template.yaml
Labels: lgtm, size/XXL

#39 Add alerts for SRE operators being offline for 15 minutes
  deploy/sre-prometheus/100-configure-alertmanager-operator.PrometheusRule.yaml
  deploy/sre-prometheus/100-dedicated-admin-operator.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: lgtm, size/M

#35 Fix kubeletconfig error
  deploy/kubelet-config/03-kubelet-config.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: lgtm, size/XXL
