Repository openshift/managed-cluster-config, pull requests merged in 2020-02, with the labels that each got.

#202 Upgrade script checks CIS name, not image
  scripts/cluster-upgrade.sh
Labels: approved, lgtm, size/XS

#203 move monitoring solutions to infra
  deploy/cluster-monitoring-config/cluster-monitoring-config.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/M

#201 move cluster ingress to infra nodes
  deploy/osd-ingress/router-infraNodes.patch.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/M

#204 Enhancements to the upgrade script.
  scripts/cluster-upgrade.sh
Labels: approved, lgtm, size/M

#199 deploy image-registry on infra nodes
  deploy/osd-registry/registry-infraNodes.patch.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/S

#192 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#198 Rename alertmanager configuration secret name
  deploy/osd-customer-monitoring/05-prometheus-k8s-role.yaml
  deploy/osd-customer-monitoring/05-role.yaml
  deploy/rbac-permissions-operator-config/00-dedicated-admins-project.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/M

#206 Only patch a resource once
  deploy/osd-registry/cluster.Config.patch.yaml
  deploy/osd-registry/registry-defaultRoute.patch.yaml
  deploy/osd-registry/registry-infraNodes.patch.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/M

#205 OSD-2807 Add permission for dedicated-admins to create events in their NSs
  deploy/rbac-permissions-operator-config/00-dedicated-admins-project.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/S

#208 allow dedicated-admins to manage alertmanagers without resourceNames
  deploy/osd-customer-monitoring/05-role.yaml
  deploy/rbac-permissions-operator-config/00-dedicated-admins-project.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XS

#210 Added supported value to aquasec clusterRoleBinding roleRef.kind
  deploy/osd-aquasec-operator/11-clusterrolebinding-image-scanner.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XS

#209 OSD-2809 - Enable missing Secrets permissions in openshift-strimzi NS
  deploy/osd-strimzi-operator/05-role.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XS

#211 Allow any "non-default", 'enabled' CIS to be a valid target
  scripts/cluster-upgrade.sh
Labels: approved, lgtm, size/S

#212 :bug: re #211: Fix logic in vercomp result
  scripts/cluster-upgrade.sh
Labels: approved, lgtm, size/XS

#197 [openshift-customer-monitoring] enable openshift-acme
  deploy/osd-customer-monitoring/05-role.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/M

#213 Remove all node placement constraints on router
  deploy/osd-ingress/router-infraNodes.patch.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/S

#215 For 4.3.0: Delete two Deployments that cause issues
  scripts/cluster-upgrade.sh
Labels: approved, lgtm, size/S

#216 Added RBAC permission for dedicated-admins to update namespaces
  deploy/rbac-permissions-operator-config/00-dedicated-admins-cluster.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XS

#217 Add RBAC permissions for dedicated-admins to update, create, delete g…
  deploy/rbac-permissions-operator-config/00-dedicated-admins-cluster.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/S

#218 Remove patch for osd-ingress
  deploy/osd-ingress/router-infraNodes.patch.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/S

#214 Script to rotate aws creds
  scripts/rotate-aws-creds.sh
Labels: approved, lgtm, size/L

#219 Add patch namespace permission for dedicated-admin user OSD-2874
  deploy/rbac-permissions-operator-config/00-dedicated-admins-cluster.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XS

#220 Add get groups permission for dedicated-admin user OSD-2817
  deploy/rbac-permissions-operator-config/00-dedicated-admins-cluster.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XS

#221 added back the ingress pod landing on infra nodes
  deploy/osd-ingress/router-infraNodes.patch.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/M

#222 Fix provider for OperatorHub
  deploy/osd-curated-operatorsources/10-curated-certified-operators.OperatorSource.yaml
  deploy/osd-curated-operatorsources/10-curated-community-operators.OperatorSource.yaml
  deploy/osd-curated-operatorsources/10-curated-redhat-operators.OperatorSource.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/S

#223 Added secret names to managed by openshift-acme
  deploy/osd-customer-monitoring/05-role.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XS

#225 Revert "Add get/list groups permission for dedicated-admin user OSD-2…
  deploy/rbac-permissions-operator-config/00-dedicated-admins-cluster.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XS

#227 Many changes to the cluster-upgrade script, added ClusterUpgradingSRE alert
  deploy/sre-prometheus/100-cluster-upgrade.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  scripts/cluster-upgrade.sh
Labels: approved, lgtm, size/L

#226 Fix osd customer monitoring acme-related secrets
  deploy/osd-customer-monitoring/05-role.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XS

#230 Change image pruner to ignore invalid refs
  deploy/sre-pruning/110-pruning-images.CronJob.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XS

#231 Add sss-config.yaml to support some overrides for SSS generation
  README.md
  deploy/osd-operatorhub-crd/00-operatorhub.crd.yaml
  deploy/osd-operatorhub-crd/sss-config.yaml
  deploy/sre-prometheus/aws/sss-config.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  scripts/generate_syncset.py
Labels: approved, lgtm, size/XXL

#232 Add support for podman
  Dockerfile
  Makefile
Labels: approved, lgtm, size/XS

#229 Updated EBS stuck attaching/detaching alerts
  deploy/sre-prometheus/aws/100-stuck-volumes.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/S

#233 Update pruning configuration
  deploy/sre-pruning/110-pruning-builds.CronJob.yaml
  deploy/sre-pruning/110-pruning-deployments.CronJob.yaml
  deploy/sre-pruning/110-pruning-images.CronJob.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/S

#228 Better validation for node upgrades.
  scripts/cluster-upgrade.sh
Labels: approved, lgtm, size/M

#235 Add get/list permissions on groups for dedicated-admin OSD-2817
  deploy/rbac-permissions-operator-config/00-dedicated-admins-cluster.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XS

#237 Remove legacy operatorhub and operatorsource things
  deploy/osd-curated-operators/00-cvo-overrides.patch.yaml
  deploy/osd-curated-operators/10-curated-certified-operators.patch.yaml
  deploy/osd-curated-operators/10-curated-community-operators.patch.yaml
  deploy/osd-curated-operators/10-curated-redhat-operators.patch.yaml
  deploy/osd-operatorhub-crd/00-operatorhub.crd.yaml
  deploy/osd-operatorhub-crd/sss-config.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#236 Added LoggingOperatorVersionInvalidSRE alert
  deploy/sre-prometheus/100-logging-channels.PrometheusRules.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/M
