Repository openshift/managed-cluster-config, pull requests merged in 2020-03, with the labels that each got.

#224 Add LP SRE Cluster admin and RHMI SRE RBAC
  deploy/layered-sre-authorization/00-layered-sre-cluster-admins.ClusterRoleBinding.yaml
  deploy/layered-sre-authorization/00-layered-sre-cluster-admins.Group.yaml
  deploy/layered-sre-authorization/01-layered-cs-sre-admin-cluster.ClusterRole.yaml
  deploy/layered-sre-authorization/01-layered-cs-sre-admin-project.ClusterRole.yaml
  deploy/layered-sre-authorization/01-layered-cs-sre-admins.Group.yaml
  deploy/layered-sre-authorization/02-layered-cs-sre-admin.SubjectPermission.yaml
  deploy/layered-sre-authorization/sss-config.yaml
  deploy/sre-prometheus/100-layered-sre-elevation.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  scripts/templates/template.yaml
Labels: approved, lgtm, size/L

#239 Replace cincinatti call with check of clusterversion
  scripts/cluster-upgrade.sh
Labels: approved, lgtm, size/M

#240 Added new permissions to CS SRE group that are needed for SOPS
  deploy/layered-sre-authorization/01-layered-cs-sre-admin-cluster.ClusterRole.yaml
  deploy/layered-sre-authorization/01-layered-cs-sre-admin-project.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/M

#242 added the RBAC for ded admin to manage the DNS forwarder
  deploy/rbac-permissions-operator-config/00-dedicated-admins-cluster.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/S

#243 dedicated-admin: dns fix and dns config map
  deploy/rbac-permissions-operator-config/00-dedicated-admins-cluster.ClusterRole.yaml
  deploy/rbac-permissions-operator-config/03-dedicated-admins-dns.Role.yaml
  deploy/rbac-permissions-operator-config/03-dedicated-admins-dns.RoleBinding.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/M

#244 Remove NoNodeObjectForMachine alerts
  deploy/sre-prometheus/100-machine-api.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/M

#247 Update OWNERS with leads list
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#248 Removing CS SRE ability to delete namespaces and RHMI installation CR
  deploy/layered-sre-authorization/01-layered-cs-sre-admin-cluster.ClusterRole.yaml
  deploy/layered-sre-authorization/01-layered-cs-sre-admin-project.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/M

#250 Allow dedicated-admins to 'list' resource 'namespaces'
  deploy/rbac-permissions-operator-config/00-dedicated-admins-cluster.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XS

#252 Removing resourceNames from CS SRE clusterresourcequotas RBAC
  deploy/layered-sre-authorization/01-layered-cs-sre-admin-cluster.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XS

#251 Added APAC to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS, tide/merge-method-squash

#253 Allow dedicated-admins to manage additional ca.crt in cluster
  deploy/customer-registry-cas/10-dedicated-admins-registry-cas.ClusterRole.yaml
  deploy/customer-registry-cas/15-dedicated-admins-registry-cas.Role.yaml
  deploy/customer-registry-cas/20-dedicated-admins-registry-cas.ClusterRoleBinding.yaml
  deploy/customer-registry-cas/25-dedicated-admins-registry-cas.RoleBinding.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, do-not-merge/hold, lgtm

#254 Updated rbac for some roles that didn't include dedicated-admin SA
  deploy/rbac-permissions-operator-config/01-dedicated-admins-operators.RoleBinding.yaml
  deploy/rbac-permissions-operator-config/02-dedicated-admins-marketplace.RoleBinding.yaml
  deploy/rbac-permissions-operator-config/03-dedicated-admins-dns.RoleBinding.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm

#256 Grant customer installed opeartor's CRD RBAC to dedicated-admins
  deploy/rbac-permissions-operator-config/03-dedicated-admins-cluster.ClusterRole.yaml
  deploy/rbac-permissions-operator-config/03-dedicated-admins-project.ClusterRole.yaml
  deploy/rbac-permissions-operator-config/05-dedicated-admins-aggregate-cluster.ClusterRole.yaml
  deploy/rbac-permissions-operator-config/05-dedicated-admins-aggregate-project.ClusterRole.yaml
  deploy/rbac-permissions-operator-config/07-dedicated-admins-cluster.ClusterRoleBinding.yaml
  deploy/rbac-permissions-operator-config/10-dedicated-admins-operators.Role.yaml
  deploy/rbac-permissions-operator-config/10-dedicated-admins-operators.RoleBinding.yaml
  deploy/rbac-permissions-operator-config/20-dedicated-admins-marketplace.Role.yaml
  deploy/rbac-permissions-operator-config/20-dedicated-admins-marketplace.RoleBinding.yaml
  deploy/rbac-permissions-operator-config/30-dedicated-admins-dns.Role.yaml
  deploy/rbac-permissions-operator-config/30-dedicated-admins-dns.RoleBinding.yaml
  deploy/rbac-permissions-operator-config/50-dedicated-admins-serviceaccounts.SubjectPermission.yaml
  deploy/rbac-permissions-operator-config/50-dedicated-admins.SubjectPermission.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm

#257 Move container engine to var and default to 'docker'
  Makefile
Labels: approved, lgtm

#259 Fix dedicated-admins RBAC aggregation
  deploy/rbac-permissions-operator-config/03-dedicated-admins-cluster.ClusterRole.yaml
  deploy/rbac-permissions-operator-config/03-dedicated-admins-project.ClusterRole.yaml
  deploy/rbac-permissions-operator-config/05-dedicated-admins-aggregate-cluster.ClusterRole.yaml
  deploy/rbac-permissions-operator-config/05-dedicated-admins-aggregate-project.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm

#258 allow dedicated-admins to run `oc adm top {node,pod}`
  deploy/rbac-permissions-operator-config/05-dedicated-admins-aggregate-cluster.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm

#261 Value of resourceApplyMode is case sensitive!
  README.md
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  scripts/generate_syncset.py
  scripts/templates/selectorsyncset.yaml
  scripts/templates/template.yaml
Labels: approved, lgtm

#262 Wait for 5 minutes before firing the DNS error alerts. Also add messa…
  deploy/sre-prometheus/100-dns-latency.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm

#263 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, lgtm

#260 Updated PV alerts
  deploy/sre-prometheus/100-check-full-cust-pv.PrometheusRule.yaml
  deploy/sre-prometheus/100-sre-pv.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm

#241 Revert osd-customer-monitoring openshift-acme
  deploy/osd-customer-monitoring/05-role.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/M

#268 Adding RBAC for CS SRE to view pod logs
  deploy/layered-sre-authorization/01-layered-cs-sre-admin-project.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm

#269 OSD-2801 Enable dedicated-admins to manage operators in customer NS
  deploy/ccs-dedicated-admins/03-dedicated-admins-manage-operators.ClusterRole.yaml
  deploy/ccs-dedicated-admins/sss-config.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm

#266 Fix fix pr check and fix failing pr checks
  deploy/sre-prometheus/100-excessive-memory.PrometheusRule.yaml
  deploy/sre-prometheus/100-layered-sre-elevation.PrometheusRule.yaml
  deploy/sre-prometheus/100-sre-elevation.PrometheusRule.yaml
  deploy/sre-prometheus/100-sre-pv.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  hack/app_sre_pr_check.sh
Labels: approved, lgtm

#270 Update managed-velero-operator to v0.2.117-ededc3e
  deploy/managed-velero-operator/050-velero.CustomResourceDefinition.yaml
  deploy/managed-velero-operator/110-velero.ClusterRole.yaml
  deploy/managed-velero-operator/110-velero.Role.yaml
  deploy/managed-velero-operator/135-velero.Deployment.yaml
  deploy/velero-configuration/100-velero.Velero.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm

#265 Added custom alert for tracking monthly SLA
  deploy/sre-prometheus/100-sre-api-errors.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm

#271 Corrected api error rule
  deploy/sre-prometheus/100-sre-api-errors.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm

#272 Corrected api error rule
  deploy/sre-prometheus/100-sre-api-errors.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm

#273 Adding SelectorSyncIdentityProvider for Google Auth
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  scripts/templates/template.yaml
Labels: approved, lgtm

#275 Fix indentation for osd-sre-google-identityprovider SelectorSyncIdent…
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  scripts/templates/template.yaml
Labels: approved, lgtm

#276 Fix typo in matchExpressions, missing 's'
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  scripts/templates/template.yaml
Labels: approved, lgtm

#274 Only curate operators for non-CCS clusters
  deploy/osd-curated-operatorsources-revert/00-operatorhub.cr.yaml
  deploy/osd-curated-operatorsources-revert/README.md
  deploy/osd-curated-operatorsources-revert/sss-config.yaml
  deploy/osd-curated-operatorsources/sss-config.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  scripts/generate_syncset.py
Labels: approved, lgtm

#277 Fix issue with curated operatorsources matchExpressions
  deploy/osd-curated-operatorsources-revert/sss-config.yaml
  deploy/osd-curated-operatorsources/sss-config.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm
