Repository openshift/managed-cluster-config, pull requests merged in 2020-01, with the labels that each got.

#175 Allow dedicated admins to view router metrics
  deploy/rbac-permissions-operator-config/00-dedicated-admins-cluster.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/S

#176 Add selfsubjectaccessreviews create permission for dedicate-admin-cluster role
  deploy/rbac-permissions-operator-config/00-dedicated-admins-cluster.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#177 move managed-velero-operator to infra node
  deploy/managed-velero-operator/135-velero.Deployment.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XXL

#178 Ensure files are processed in alphabetic order
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  scripts/generate_syncset.py
Labels: approved, lgtm, size/XXL

#180 bump managed-velero-operator image
  deploy/managed-velero-operator/135-velero.Deployment.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XS

#181 Fix typo in the comment
  deploy/rbac-permissions-operator-config/00-dedicated-admins-cluster.ClusterRole.yaml
Labels: approved, lgtm, size/XS

#182 allow dedicated-admin to create project-request template in openshift-config
  deploy/osd-project-request-template/02-role.dedicated-admins-project-request.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XS

#184 adding label to openshift-customer-monitoring
  deploy/osd-customer-monitoring/00-namespace.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm

#186 Update managed-velero-operator to v0.1.64-c5ab0f3
  deploy/managed-velero-operator/130-velero.CredentialRequest.yaml
  deploy/managed-velero-operator/135-velero.Deployment.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/S

#187 Update quota selectorsyncsets to not be created for BYOC (CCS) clusters
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  scripts/templates/template.yaml
Labels: approved, lgtm, size/L

#188 Give permissions for dedicated-admins to manage ProwJobs and READ CRDs
  deploy/rbac-permissions-operator-config/00-dedicated-admins-project.ClusterRole.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/M

#189 Reserve redhat-.* namespace for layered products.
  deploy/rbac-permissions-operator-config/00-dedicated-admins-serviceaccounts.SubjectPermission.yaml
  deploy/rbac-permissions-operator-config/00-dedicated-admins.SubjectPermission.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/S

#190 OSD-2711 - Increase maintenance window duration to 60min during cluster upgrades
  scripts/cluster-upgrade.sh
Labels: approved, lgtm, size/XS

#191 Remove Loadbalancer quotas > 20
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
  scripts/templates/template.yaml
Labels: approved, lgtm, size/L

#193 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#194 allow all verbs on project-request template for dedicated-admins
  deploy/osd-project-request-template/02-role.dedicated-admins-project-request.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/S

#195 remove resourceNames from dedicated-admins-project-request
  deploy/osd-project-request-template/02-role.dedicated-admins-project-request.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XS

#196 Bump m-v-o to 6bca798
  deploy/managed-velero-operator/135-velero.Deployment.yaml
  hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl
Labels: approved, lgtm, size/XS
