Repository openshift/managed-cluster-config, pull requests merged in 2021-01, with the labels that each got.

#608 Fall back to docker hub image
  .github/workflows/makecommit.yml
  Makefile
Labels: approved, lgtm

#612 CSSRE-1415: Added tekton.dev project access.
  deploy/backplane/cssre/rhmi/01-rhmi-cssre-admins-project.ClusterRole.yaml
  deploy/backplane/cssre/rhoam/01-rhoam-cssre-admins-project.ClusterRole.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#609 Don't back up unnecessary objects
  deploy/velero-configuration/110-velero.Schedules.yaml
  deploy/velero-configuration/hive-specific/111-velero.Schedules.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#611 Backplane prod
  deploy/backplane/cee/config.yaml
  deploy/backplane/config.yaml
  deploy/backplane/cssre/config.yaml
  deploy/backplane/cssre/rhmi/config.yaml
  deploy/backplane/cssre/rhoam/config.yaml
  deploy/backplane/elevated-sre/config.yaml
  deploy/backplane/srep/config.yaml
  deploy/layered-sre-authorization/README.md
  deploy/layered-sre-authorization/config.yaml
  deploy/layered-sre-authorization/rhmi/config.yaml
  deploy/layered-sre-authorization/rhoam/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#613 Revert "Adding in uwm for stg"
  deploy/cluster-monitoring-config-uwm/cluster-monitoring-config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#614 remove quick fix to add backplane-srep ns
  deploy/osd-serviceaccounts/00-srep.namespace.yml
  deploy/osd-serviceaccounts/README.md
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#616 Add workaround for BZ1915661
  deploy/bz1915661/10-osd-pruner.ClusterRole.yaml
  deploy/bz1915661/OWNERS
  deploy/bz1915661/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#620 Unfreeze logging as 2020 holiday freeze has lifted
  deploy/osd-logging/freeze/00-configmap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#623 Changing SOP link for v4 KubeNodeUnschedulableSRE alert
  deploy/sre-prometheus/100-node-unschedulable.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#406 Remove alert DNSLatencyOver200ms5MinSRE
  deploy/sre-prometheus/100-dns-latency.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, lifecycle/frozen

#622 Add PR check to detect changes to rolerefs in rolebindings/clusterrolebingings
  hack/app_sre_pr_check.sh
Labels: approved, lgtm, tide/merge-method-squash

#624 Add limits to Thanos pods - see OSD-6250
  deploy/cluster-monitoring-config-uwm/cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config/cluster-monitoring-config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#615 OSD-5555: Change maxUnhealthy to 2 so MHC works in 2-worker clusters
  deploy/osd-machine-api/010-machine-api.srep-infra-healthcheck.MachineHealthCheck.yaml
  deploy/osd-machine-api/011-machine-api.srep-worker-healthcheck.MachineHealthCheck.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#627 Readme: Add note about github action
  README.md
Labels: approved, lgtm

#628 OHSS-2615 ded-admin can update installplan in openshift-operators
  deploy/rbac-permissions-operator-config/10-dedicated-admins-operators.Role.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#619 Add components for observatorium token refresher
  deploy/osd-token-refresher/01-token-refresher.Deployment.yaml
  deploy/osd-token-refresher/02-token-refresher.Service.yaml
  deploy/osd-token-refresher/03-token-refresher.NetworkPolicy.yaml
  deploy/osd-token-refresher/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/templates/template.yaml
Labels: approved, lgtm

#630 Fix token-refresher deployment with correct escaping and flag name
  deploy/osd-token-refresher/01-token-refresher.Deployment.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#629 Add PoC for Cluster Readiness
  deploy/osd-cluster-ready/10-osd-ready.ServiceAccount.yaml
  deploy/osd-cluster-ready/20-osd-ready.Role.yaml
  deploy/osd-cluster-ready/40-osd-ready.RoleBinding.yaml
  deploy/osd-cluster-ready/50-osd-ready.Job.yaml
  deploy/osd-cluster-ready/config.yaml
  deploy/sre-prometheus/100-alertmanager-silence-active.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#631 Allow Cluster Ready Job to Deploy to prod
  deploy/osd-cluster-ready/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#633 Tuned thanosQuerier cpu limit so avoid throttle
  deploy/cluster-monitoring-config-uwm/cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config/cluster-monitoring-config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#585 Add permissions to dedicated for the openshift pipelines operator
  deploy/rbac-permissions-operator-config/05-dedicated-admins-aggregate-cluster.ClusterRole.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#634 Grant dedicated-admins roles/permissions to manage UWM-related CRs
  deploy/osd-user-workload-monitoring/01-dedicated-admins-uwm-config-edit.RoleBinding.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#635 Add MasterNodesNeedResizingSRE alert
  deploy/sre-prometheus/100-control-plane-resizing.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#632 Add SSS to patch candidate and fast channels in ClusterVersion
  deploy/osd-channel-patch/README.md
  deploy/osd-channel-patch/candidate-4.5/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/candidate-4.5/config.yaml
  deploy/osd-channel-patch/candidate-4.6/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/candidate-4.6/config.yaml
  deploy/osd-channel-patch/candidate-4.7/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/candidate-4.7/config.yaml
  deploy/osd-channel-patch/candidate-4.8/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/candidate-4.8/config.yaml
  deploy/osd-channel-patch/candidate-4.9/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/candidate-4.9/config.yaml
  deploy/osd-channel-patch/fast-4.5/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/fast-4.5/config.yaml
  deploy/osd-channel-patch/fast-4.6/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/fast-4.6/config.yaml
  deploy/osd-channel-patch/fast-4.7/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/fast-4.7/config.yaml
  deploy/osd-channel-patch/fast-4.8/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/fast-4.8/config.yaml
  deploy/osd-channel-patch/fast-4.9/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/fast-4.9/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, size/XXL

#638 Added SSS to patch stable channels
  deploy/osd-channel-patch/README.md
  deploy/osd-channel-patch/stable-4.5/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/stable-4.5/config.yaml
  deploy/osd-channel-patch/stable-4.6/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/stable-4.6/config.yaml
  deploy/osd-channel-patch/stable-4.7/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/stable-4.7/config.yaml
  deploy/osd-channel-patch/stable-4.8/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/stable-4.8/config.yaml
  deploy/osd-channel-patch/stable-4.9/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/stable-4.9/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#641 Tuned thanosQuerier cpu limit up to allow some room for larger workloads
  deploy/cluster-monitoring-config-uwm/cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config/cluster-monitoring-config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#642 Ignore PrometheusRuleFailures alerts for upgrade health checks [OSD-6319]
  deploy/managed-upgrade-operator-config/10-managed-upgrade-operator-configmap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#639 OHSS-2561 Extend hive integration token timeout
  deploy/osd-oauth-templates/ohss-2561/README.md
  deploy/osd-oauth-templates/ohss-2561/config.yaml
  deploy/osd-oauth-templates/ohss-2561/hive-integration-oauth.patch.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#637 Add workaround for BZ1915081
  deploy/bz1915081/10-node-ca-tolerations.daemonset.patch.yaml
  deploy/bz1915081/OWNERS
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#640 Updated readme for patching channel
  deploy/osd-channel-patch/README.md
Labels: approved, lgtm

#643 OSD-6329 MUO to ignore CannotRetrieveUpdates for healthcheck
  deploy/managed-upgrade-operator-config/10-managed-upgrade-operator-configmap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#644 Removing osde2e-tweaks snowflake OSD-6311
  snowflake/README.md
  snowflake/osde2e-tweaks/20-osde2e-noalerts.serviceaccount.yaml
  snowflake/osde2e-tweaks/22-osde2e-noalerts.clusterrole.yaml
  snowflake/osde2e-tweaks/24-osde2e-noalerts.clusterrolebinding.yaml
  snowflake/osde2e-tweaks/README.md
  snowflake/osde2e-tweaks/config.yaml
  snowflake/osde2e-tweaks/production/10-noalerts-osde2e.cronjob.yaml
  snowflake/osde2e-tweaks/production/config.yaml
Labels: approved, lgtm

#645 Apply UWM to clusters without a uwm-disabled label
  deploy/cluster-monitoring-config-uwm/cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config-uwm/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#646 Revert "Apply UWM to clusters without a uwm-disabled label"
  deploy/cluster-monitoring-config-uwm/cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config-uwm/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm
