Repository openshift/managed-cluster-config, pull requests merged in 2021-09, with the labels that each got.

#916 Set kubelet-config to Upsert
  deploy/kubelet-config/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#905 Update backplane directory readme
  deploy/backplane/README.md
Labels: approved, lgtm

#908 OSD-7916 cronjob to clean backplane script resources
  deploy/osd-delete-backplane-script-resources/00-delete-backplane-script-resources.namespace.yml
  deploy/osd-delete-backplane-script-resources/10-delete-backplane-script-resources.rbac.yaml
  deploy/osd-delete-backplane-script-resources/20-delete-backplane-script-resources.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#900 Adding configmap for hive-managed resources and script to update it.
  deploy/osd-managed-resources/OWNERS
  deploy/osd-managed-resources/README.md
  deploy/osd-managed-resources/config.yaml
  deploy/osd-managed-resources/managed-namespaces.ConfigMap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  resources/managed/all-osd-resources.yaml
  scripts/managed-resources/generate-managed-list.py
  scripts/managed-resources/make-all-managed-lists.sh
Labels: approved, lgtm

#920 Allow SREP and dedicated-admins to view API server request counts
  deploy/backplane/srep/10-srep-admins-cluster.ClusterRole.yml
  deploy/rbac-permissions-operator-config/05-dedicated-admins-aggregate-cluster.ClusterRole.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#923 OSD-7566 sre source builds
  deploy/sre-build-test/20-build-test-ClusterRole.yaml
  deploy/sre-build-test/50-source-build-test.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#924 OSD-8306, Added Reader permissions to the openshift-backplane-managed…
  deploy/osd-backplane-managed-scripts/00-openshift-backplane-managed-scripts.Namespace.yml
  deploy/osd-backplane-managed-scripts/10-openshift-backplane-managed-scripts.ClusterRole.yml
  deploy/osd-backplane-managed-scripts/20-openshift-backplane-managed-scripts.ClusterRoleBinding.yml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#927 [OSD-8405] SREP should be able to read CSR objects in cluster
  deploy/backplane/srep/10-srep-admins-cluster.ClusterRole.yml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#928 fix matchlabels for ocs-converged + fix matchlabel indents
  deploy/backplane/mtsre/config.yaml
  deploy/backplane/mtsre/managed-odh/config.yaml
  deploy/backplane/mtsre/ocs-converged/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#929 allow CONTAINER_ENGINE var to be overriden from the outside
  Makefile
Labels: approved, lgtm

#921 OSD-6381 remove ssh on non-hive clusters
  deploy/cloud-ingress-operator-configuration/sshd/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#904 Remove leftovers after removing old IDP RBACs
  deploy/osd-must-gather-operator/02-osd-devaccess.Role.yaml
  deploy/osd-must-gather-operator/03-osd-devaccess.RoleBinding.yaml
  deploy/osd-pcap-collector/01-pcap-collector-scc.yaml
  deploy/osd-pcap-collector/02-pcap-collector-ClusterRole.yaml
  deploy/osd-pcap-collector/03-pcap-collector-ClusterRoleBind.yaml
  deploy/sre-prometheus/100-sre-elevation.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#930 add backplane rbac access for reference addon
  deploy/backplane/mtsre/config.yaml
  deploy/backplane/mtsre/reference-addon/10-mtsre-reference-addon-admins.SubjectPermission.yml
  deploy/backplane/mtsre/reference-addon/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, ok-to-test

#893 Update makecommit.yml
  .github/workflows/makecommit.yml
Labels: approved, lgtm

#933 Remove CSV abnormal alerts after 4.8
  deploy/sre-prometheus/pre-4.8/100-csv-abnormal.PrometheusRule.yaml
  deploy/sre-prometheus/pre-4.8/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#931 Update apiVersion for the rebalance-infra-nodes CronJob to batch/v1beta1
  deploy/osd-rebalance-infra-nodes/10-osd-rebalance-infra-nodes.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#934 [OSD-7738] Document all namespaces that are managed by Add-Ons
  resources/addons-namespaces/main.yaml
  scripts/addons-namespaces/README.md
  scripts/addons-namespaces/generate-add-ons-list.py
Labels: approved, lgtm, tide/merge-method-squash

#793 OSD-7065: Pull token-refresher by digest
  deploy/osd-token-refresher/01-token-refresher.Deployment.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#917 OSD-6030: Remove OpenShift_SRE from non-hive clusters
  deploy/sre-pruning/105-pruning.rbac.ClusterRole.yaml
  deploy/sre-pruning/120-pruning.openshiftsreidp.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#936 Adding 'openshift-monitoring' to the managed namespaces list
  deploy/osd-managed-resources/managed-namespaces.ConfigMap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  resources/managed/all-osd-resources.yaml
  scripts/managed-resources/generate-managed-list.py
Labels: approved, lgtm

#937 CEE should be allowed to delete MustGathers
  deploy/backplane/cee/20-cee-mustgather.Role.yml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#938 OSD-8028: Patch IngressController.spec.replicas to 3 for specific clusters
  deploy/cloud-ingress-operator-configuration/routerreplicas-OSD-8028/10-routerreplics.ingresscontroller.yaml
  deploy/cloud-ingress-operator-configuration/routerreplicas-OSD-8028/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/templates/template.yaml
Labels: approved, lgtm

#939 Rename routerreplicas-OSD-8028 to routerreplicas-osd-8028
  deploy/cloud-ingress-operator-configuration/routerreplicas-osd-8028/10-routerreplics.ingresscontroller.yaml
  deploy/cloud-ingress-operator-configuration/routerreplicas-osd-8028/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#940 Specify namespace of the default ingress controller
  deploy/cloud-ingress-operator-configuration/routerreplicas-osd-8028/10-routerreplics.ingresscontroller.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#926 bz1997062: Adds DaemonSet to clean up pids
  deploy/bz1997062-crio-pid-leak/00-osd-cleanup-pids.DaemonSet.yaml
  deploy/bz1997062-crio-pid-leak/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#942 Updated image for osd-cluster-ready
  deploy/osd-cluster-ready/60-osd-ready.Job.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#944 update osd-cluster-ready
  deploy/osd-cluster-ready/50-osd-ready.ClusterRole.yaml
  deploy/osd-cluster-ready/60-osd-ready.Job.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#945 update osd-cluster-ready
  deploy/osd-cluster-ready/60-osd-ready.Job.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#946 Add 4.6.43 to list of impacted versions for BZ1997062
  deploy/bz1997062-crio-pid-leak/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#947 Remove CSO from SREP clusters
  deploy/container-security-operator/00-containerSecurityOperator-Namespace.yaml
  deploy/container-security-operator/10-containerSecurityOperator-OperatorGroup.yaml
  deploy/container-security-operator/20-containerSecurityOperator-Subscription.yaml
  deploy/container-security-operator/OWNERS
  deploy/container-security-operator/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#943 remove openshift-sre-ssh ns on none hive
  deploy/osd-ingress/00-openshift-sre-sshd.Namespace.yaml
  deploy/osd-ingress/config.yaml
  deploy/osd-ingress/controller/router-infraNodes.patch.yaml
  deploy/resource-quotas/10-patch.namespace.openshift-sre-sshd.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#948 Add apirequestcounts to CEE backplane access
  deploy/backplane/cee/01-cee-cluster-readers-ClusterRole.yml
  deploy/backplane/cee/02-cee-cluster-readers-ClusterRoleBinding.yml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm
