Repository openshift/managed-cluster-config, pull requests merged in 2021-11, with the labels that each got.

#963 OSD-6945 Add InfraNodesNeedResizingSRE alert
  deploy/sre-prometheus/100-control-plane-resizing.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#971 [OSD-8757] Update managed-resources script to generate OCP and addon's configmaps
  deploy/osd-managed-resources/addons-namespaces.ConfigMap.yaml
  deploy/osd-managed-resources/managed-namespaces.ConfigMap.yaml
  deploy/osd-managed-resources/ocp-namespaces.ConfigMap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/managed-resources/generate-managed-list.py
  scripts/managed-resources/make-all-managed-lists.sh
Labels: approved, lgtm, tide/merge-method-squash

#973 infra-rebalance every 15 minutes after osd-cluster-ready has succeeded
  deploy/osd-rebalance-infra-nodes/03-osd-rebalance-infra-nodes-openshift-monitoring.Role.yaml
  deploy/osd-rebalance-infra-nodes/07-osd-rebalance-infra-nodes.ConfigMap.yaml
  deploy/osd-rebalance-infra-nodes/10-osd-rebalance-infra-nodes.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#974 Remove unneeded variables from MCC config
  deploy/cloud-ingress-operator-configuration/apischeme/10-rh-api.apischeme.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/templates/template.yaml
Labels: approved, lgtm

#976 Add mrbarge as FL; Move dofinn to TL
  OWNERS_ALIASES
Labels: approved, lgtm

#979 Resolve OSD-8567 Fix errors when first time run this
  deploy/sre-build-test/50-source-build-test.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#972 add mkrts permissions to cssre
  deploy/backplane/cssre/config.yaml
  deploy/backplane/cssre/redhat-kas-fleetshard/10-mkrts-admins-project.ClusterRole.yml
  deploy/backplane/cssre/redhat-kas-fleetshard/20-mkrts-fleetshard-admins.SubjectPermission.yml
  deploy/backplane/cssre/redhat-kas-fleetshard/config.yaml
  deploy/backplane/mkrts/00-mkrts-namespace.yml
  deploy/backplane/mkrts/10-mkrts-readers-cluster.ClusterRole.yml
  deploy/backplane/mkrts/20-mkrts-readers.ClusterRoleBinding.yml
  deploy/backplane/mkrts/elevated-mkrts/00-impersonate-cluster-admin.ClusterRole.yml
  deploy/backplane/mkrts/elevated-mkrts/10-impersonate-cluster-admin.ClusterRoleBinding.yml
  deploy/backplane/mkrts/elevated-mkrts/20-cluster-admin.User.yml
  deploy/backplane/mkrts/redhat-kas-fleetshard/20-mkrts-fleetshard-admins.SubjectPermission.yml
  deploy/backplane/mkrts/redhat-kas-fleetshard/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#981 OSD-9006 silence CODown during upgrades
  deploy/managed-upgrade-operator-config/10-managed-upgrade-operator-configmap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#978 feat(osd-sts-ack): auto-add ack [OSD-8884]
  deploy/osd-cluster-acks/sts/4.9/config.yaml
  deploy/osd-cluster-acks/sts/4.9/osd-sts-ack_4.9_CloudCredential.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#983 fix(sts-ack): fix typo [OSD-8884]
  deploy/osd-cluster-acks/sts/4.9/osd-sts-ack_4.9_CloudCredential.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#745 Add a notification banner for clusters in Limited Support
  deploy/osd-ls-banner/10-limited-support-consolenotification.yaml
  deploy/osd-ls-banner/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, lifecycle/active

#984 Fix banner url
  deploy/osd-ls-banner/10-limited-support-consolenotification.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#985 Update limited support banner wording
  deploy/osd-ls-banner/10-limited-support-consolenotification.yaml
  deploy/osd-ls-banner/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#986 Use CONSOLE_BASE_URL now that it's available
  deploy/osd-ls-banner/10-limited-support-consolenotification.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/templates/template.yaml
Labels: approved, lgtm

#988 Collect namespaces listed as relatedObjects in clusteroperator
  deploy/osd-managed-resources/ocp-namespaces.ConfigMap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/managed-resources/generate-managed-list.py
Labels: approved, lgtm

#989 Deploy Managed Resources ConfigMaps To All Envs
  deploy/osd-managed-resources/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#992 Add port forwarding to managed kafka permissions
  deploy/backplane/cssre/redhat-kas-fleetshard/10-mkrts-admins-project.ClusterRole.yml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#991 Add ability for SRE to delete CSRs
  deploy/backplane/srep/10-srep-admins-cluster.ClusterRole.yml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm
