Repository openshift/managed-cluster-config, pull requests merged in 2022-09, with the labels that each got.

#1234 [MTSRE-611] feat(backplane): onboard backplane config for mcg-osd
  deploy/backplane/mcg/00-mcg.namespace.yml
  deploy/backplane/mcg/config.yaml
  deploy/backplane/mcg/mcg-osd/01-mcg-osd-cr-admins.ClusterRole.yml
  deploy/backplane/mcg/mcg-osd/10-mcg-mcg-osd-admins.SubjectPermission.yml
  deploy/backplane/mcg/mcg-osd/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1255 [Hypershift] Add operator policies for hypershift-specific operators
  resources/sts/4.11/openshift_capa_controller_manager_credentials_policy.json
  resources/sts/4.11/openshift_control_plane_operator_credentials_policy.json
  resources/sts/4.11/openshift_kube_controller_manager_credentials_policy.json
Labels: approved, lgtm, ok-to-test

#1250 [MTSRE-643] feat: adding nvidia gpu backplane config
  deploy/backplane/nvidia-gpu/00-nvidia-gpu.namespace.yml
  deploy/backplane/nvidia-gpu/config.yaml
  deploy/backplane/nvidia-gpu/nvidia-gpu/10-nvidia-gpu-admins.SubjectPermission.yml
  deploy/backplane/nvidia-gpu/nvidia-gpu/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  resources/addons-namespaces/main.yaml
Labels: approved, lgtm

#1266 Add new clusterroles for support roles.
  deploy/backplane/csa/00-csa.namespace.yml
  deploy/backplane/csa/10-csa-readers-cluster.ClusterRole.yml
  deploy/backplane/csa/10-csa-readers-cluster.ClusterRoleBinding.yml
  deploy/backplane/cse/00-cse.namespace.yml
  deploy/backplane/cse/10-cse-readers-cluster.ClusterRole.yml
  deploy/backplane/cse/10-cse-readers-cluster.ClusterRoleBinding.yml
  deploy/backplane/csm/00-csm.namespace.yml
  deploy/backplane/csm/10-csm-readers-cluster.ClusterRole.yml
  deploy/backplane/csm/10-csm-readers-cluster.ClusterRoleBinding.yml
  deploy/backplane/mobb/00-mobb.namespace.yml
  deploy/backplane/mobb/10-mobb-readers-cluster.ClusterRole.yml
  deploy/backplane/mobb/10-mobb-readers-cluster.ClusterRoleBinding.yml
  deploy/backplane/tam/00-tam.namespace.yml
  deploy/backplane/tam/10-tam-readers-cluster.ClusterRole.yml
  deploy/backplane/tam/10-tam-readers-cluster.ClusterRoleBinding.yml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1268 OSD-13086 clamav-images++
  deploy/osd-scanning/20-osd-scanning-logger-Daemonset.yaml
  deploy/osd-scanning/30-osd-scanning-scanner-Daemonset.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1269 Add stopgap alert for OCPBUGS-773
  deploy/sre-prometheus/100-runaway-sdn.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1270 Only look at the last sequential build status
  deploy/sre-build-test/50-source-build-test.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#1271 [FedRAMP] Conversion of VPCE to a namespaced CRD
  deploy/osd-avo-resources/us-gov-east-1/00-osd-avo-VpcEndpoint.yaml
  deploy/osd-avo-resources/us-gov-west-1/00-osd-avo-VpcEndpoint.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1272 [FedRAMP] AVO metrics are now namespaced
  deploy/sre-prometheus/fedramp/100-avo-pendingAcceptance.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1274 [FedRAMP] clamav-images++
  deploy/osd-scanning/20-osd-scanning-logger-Daemonset.yaml
  deploy/osd-scanning/30-osd-scanning-scanner-Daemonset.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1273 Add the `iam:CreatePolicy` permission to the OCM admin role
  resources/sts/4.11/sts_ocm_admin_permission_policy.json
Labels: approved, lgtm

#1275 [FedRAMP] clamsig-puller++
  deploy/osd-scanning/30-osd-scanning-scanner-Daemonset.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1276 [FedRAMP] clam-files is mounted at /clam for clamsig-puller
  deploy/osd-scanning/30-osd-scanning-scanner-Daemonset.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1277 OSD-13103 Adjust alert to >8GB consumption for SDN pods to tune false positives
  deploy/sre-prometheus/100-runaway-sdn.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1278 deploy/OCPBUGS-1341-PodNetworkConnectivityCheck-leak: CronJob pruner
  deploy/OCPBUGS-1341-PodNetworkConnectivityCheck-leak/00-OCPBUGS-1341.ServiceAccount.yaml
  deploy/OCPBUGS-1341-PodNetworkConnectivityCheck-leak/01-OCPBUGS-1341.Role.yaml
  deploy/OCPBUGS-1341-PodNetworkConnectivityCheck-leak/02-OCPBUGS-1341.RoleBinding.yaml
  deploy/OCPBUGS-1341-PodNetworkConnectivityCheck-leak/03-OCPBUGS-1341.ClusterRoleBinding.yaml
  deploy/OCPBUGS-1341-PodNetworkConnectivityCheck-leak/10-OCPBUGS-1341.CronJob.yaml
  deploy/OCPBUGS-1341-PodNetworkConnectivityCheck-leak/OWNERS
  deploy/OCPBUGS-1341-PodNetworkConnectivityCheck-leak/README.md
  deploy/OCPBUGS-1341-PodNetworkConnectivityCheck-leak/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1279 deploy/ocpbugs-1341-pod-network-connectivity-check-leak: Downcase and hyphenate
  deploy/ocpbugs-1341-pod-network-connectivity-check-leak/00-OCPBUGS-1341.ServiceAccount.yaml
  deploy/ocpbugs-1341-pod-network-connectivity-check-leak/01-OCPBUGS-1341.Role.yaml
  deploy/ocpbugs-1341-pod-network-connectivity-check-leak/02-OCPBUGS-1341.RoleBinding.yaml
  deploy/ocpbugs-1341-pod-network-connectivity-check-leak/03-OCPBUGS-1341.ClusterRoleBinding.yaml
  deploy/ocpbugs-1341-pod-network-connectivity-check-leak/10-OCPBUGS-1341.CronJob.yaml
  deploy/ocpbugs-1341-pod-network-connectivity-check-leak/OWNERS
  deploy/ocpbugs-1341-pod-network-connectivity-check-leak/README.md
  deploy/ocpbugs-1341-pod-network-connectivity-check-leak/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1281 addon operator metrics
  deploy/cluster-monitoring-config/cluster-monitoring-config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1282 Update FL for Team Rocket
  OWNERS_ALIASES
Labels: approved, lgtm

#1283 Add missing RBAC for sre-build-test to get serviceaccounts
  deploy/sre-build-test/20-build-test-ClusterRole.yaml
  deploy/sre-build-test/50-source-build-test.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1284 deploy/ocpbugs-1341-pod-network-connectivity-check-leak/10-OCPBUGS-1341.CronJob: Drop seccompProfile
  deploy/ocpbugs-1341-pod-network-connectivity-check-leak/10-OCPBUGS-1341.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1285 deploy/ocpbugs-1341-pod-network-connectivity-check-leak: seccompProfile sharding
  deploy/ocpbugs-1341-pod-network-connectivity-check-leak/no-seccomp/10-OCPBUGS-1341.CronJob.yaml
  deploy/ocpbugs-1341-pod-network-connectivity-check-leak/no-seccomp/config.yaml
  deploy/ocpbugs-1341-pod-network-connectivity-check-leak/seccomp/10-OCPBUGS-1341.CronJob.yaml
  deploy/ocpbugs-1341-pod-network-connectivity-check-leak/seccomp/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1286 deploy/ocpbugs-1341-pod-network-connectivity-check-leak: Set base config
  deploy/ocpbugs-1341-pod-network-connectivity-check-leak/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1287 updates suricata log-cleaner to remediate CVE
  deploy/osd-suricata/20-osd-suricata-Daemonset.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm
