Repository openshift/managed-cluster-config, pull requests merged in 2022-02, with the labels that each got.

#1038 OSD-9760 Add ocm-agent-operator pre-reqs to MCC
  deploy/osd-serviceaccounts/cronjob/10-osd-delete-ownerrefs.CronJob.yaml
  deploy/osd-serviceaccounts/oao/00-ocm-agent-operator.ServiceAccount.yaml
  deploy/osd-serviceaccounts/oao/README.md
  deploy/osd-serviceaccounts/oao/config.yaml
  deploy/rbac-permissions-operator-config/03-dedicated-admins-cluster.ClusterRole.yaml
  deploy/rbac-permissions-operator-config/03-dedicated-admins-project.ClusterRole.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  resources/managed/all-osd-resources.yaml
Labels: approved, lgtm

#1031 [OSD-9675] adding code to deploy osd-scanning daemonsets
  deploy/osd-scanning/00-osd-scanning-Namespace.yaml
  deploy/osd-scanning/05-osd-scanning-logger-ServiceAccount.yaml
  deploy/osd-scanning/05-osd-scanning-scanner-ServiceAccount.yaml
  deploy/osd-scanning/05-osd-scanning-scc-SecurityContextConstraint.yaml
  deploy/osd-scanning/10-osd-scanning-logger-Role.yaml
  deploy/osd-scanning/10-osd-scanning-logger-RoleBinding.yaml
  deploy/osd-scanning/10-osd-scanning-scanner-Role.yaml
  deploy/osd-scanning/10-osd-scanning-scanner-RoleBinding.yaml
  deploy/osd-scanning/20-osd-scanning-logger-Daemonset.yaml
  deploy/osd-scanning/25-osd-scanning-logger-Service.yaml
  deploy/osd-scanning/30-osd-scanning-scanner-Daemonset.yaml
  deploy/osd-scanning/OWNERS
  deploy/osd-scanning/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#1028 [OSD-8801] adding ids-tester weekly CronJob for suricata
  deploy/osd-ids-tester/100-ids-tester.Namespace.yaml
  deploy/osd-ids-tester/105-ids-tester.rbac.ServiceAccount.yaml
  deploy/osd-ids-tester/110-ids-tester-CronJob.yaml
  deploy/osd-ids-tester/OWNERS
  deploy/osd-ids-tester/README.md
  deploy/osd-ids-tester/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#1033 [OSD-9676] adding deploy config for suricata ds
  deploy/osd-suricata/00-osd-suricata-Namespace.yaml
  deploy/osd-suricata/05-osd-suricata-ServiceAccount.yaml
  deploy/osd-suricata/10-osd-suricata-Role.yaml
  deploy/osd-suricata/10-osd-suricata-RoleBinding.yaml
  deploy/osd-suricata/20-osd-suricata-Daemonset.yaml
  deploy/osd-suricata/OWNERS
  deploy/osd-suricata/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#1039 Fix suricata daemonset syntax
  deploy/osd-suricata/20-osd-suricata-Daemonset.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#1040 Add missing namespace to RoleBindings for Suricata/ClamAV
  deploy/osd-scanning/10-osd-scanning-logger-RoleBinding.yaml
  deploy/osd-scanning/10-osd-scanning-scanner-RoleBinding.yaml
  deploy/osd-suricata/10-osd-suricata-RoleBinding.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1041 OSD-9760 Fix SSS config for OAO ServiceAccount deployment
  deploy/osd-serviceaccounts/oao/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1043 Adding blrm as a functional lead
  OWNERS_ALIASES
Labels: approved, lgtm

#1024 Update osd-managed-resources configmaps and all-osd-resources.yaml
  deploy/osd-managed-resources/managed-namespaces.ConfigMap.yaml
  deploy/osd-managed-resources/ocp-namespaces.ConfigMap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  resources/managed/all-osd-resources.yaml
Labels: approved, lgtm

#1044 [OSD-9676] adding suricata-sa so the DS has the necessary permissions, ran make
  deploy/osd-suricata/20-osd-suricata-Daemonset.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1047 Fix Suricata Image and Add SCC
  deploy/osd-scanning/30-osd-scanning-scanner-Daemonset.yaml
  deploy/osd-suricata/05-osd-suricata-scc-SecurityContextConstraint.yaml
  deploy/osd-suricata/20-osd-suricata-Daemonset.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#1050 Tweaks the DNS Alert
  deploy/sre-prometheus/100-dns-latency.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, ok-to-test

#1051 Remove suricata-secrets From Suricata Daemonset
  deploy/osd-suricata/20-osd-suricata-Daemonset.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1053 adding missing /secrets volumeMount path to watcher
  deploy/osd-scanning/20-osd-scanning-logger-Daemonset.yaml
  deploy/osd-scanning/30-osd-scanning-scanner-Daemonset.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1057 Fix formatting for NotIn operator in the osd-token-refresher config
  deploy/osd-token-refresher/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, ok-to-test

#1056 [ OSD-9965 ] Add OCMAgent CR to MCC
  deploy/ocm-agent-operator-resources/10-ocm-agent-cr.yaml
  deploy/ocm-agent-operator-resources/README.md
  deploy/ocm-agent-operator-resources/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1058 OSD-5079 Update docs to define MUO silencing alert procedure
  deploy/managed-upgrade-operator-config/README.md
Labels: approved, lgtm

#1059 Standardize FedRAMP label usage
  deploy/osd-ids-tester/config.yaml
  deploy/osd-scanning/config.yaml
  deploy/osd-suricata/config.yaml
  deploy/osd-token-refresher/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1061 [MTSRE-464] AddonConnectors RBAC
  deploy/backplane/addon-connectors/00-addon-connectors.namespace.yml
  deploy/backplane/addon-connectors/10-addon-connectors-readers-cluster.ClusterRole.yml
  deploy/backplane/addon-connectors/20-addon-connectors-readers.ClusterRoleBinding.yml
  deploy/backplane/addon-connectors/addon-connectors/10-addon-connectors-admins.SubjectPermission.yml
  deploy/backplane/addon-connectors/addon-connectors/config.yaml
  deploy/backplane/addon-connectors/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  resources/addons-namespaces/main.yaml
  scripts/addons-namespaces/generate-add-ons-list.py
Labels: approved, lgtm

#1062 Add exec permissions to kafka pods
  deploy/backplane/cssre/redhat-kas-fleetshard/10-mkrts-admins-project.ClusterRole.yml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#1060 Update managed-namespaces configmap
  deploy/osd-managed-resources/managed-namespaces.ConfigMap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  resources/managed/all-osd-resources.yaml
Labels: approved, lgtm
