Repository openshift/managed-cluster-config, pull requests merged in 2022-12, with the labels that each got.

#1309 acm policies for dedicated-admin and cluster admin rbac
  Makefile
  README.md
  deploy/acm-policies/00-openshift-managed-rbac-policies.Namespace.yaml
  deploy/acm-policies/50-GENERATED-osd-cluster-admin.Policy.yaml
  deploy/acm-policies/50-GENERATED-rbac-permissions-operator-config.Policy.yaml
  deploy/acm-policies/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  project.mk
  scripts/generate-policy-config.py
  scripts/generate-policy.sh
  scripts/policy-generator-config.yaml
Labels: approved, lgtm

#1361 Make ACM policy generator not to walk directories
  deploy/acm-policies/50-GENERATED-backplane-srep.Policy.yaml
  deploy/acm-policies/50-GENERATED-backplane.Policy.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/generate-policy-config.py
Labels: approved, lgtm

#1363 Added rbac Policies for OSD-13912
  deploy/acm-policies/50-GENERATED-ccs-dedicated-admins.Policy.yaml
  deploy/acm-policies/50-GENERATED-customer-registry-cas.Policy.yaml
  deploy/acm-policies/50-GENERATED-osd-openshift-operators-redhat.Policy.yaml
  deploy/acm-policies/50-GENERATED-osd-pcap-collector.Policy.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/generate-policy-config.py
Labels: approved, lgtm

#1364 set security context for prune cronjobs
  deploy/sre-pruning/110-pruning-builds.CronJob.yaml
  deploy/sre-pruning/110-pruning-deployments.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1362 deploy/sre-build-test: Set 'ttlSecondsAfterFinished: 86400'
  deploy/sre-build-test/50-source-build-test.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1359 Update Cronjobs from batch/v1beta1 to batch/v1
  deploy/bz1980755/10-bz1980755.CronJob.yaml
  deploy/osd-curated-operatorsources-revert/10-osd-patch-subscription-source.CronJob.yaml
  deploy/osd-delete-backplane-script-resources/20-delete-backplane-script-resources.CronJob.yaml
  deploy/osd-delete-backplane-serviceaccounts/20-delete-backplane-serviceaccounts.CronJob.yaml
  deploy/osd-rebalance-infra-nodes/10-osd-rebalance-infra-nodes.CronJob.yaml
  deploy/osd-serviceaccounts/cronjob/10-osd-delete-ownerrefs.CronJob.yaml
  deploy/sre-build-test/50-source-build-test.CronJob.yaml
  deploy/sre-pruning/110-pruning-builds.CronJob.yaml
  deploy/sre-pruning/110-pruning-deployments.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1365 Revert "Merge pull request #1364 from jbpratt/update-prune-cronjobs"
  deploy/sre-pruning/110-pruning-builds.CronJob.yaml
  deploy/sre-pruning/110-pruning-deployments.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1366 Update the oc image
  Makefile
Labels: approved, lgtm

#1368 Exclude ACM generated files from roleref check
  hack/app_sre_pr_check.sh
Labels: approved, lgtm

#1367 Allow dedicated admins to view machine config pools
  deploy/rbac-permissions-operator-config/05-osd-readers.ClusterRole.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1371 Add segment telemetry for ROSA
  deploy/rosa-console-branding/telemetry/config.yaml
  deploy/rosa-console-branding/telemetry/osd-branding.console.Patch.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1373 Add env label for the metrics on management clusters
  deploy/hypershift-cluster-monitoring-config/cluster-monitoring-config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1375 updated the policies namespace
  deploy/acm-policies/00-openshift-managed-rbac-policies.Namespace.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1379 added Clusterrolebinding and Rolebinding generation for Subjectpermission
  deploy/acm-policies/50-GENERATED-backplane-srep-sp.Policy.yaml
  deploy/acm-policies/50-GENERATED-ccs-dedicated-admins-sp.Policy.yaml
  deploy/acm-policies/50-GENERATED-rbac-permissions-operator-config-sp.Policy.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/generate-subjectpermissions-policy-config.py
Labels: approved, lgtm

#1377 Added missing "ENV" parameter
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/templates/template.yaml
Labels: approved, lgtm

#1358 Osd 13558 add alert for non system change validation webhook configurations metric
  deploy/ocm-agent-operator-managednotifications/10-managednotifications-cr.yaml
  deploy/sre-prometheus/ocm-agent/100-ocm-agent.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#1384 Fix up generation
  Dockerfile
  Makefile
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/generate-policy-config.py
  scripts/generate-policy.sh
  scripts/generate-subjectpermissions-policy-config.py
  scripts/generate_template.py
Labels: approved, lgtm

#1382 openshift-backplane-addon-connectors should access all namespace starting with ting with redhat-openshift-connectors
  deploy/backplane/addon-connectors/addon-connectors/10-addon-connectors-admins.SubjectPermission.yml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, ok-to-test

#1383 Only run workflow on fork feature branches, not on fork master branches
  .github/workflows/makecommit.yml
Labels: approved, lgtm

#1380 loggerservice to use TLS
  deploy/osd-scanning/10-osd-scanning-logger-ClusterRole.yaml
  deploy/osd-scanning/20-osd-scanning-logger-Daemonset.yaml
  deploy/osd-scanning/25-osd-scanning-logger-Service.yaml
  deploy/osd-scanning/30-osd-scanning-scanner-Daemonset.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1376 Enable pcap-collector-creds secret permissions for CEE/SREP
  deploy/acm-policies/50-GENERATED-backplane-srep.Policy.yaml
  deploy/backplane/cee/30-cee-pcap-collector.Role.yml
  deploy/backplane/cee/60-cee-pcap-collector.RoleBinding.yml
  deploy/backplane/srep/30-cee-pcap-collector.Role.yml
  deploy/backplane/srep/40-cee-pcap-collector.RoleBinding.yml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1388 OSD-14247 fix sre-build-test race condition
  deploy/sre-build-test/50-source-build-test.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1390 Upate hypershift
  deploy/rhobs-hypershift-config/00-rhobs-credential-syncset.yaml
  deploy/rhobs-hypershift-config/config.yaml
  deploy/rhobs-hypershift-config/integration/config.yaml
  deploy/rhobs-hypershift-config/production/config.yaml
  deploy/rhobs-hypershift-config/stage/00-rhobs-credential-syncset.yaml
  deploy/rhobs-hypershift-config/stage/config.yaml
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
Labels: approved, lgtm

#1381 Add more backplane RBACs to hypershift
  deploy/acm-policies/50-GENERATED-backplane-cee-sp.Policy.yaml
  deploy/acm-policies/50-GENERATED-backplane-cee.Policy.yaml
  deploy/acm-policies/50-GENERATED-backplane-cse-sp.Policy.yaml
  deploy/acm-policies/50-GENERATED-backplane-cse.Policy.yaml
  deploy/acm-policies/50-GENERATED-backplane-csm-sp.Policy.yaml
  deploy/acm-policies/50-GENERATED-backplane-csm.Policy.yaml
  deploy/acm-policies/50-GENERATED-backplane-cssre-sp.Policy.yaml
  deploy/acm-policies/50-GENERATED-backplane-cssre.Policy.yaml
  deploy/acm-policies/50-GENERATED-backplane-elevated-sre.Policy.yaml
  deploy/acm-policies/50-GENERATED-backplane-mobb-sp.Policy.yaml
  deploy/acm-policies/50-GENERATED-backplane-mobb.Policy.yaml
  deploy/acm-policies/50-GENERATED-backplane-tam-sp.Policy.yaml
  deploy/acm-policies/50-GENERATED-backplane-tam.Policy.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/generate-policy-config.py
  scripts/generate-subjectpermissions-policy-config.py
Labels: approved, lgtm

#1391 Add must-gather-operator namespace to hypershift
  deploy/acm-policies/50-GENERATED-osd-must-gather-operator.Policy.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/generate-policy-config.py
Labels: approved, lgtm

#1387 [OSD-12648] Add pagerduty service orchestration rule configmap
  deploy/pagerduty-service-orchestration/00-osd-serviceorchestration-configmap.yaml
  deploy/pagerduty-service-orchestration/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1385 Split installer policy into 2 policies (in separate files)
  resources/sts/4.11/sts_installer_core_permission_policy.json
  resources/sts/4.11/sts_installer_vpc_permission_policy.json
Labels: approved, lgtm
