Repository openshift/managed-cluster-config, pull requests merged in 2022-10, with the labels that each got.

#1265 Enable segement telemetry in prod
  deploy/osd-console-branding/telemetry/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1289 updates osd-cluster-ready-image for CVE fix
  deploy/osd-cluster-ready/job/10-osd-ready.Job.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#1290 Allow dedicated-admins to manage UWM Alertmanager
  deploy/osd-user-workload-monitoring/04-dedicated-admins-uwm-am-secret-role.Role.yaml
  deploy/osd-user-workload-monitoring/05-dedicated-admins-uwm-am-secret-rolebinding.RoleBinding.yaml
  deploy/osd-user-workload-monitoring/06-dedicated-admins-alert-route-editing.SubjectPermissions.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1292 CSSRE-2173 - Updating permissions for KafkaRebalance
  deploy/backplane/cssre/redhat-kas-fleetshard/10-mkrts-admins-project.ClusterRole.yml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, ok-to-test

#1294 updating clamsig-puller options and image
  deploy/osd-scanning/30-osd-scanning-scanner-Daemonset.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1296 Remove ineffective role/binding
  deploy/rbac-permissions-operator-config/20-dedicated-admins-marketplace.Role.yaml
  deploy/rbac-permissions-operator-config/20-dedicated-admins-marketplace.RoleBinding.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1299 Changing image URI to the version allowed in image.config.openshift.io
  deploy/ocpbugs-1341-pod-network-connectivity-check-leak/no-seccomp/10-OCPBUGS-1341.CronJob.yaml
  deploy/ocpbugs-1341-pod-network-connectivity-check-leak/seccomp/10-OCPBUGS-1341.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1303 Allow dedicated-admins to manage catalogsources in openshift-marketplace
  deploy/rbac-permissions-operator-config/20-dedicated-admins-marketplace.Role.yaml
  deploy/rbac-permissions-operator-config/20-dedicated-admins-marketplace.RoleBinding.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1304 Close OSD-13506 Remove crds deletion perms
  deploy/backplane/srep/10-srep-admins-cluster.ClusterRole.yml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1298 Add fluentd job label to FluentdNodeDownSRE alert expr
  deploy/sre-prometheus/extended-logging/101-parsed_fluentd_openshift-logging_collector.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#1305 osd-rebalance-infra-nodes to correct misscheduled dns-default pods
  deploy/osd-rebalance-infra-nodes/01-osd-rebalance-infra-nodes.ClusterRoleBinding.yaml
  deploy/osd-rebalance-infra-nodes/02-osd-rebalance-infra-nodes-openshift-dns.Role.yaml
  deploy/osd-rebalance-infra-nodes/02-osd-rebalance-infra-nodes-openshift-dns.RoleBinding.yaml
  deploy/osd-rebalance-infra-nodes/05-osd-rebalance-infra-nodes-openshift-security.RoleBinding.yaml
  deploy/osd-rebalance-infra-nodes/07-osd-rebalance-infra-nodes.ConfigMap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1307 Add SREP architects alias and restrict approvals for backplane dir
  OWNERS_ALIASES
  deploy/backplane/OWNERS
Labels: approved, lgtm

#1308 Scope down csa,csm,cse,mobb,tam permissions to use osd-readers
  deploy/backplane/csa/10-csa-readers-cluster.ClusterRole.yml
  deploy/backplane/cse/10-cse-readers-cluster.ClusterRole.yml
  deploy/backplane/csm/10-csm-readers-cluster.ClusterRole.yml
  deploy/backplane/mobb/10-mobb-readers-cluster.ClusterRole.yml
  deploy/backplane/tam/10-tam-readers-cluster.ClusterRole.yml
  deploy/rbac-permissions-operator-config/05-osd-readers.ClusterRole.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1310 Fix typo
  OWNERS_ALIASES
Labels: approved, lgtm, ok-to-test

#1311 OSD-13445: adds vpceacceptance objects for FedRAMP
  deploy/osd-avo-resources/fedramp-vpce-acceptance/00-osd-avo-vpcendpointacceptance-us-gov-east-1.yaml
  deploy/osd-avo-resources/fedramp-vpce-acceptance/00-osd-avo-vpcendpointacceptance-us-gov-west-1.yaml
  deploy/osd-avo-resources/fedramp-vpce-acceptance/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#1314 adding a new recording rule sre:sla:outage_minutes_28d
  deploy/cluster-monitoring-config/cluster-monitoring-config.yaml
  deploy/sre-prometheus/centralized-observability/100-sre-slo-recording-rules.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1315 add filter on code=~"([1-5]..)" to remove the request in code 0
  deploy/sre-prometheus/centralized-observability/100-sre-slo-recording-rules.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1306 enable the size based retention for platform prometheus
  deploy/cluster-monitoring-config-non-uwm/cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config/cluster-monitoring-config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1312 restructures AVO resources to account for future needs
  deploy/osd-avo-resources/fedramp-vpc-endpoints/us-gov-east-1/00-osd-avo-VpcEndpoint.yaml
  deploy/osd-avo-resources/fedramp-vpc-endpoints/us-gov-east-1/config.yaml
  deploy/osd-avo-resources/fedramp-vpc-endpoints/us-gov-west-1/00-osd-avo-VpcEndpoint.yaml
  deploy/osd-avo-resources/fedramp-vpc-endpoints/us-gov-west-1/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1317 update the SLA recording rule with RMO
  deploy/sre-prometheus/centralized-observability/100-sre-slo-recording-rules.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1318 removes avo acceptance to be handled elsewhere
  deploy/osd-avo-resources/fedramp-vpce-acceptance/00-osd-avo-vpcendpointacceptance-us-gov-east-1.yaml
  deploy/osd-avo-resources/fedramp-vpce-acceptance/00-osd-avo-vpcendpointacceptance-us-gov-west-1.yaml
  deploy/osd-avo-resources/fedramp-vpce-acceptance/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1319 update sla rule to get 1 when RMO sees full outage
  deploy/sre-prometheus/centralized-observability/100-sre-slo-recording-rules.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm
