Repository openshift/managed-cluster-config, pull requests merged in 2023-04, with the labels that each got.

#1574 Remove redundant action sts:GetCallerIdentity
  resources/sts/4.12/hypershift/sts_hcp_installer_permission_policy.json
  resources/sts/4.13/hypershift/sts_hcp_installer_permission_policy.json
Labels: approved, lgtm

#1540 (OSD-14058) feat: Add KubeJobFailingSRE alert
  deploy/sre-prometheus/100-sre-kubejobfailing.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1576 Add admin gate for 4.13
  deploy/osd-cluster-acks/ocp/4.13/admin-gates.yaml
  deploy/osd-cluster-acks/ocp/4.13/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1578 Prevent CPMS from being enabled on 4.12 clusters
  deploy/osd-14634-disable-cpms/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1566 Remove privileged IAM permissions for HCP
  resources/sts/4.12/hypershift/sts_hcp_installer_permission_policy.json
  resources/sts/4.13/hypershift/sts_hcp_installer_permission_policy.json
Labels: approved, lgtm

#1581 OSD-15881: fix resources causing non-compliant logging policies
  deploy/acm-policies/50-GENERATED-osd-logging-unsupported.Policy.yaml
  deploy/osd-logging/01-operatorgroup.yaml
  deploy/osd-logging/unsupported/01-operatorgroup.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#1582 Stop patching 'default' namespace in ACM policy (for HCP)
  deploy/acm-policies/50-GENERATED-osd-project-request-template.Policy.yaml
  deploy/osd-project-request-template/nonhypershift/04-patch.label-default-namespace.yaml
  deploy/osd-project-request-template/nonhypershift/README.md
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1583 Expand SREP read rbac a bit for MC and SC
  deploy/backplane/srep/hypershift/management-cluster/10-srep-management-cluster-cluster.ClusteRole.yml
  deploy/backplane/srep/hypershift/service-cluster/10-srep-service-cluster-cluster.ClusteRole.yml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1527 Add missing node pool KMS permissions
  resources/sts/4.12/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
Labels: approved, lgtm

#1585 Restrict RunInstances to Red Hat AMIs
  resources/sts/4.12/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
Labels: approved, lgtm

#1563 Adding additional namespace access due to ACM SOPs for LPSRE
  deploy/backplane/lpsre/acm/01-acm-lpsre-admins.SubjectPermission.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1577 Remove ReleaseAddress from HCP NodePool policy as it's not used
  resources/sts/4.12/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
  resources/sts/4.13/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
Labels: approved, lgtm

#1586 Fix image restriction statement
  resources/sts/4.12/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
Labels: approved, lgtm

#1580 Bump KubeControllerManagerCrashloopingSRE to critical
  deploy/sre-prometheus/100-kube-controller-manager-crashlooping.yaml
  deploy/sre-prometheus/100-kube-controller-manager-missing-on-node.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1588 Adding a missing comma in the HCP installer policy
  resources/sts/4.12/hypershift/sts_hcp_installer_permission_policy.json
Labels: approved, lgtm

#1589 Remove tagging permissions from the HCP installer policy
  resources/sts/4.12/hypershift/sts_hcp_installer_permission_policy.json
Labels: approved, lgtm

#1594 Add wanghaoran1988 TL role
  OWNERS_ALIASES
Labels: approved, lgtm

#1593 Add RunInstances support for network verifier
  resources/sts/4.12/hypershift/sts_hcp_installer_permission_policy.json
Labels: approved, lgtm

#1599 Add Sids to all statements in HCP Control Plane policy
  resources/sts/4.12/hypershift/openshift_hcp_control_plane_operator_credentials_policy.json
Labels: approved, lgtm

#1591 Adding a config.yaml for every SSS
  README.md
  deploy/backplane/cee/config.yaml
  deploy/backplane/config.yaml
  deploy/backplane/csa/config.yaml
  deploy/backplane/cse/config.yaml
  deploy/backplane/csm/config.yaml
  deploy/backplane/elevated-sre/config.yaml
  deploy/backplane/lpsre/hypershift/config.yaml
  deploy/backplane/mobb/config.yaml
  deploy/backplane/srep/config.yaml
  deploy/backplane/tam/config.yaml
  deploy/customer-registry-cas/config.yaml
  deploy/managed-velero-operator-rolebinding/config.yaml
  deploy/osd-aquasec-operator/config.yaml
  deploy/osd-backplane-managed-scripts/config.yaml
  deploy/osd-cluster-ready/config.yaml
  deploy/osd-codeready-workspaces/config.yaml
  deploy/osd-custom-domains/config.yaml
  deploy/osd-customer-monitoring/config.yaml
  deploy/osd-delete-backplane-script-resources/config.yaml
  deploy/osd-delete-backplane-serviceaccounts/config.yaml
  deploy/osd-hsts-routes/config.yaml
  deploy/osd-ingress/controller/config.yaml
  deploy/osd-machine-api/config.yaml
  deploy/osd-managed-resources/config.yaml
  deploy/osd-must-gather-operator/config.yaml
  deploy/osd-namespace-labels/config.yaml
  deploy/osd-netnamespaces/config.yaml
  deploy/osd-openshift-operators-redhat/config.yaml
  deploy/osd-pcap-collector/config.yaml
  deploy/osd-project-request-template/config.yaml
  deploy/osd-project-request-template/nonhypershift/config.yaml
  deploy/osd-rebalance-infra-nodes/config.yaml
  deploy/osd-strimzi-operator/config.yaml
  deploy/osd-user-workload-monitoring/config.yaml
  deploy/rbac-permissions-operator-config/config.yaml
  deploy/resource-quotas/config.yaml
  deploy/sre-build-test/config.yaml
  deploy/sre-prometheus/centralized-observability/config.yaml
  deploy/sre-prometheus/config.yaml
  deploy/sre-pruning/config.yaml
  scripts/generate_template.py
Labels: approved, lgtm

#1596 Add OSD Fleet Manager backplane access namespace and permissions
  deploy/backplane/README.md
  deploy/backplane/osdfm/00-osdfm.namespace.yml
  deploy/backplane/osdfm/20-osdfm.SubjectPermission.yml
  deploy/backplane/osdfm/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: do-not-merge/hold, approved, lgtm

#1600 Revert "Merge pull request #1596 from tiwillia/osdfm_backplane_perms"
  deploy/backplane/README.md
  deploy/backplane/osdfm/00-osdfm.namespace.yml
  deploy/backplane/osdfm/20-osdfm.SubjectPermission.yml
  deploy/backplane/osdfm/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1601 OSD-15737 - Fix port for RMO api ClusterURLMonitor for HS
  deploy/acm-policies/50-GENERATED-hs-mgmt-route-monitor-operator.Policy.yaml
  deploy/hs-mgmt-route-monitor-operator/api.ClusterUrlMonitor.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1595 Add HyperShift monitoring label to openshift-monitoring namespace
  deploy/hypershift-namespace-labels/02-openshift-monitoring.patch.yaml
  deploy/hypershift-namespace-labels/README.md
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1603 Remove AssumeRoleWithWebIdentity from the HCP installer policy as it'…
  resources/sts/4.12/hypershift/sts_hcp_installer_permission_policy.json
Labels: approved, lgtm

#1604 Rename Sid for RunInstances restriction based on AWS feedback
  resources/sts/4.12/hypershift/sts_hcp_installer_permission_policy.json
Labels: approved, lgtm

#1606 Add alert CannotRetrieveUpdatesSRE
  deploy/sre-prometheus/100-sre-cannot-retrieve-updates.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1605 Update create tags node pool
  resources/sts/4.12/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
Labels: approved, lgtm

#1597 Add context keys to CP policy SG authorization
  resources/sts/4.12/hypershift/openshift_hcp_control_plane_operator_credentials_policy.json
Labels: approved, lgtm

#1612 Condition HCP KMS permissions by the red-hat-managed: true tag
  resources/sts/4.12/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
  resources/sts/4.12/hypershift/openshift_hcp_kms_provider_credential_policy.json
  resources/sts/4.12/hypershift/sts_hcp_support_permission_policy.json
Labels: approved, lgtm

#1610 Add request region name to image registry ARN
  resources/sts/4.12/hypershift/openshift_hcp_image_registry_operator_permission_policy.json
Labels: approved, lgtm

#1592 Ensure all AMIs originate from a known AWS account
  resources/sts/4.12/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
  resources/sts/4.12/hypershift/sts_hcp_support_permission_policy.json
Labels: approved, lgtm

#1617 added policy for ccs-dedicated-admins SubjectPermission
  deploy/acm-policies/50-GENERATED-ccs-dedicated-admins-sp.Policy.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/generate-subjectpermissions-policy-config.py
Labels: approved, lgtm

#1618 Add kms permission to installer for verifier, and correct tag in NodePool controller
  resources/sts/4.12/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
  resources/sts/4.12/hypershift/sts_hcp_installer_permission_policy.json
Labels: approved, lgtm

#1613 Added alert for OCMAgentResponseFailureServiceLogsSRE
  deploy/sre-prometheus/100-ocm-agent-operator.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1624 Add Sids to KubeControllerManager policies in HCP
  resources/sts/4.12/hypershift/openshift_hcp_kube_controller_manager_credentials_policy.json
Labels: approved, lgtm

#1629 Add Sids to KMS and image registry policies
  resources/sts/4.12/hypershift/openshift_hcp_image_registry_operator_permission_policy.json
  resources/sts/4.12/hypershift/openshift_hcp_kms_provider_credential_policy.json
  resources/sts/4.12/hypershift/openshift_hcp_kube_controller_manager_credentials_policy.json
Labels: approved, lgtm

#1627 Fix the hcp support to enable verifier runs
  resources/sts/4.12/hypershift/sts_hcp_support_permission_policy.json
  resources/sts/4.12/reference_policies/ROSASRESupportPolicy_unabridged.json
Labels: approved, lgtm

#1626 Update HCP Installer policy to handle verifier runs
  resources/sts/4.12/hypershift/sts_hcp_installer_permission_policy.json
  resources/sts/4.12/hypershift/sts_hcp_support_permission_policy.json
Labels: approved, lgtm

#1631 Combine statements where resource and condition are equal
  resources/sts/4.12/hypershift/sts_hcp_support_permission_policy.json
Labels: approved, lgtm

#1619 Remove unused permissions for KMS cluster API provider
  resources/sts/4.12/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
  resources/sts/4.12/hypershift/openshift_hcp_kms_provider_credential_policy.json
Labels: approved, lgtm

#1632 Add requirements for SRE jumpbox
  resources/sts/4.12/hypershift/sts_hcp_support_permission_policy.json
Labels: approved, lgtm

#1634 Add get instance profile to support policy
  resources/sts/4.12/hypershift/sts_hcp_support_permission_policy.json
Labels: approved, lgtm

#1635 Add Sids for HCP NodePool policy
  resources/sts/4.12/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
Labels: approved, lgtm

#1638 Fix Create/Delete keypair action
  resources/sts/4.12/hypershift/sts_hcp_support_permission_policy.json
Labels: approved, lgtm

#1637 Add unrequired CreateVolume action from conditions
  resources/sts/4.12/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
  resources/sts/4.12/hypershift/sts_hcp_installer_permission_policy.json
  resources/sts/4.12/hypershift/sts_hcp_support_permission_policy.json
Labels: approved, lgtm

#1636 Change nodepool management ec2 tag condition
  resources/sts/4.12/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
Labels: approved, lgtm

#1639 Update route-monitor-operator package and routeMonitor configurations
  deploy/acm-policies/50-GENERATED-hs-hosted-route-monitor-operator.Policy.yaml
  deploy/acm-policies/50-GENERATED-hs-mgmt-route-monitor-operator.Policy.yaml
  deploy/hs-hosted-route-monitor-operator/console.RouteMonitor.yaml
  deploy/hs-mgmt-route-monitor-operator/package.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1640 Revert "Use stock CMO on management clusters"
  deploy/cluster-monitoring-config/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1645 Update S3 buckets and KMS
  resources/sts/4.12/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
  resources/sts/4.12/hypershift/openshift_hcp_image_registry_operator_permission_policy.json
  resources/sts/4.12/hypershift/openshift_hcp_kms_provider_credential_policy.json
  resources/sts/4.12/hypershift/openshift_hcp_kube_controller_manager_credentials_policy.json
  resources/sts/4.12/hypershift/sts_hcp_installer_permission_policy.json
  resources/sts/4.12/hypershift/sts_hcp_support_permission_policy.json
Labels: approved, lgtm

#1646 Add KMS via service condition
  resources/sts/4.12/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
  resources/sts/4.12/hypershift/sts_hcp_installer_permission_policy.json
  resources/sts/4.12/hypershift/sts_hcp_support_permission_policy.json
Labels: approved, lgtm

#1647 Fix OCPBUGS link in the comments for runaway sdn alert
  deploy/sre-prometheus/100-runaway-sdn.PrometheusRule.yaml
Labels: approved, lgtm

#1648 Fix typos in statement IDs
  resources/sts/4.12/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
  resources/sts/4.12/hypershift/sts_hcp_installer_permission_policy.json
Labels: approved, lgtm

#1649 Use StringLike condition to match wildcard
  resources/sts/4.12/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
  resources/sts/4.12/hypershift/sts_hcp_installer_permission_policy.json
  resources/sts/4.12/hypershift/sts_hcp_support_permission_policy.json
Labels: approved, lgtm
