Repository openshift/managed-cluster-config, pull requests merged in 2023-10, with the labels that each got.

#1887 Update MC MHC to trigger on an undefined status condition
  deploy/osd-machine-api/management-clusters/011-machine-api.srep-worker-healthcheck.MachineHealthCheck.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1888 OSDOCS-6662 Adding KCS Article about PID Pressure to notification
  deploy/ocm-agent-operator-managednotifications/node-condition/200-sre-node-condition-managed-notification.ManagedNotification.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1889 Update MC MHC to select serving-* machines
  deploy/osd-machine-api/management-clusters/011-machine-api.srep-worker-healthcheck.MachineHealthCheck.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1866 Reverting the one-shot cronjob for OSD-18458 after it ran on affected clusters
  deploy/osd-18458-reinstall-rmo/README.md
  deploy/osd-18458-reinstall-rmo/config.yaml
  deploy/osd-18458-reinstall-rmo/osd18458.CronJob.yaml
  deploy/osd-18458-reinstall-rmo/pre-4.11/README.md
  deploy/osd-18458-reinstall-rmo/pre-4.11/config.yaml
  deploy/osd-18458-reinstall-rmo/pre-4.11/osd18458.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1890 adds subject permission for fedramp for services we manage in FR only
  deploy/backplane/srep/fedramp/30-srep-fedramp.SubjectPermission.yml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1891 Update MC MHC to select serving-* machines
  deploy/osd-machine-api/management-clusters/011-machine-api.srep-worker-healthcheck.MachineHealthCheck.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1894 Update hypershift suricata config
  deploy/osd-suricata/hypershift-management-cluster/15-configmap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1873 fixed policies for OSD-18642
  resources/sts/4.14/hypershift/sts_hcp_support_permission_policy.json
Labels: approved, lgtm

#1893 Policy for ovn label in HCP namespaces
  deploy/acm-policies/50-GENERATED-hypershift-ovn-logging.Policy.yaml
  deploy/hypershift-ovn-logging/config.yaml
  deploy/hypershift-ovn-logging/ovn-logging-label.Policy.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/generate-policy-config.py
Labels: approved, lgtm

#1897 Update suricata image
  deploy/osd-suricata/hypershift-management-cluster/20-osd-suricata-Daemonset.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1896 Add workaround for OCPBUGS-20184
  deploy/ocpbugs-20184/00-ocpbugs-20184.ServiceAccount.yaml
  deploy/ocpbugs-20184/01-ocpbugs-20184.Role.yaml
  deploy/ocpbugs-20184/02-ocpbugs-20184.RoleBinding.yaml
  deploy/ocpbugs-20184/10-ocpbugs-20184.CronJob.yaml
  deploy/ocpbugs-20184/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1898 Ignore KubeletDown during control plane phase of upgrades
  deploy/managed-upgrade-operator-config/10-managed-upgrade-operator-configmap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1900 [OSD-18400] Disable more eve types
  deploy/osd-suricata/hypershift-management-cluster/15-configmap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1901 Update to last image for suricata on hypershift.
  deploy/osd-suricata/hypershift-management-cluster/20-osd-suricata-Daemonset.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1899 Disable ovn label on HCP namespace
  deploy/acm-policies/50-GENERATED-hypershift-ovn-logging.Policy.yaml
  deploy/hypershift-ovn-logging/ovn-logging-label.Policy.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1824 Increase backoff for remote write
  deploy/cluster-monitoring-config-non-uwm/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config/50-GENERATED-cluster-monitoring-config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  resources/cluster-monitoring-config/config.yaml
Labels: approved, lgtm

#1903 [OSD-18400] Remove selector for hypershift suricata.
  deploy/osd-suricata/hypershift-management-cluster/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1904 Change policy to enable OVN audit log
  deploy/acm-policies/50-GENERATED-hypershift-ovn-logging.Policy.yaml
  deploy/hypershift-ovn-logging/ovn-logging-label.Policy.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1906 updates limited support to not target FR
  deploy/osd-limited-support/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1909 fix(MTSRE-1560): add 'rhacs' namespace for lpsre backplane access
  deploy/backplane/lpsre/acs/01-acs-lpsre-admins.SubjectPermission.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1911 Add `iam:GetPolicyVersion` to the OCM admin role
  resources/sts/4.11/sts_ocm_admin_permission_policy.json
  resources/sts/4.12/sts_ocm_admin_permission_policy.json
  resources/sts/4.13/sts_ocm_admin_permission_policy.json
  resources/sts/4.14/sts_ocm_admin_permission_policy.json
Labels: approved, lgtm

#1913 ignore KubeletDown during OCP upgrades
  deploy/managed-upgrade-operator-config/hypershift-mc/10-managed-upgrade-operator-configmap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1910 Allow ocpbugs-20184 cronjob to schedule anywhere
  deploy/ocpbugs-20184/10-ocpbugs-20184.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1914 osd-cluster-ready: v0.1.122-8ca3df8
  deploy/osd-cluster-ready/job/10-osd-ready.Job.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1905 Add channel patches for 4.15 through 4.19
  deploy/osd-channel-patch/README.md
  deploy/osd-channel-patch/candidate-4.15/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/candidate-4.15/config.yaml
  deploy/osd-channel-patch/candidate-4.16/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/candidate-4.16/config.yaml
  deploy/osd-channel-patch/candidate-4.17/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/candidate-4.17/config.yaml
  deploy/osd-channel-patch/candidate-4.18/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/candidate-4.18/config.yaml
  deploy/osd-channel-patch/candidate-4.19/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/candidate-4.19/config.yaml
  deploy/osd-channel-patch/fast-4.15/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/fast-4.15/config.yaml
  deploy/osd-channel-patch/fast-4.16/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/fast-4.16/config.yaml
  deploy/osd-channel-patch/fast-4.17/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/fast-4.17/config.yaml
  deploy/osd-channel-patch/fast-4.18/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/fast-4.18/config.yaml
  deploy/osd-channel-patch/fast-4.19/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/fast-4.19/config.yaml
  deploy/osd-channel-patch/stable-4.15/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/stable-4.15/config.yaml
  deploy/osd-channel-patch/stable-4.16/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/stable-4.16/config.yaml
  deploy/osd-channel-patch/stable-4.17/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/stable-4.17/config.yaml
  deploy/osd-channel-patch/stable-4.18/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/stable-4.18/config.yaml
  deploy/osd-channel-patch/stable-4.19/01-patch.clusterversion.yaml
  deploy/osd-channel-patch/stable-4.19/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#1916 Bump infra machinehealthcheck timeout to 10m
  deploy/osd-machine-api/010-machine-api.srep-infra-healthcheck.MachineHealthCheck.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1912 OSD-18286: Adding Prometheus Rule for Dynatrace Workload Monitoring at MC
  deploy/sre-prometheus/management-cluster/100-dynatrace-workloads-monitoring.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#1915 updates base images for Suricata and ClamAV in fedRAMP
  deploy/osd-scanning/20-osd-scanning-logger-Daemonset.yaml
  deploy/osd-scanning/30-osd-scanning-scanner-Daemonset.yaml
  deploy/osd-suricata/20-osd-suricata-Daemonset.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1917 fixes bad image digests for openshift-scanning
  deploy/osd-scanning/30-osd-scanning-scanner-Daemonset.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm
