Repository openshift/managed-cluster-config, pull requests merged in 2023-06, with the labels that each got.

#1696 Update token-refresher image to version without security vulns
  deploy/osd-token-refresher/01-token-refresher.Deployment.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1697 osd-cluster-ready++
  deploy/osd-cluster-ready/job/10-osd-ready.Job.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1679 chore(MTSRE-1246): add ODF SRE RBAC for backplane
  deploy/backplane/odf-sre/00-odf-sre.namespace.yml
  deploy/backplane/odf-sre/10-odf-sre-monitoring.ClusterRole.yml
  deploy/backplane/odf-sre/20-odf-sre.SubjectPermission.yml
  deploy/backplane/odf-sre/config.yaml
  deploy/backplane/odf-sre/ocs-consumer/01-odf-sre-ocs-consumer-project.ClusterRole.yml
  deploy/backplane/odf-sre/ocs-consumer/10-odf-sre.SubjectPermission.yml
  deploy/backplane/odf-sre/ocs-consumer/config.yaml
  deploy/backplane/odf-sre/ocs-provider/01-odf-sre-ocs-provider-project.ClusterRole.yml
  deploy/backplane/odf-sre/ocs-provider/10-odf-sre.SubjectPermission.yml
  deploy/backplane/odf-sre/ocs-provider/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1699 OSD-16737 make OCPBUGS-773 work on OVN clusters too
  deploy/ocpbugs-773/no-seccomp/10-OCPBUGS-773.CronJob.yaml
  deploy/ocpbugs-773/seccomp/10-OCPBUGS-773.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1691 [OSD-16075] Add new SL for audit-events failing delivery.
  deploy/ocm-agent-operator-managedfleetnotifications/OWNERS
  deploy/ocm-agent-operator-managedfleetnotifications/README.md
  deploy/ocm-agent-operator-managedfleetnotifications/audit-webhook-error-putting-minimized-cloudwatch-log.yaml
  deploy/ocm-agent-operator-managedfleetnotifications/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1700 Adds 4.13.z to the CPMS disabling cron job
  deploy/osd-14634-disable-cpms/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1702 Correct syntax error in ManagedFleetNotification
  deploy/ocm-agent-operator-managedfleetnotifications/audit-webhook-error-putting-minimized-cloudwatch-log.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1614 removing workaround PR #1517
  deploy/hypershift-validating-webhook-patching/10-validating-webhook-patching.Policy.yaml
  deploy/hypershift-validating-webhook-patching/OWNERS
  deploy/hypershift-validating-webhook-patching/README.md
  deploy/hypershift-validating-webhook-patching/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1704 Fix invalid format for LPSRE HyperShift SubjectPermission
  deploy/backplane/lpsre/hypershift/management-cluster/10-lpsre.SubjectPermission.yml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1705 * Remove ELB type, this will cause the system to default to Classic.
  deploy/acm-policies/50-GENERATED-rosa-ingress-certificate-policies.Policy.yaml
  deploy/rosa-ingress-certificate-policies/02-ingress-default.Policy.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1369 [OSD-14160] Add alert to detect stuck node.
  deploy/sre-prometheus/100-node-stuck-terminating-creating.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: lifecycle/rotten, approved, lgtm

#1692 Change installer role policy condition for the worker role
  resources/sts/4.12/hypershift/sts_hcp_installer_permission_policy.json
Labels: approved, lgtm

#1708 Align 4.12 and 4.13 HCP managed policy definitions
  resources/sts/4.13/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
  resources/sts/4.13/hypershift/openshift_hcp_control_plane_operator_credentials_policy.json
  resources/sts/4.13/hypershift/openshift_hcp_image_registry_operator_permission_policy.json
  resources/sts/4.13/hypershift/openshift_hcp_kms_provider_credential_policy.json
  resources/sts/4.13/hypershift/openshift_hcp_kube_controller_manager_credentials_policy.json
  resources/sts/4.13/hypershift/sts_hcp_installer_permission_policy.json
  resources/sts/4.13/hypershift/sts_hcp_support_permission_policy.json
Labels: approved, lgtm

#1709 CreateVPCEndpoint now specifies a security group
  resources/sts/4.12/hypershift/openshift_hcp_control_plane_operator_credentials_policy.json
  resources/sts/4.13/hypershift/openshift_hcp_control_plane_operator_credentials_policy.json
Labels: approved, lgtm

#1611 added destination: "generated_deploy/acm-policies" in policy field in config.yaml
  deploy/backplane/cee/config.yaml
  deploy/backplane/config.yaml
  deploy/backplane/cse/config.yaml
  deploy/backplane/csm/config.yaml
  deploy/backplane/cssre/config.yaml
  deploy/backplane/elevated-sre/config.yaml
  deploy/backplane/mobb/config.yaml
  deploy/backplane/srep/config.yaml
  deploy/backplane/tam/config.yaml
  deploy/ccs-dedicated-admins/config.yaml
  deploy/customer-registry-cas/config.yaml
  deploy/osd-backplane-managed-scripts/config.yaml
  deploy/osd-cluster-admin/config.yaml
  deploy/osd-customer-monitoring/config.yaml
  deploy/osd-delete-backplane-script-resources/config.yaml
  deploy/osd-delete-backplane-serviceaccounts/config.yaml
  deploy/osd-logging/unsupported/config.yaml
  deploy/osd-must-gather-operator/config.yaml
  deploy/osd-openshift-operators-redhat/config.yaml
  deploy/osd-pcap-collector/config.yaml
  deploy/osd-project-request-template/config.yaml
  deploy/osd-user-workload-monitoring/config.yaml
  deploy/rbac-permissions-operator-config/config.yaml
  deploy/rosa-console-branding-configmap/config.yaml
  deploy/rosa-console-branding/config.yaml
  deploy/rosa-ingress-certificate-policies/config.yaml
  deploy/rosa-oauth-templates/config.yaml
Labels: approved, lgtm

#1713 Create new statement to restrict ec2:CreateListener to require RequestTag
  resources/sts/4.12/hypershift/openshift_hcp_kube_controller_manager_credentials_policy.json
  resources/sts/4.13/hypershift/openshift_hcp_kube_controller_manager_credentials_policy.json
Labels: approved, lgtm

#1714 Updated README.md for https://issues.redhat.com/browse/SDE-2786 changes
  README.md
Labels: approved, lgtm

#1716 updating UBI versions for FR scanning
  deploy/osd-scanning/20-osd-scanning-logger-Daemonset.yaml
  deploy/osd-scanning/30-osd-scanning-scanner-Daemonset.yaml
  generated_deploy/osd-scanning/20-osd-scanning-logger-Daemonset.yaml
  generated_deploy/osd-scanning/30-osd-scanning-scanner-Daemonset.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1686 Remove alerting for non-default ingress controllers
  deploy/sre-prometheus/ocm-agent/100-ocm-agent.PrometheusRule.yaml
  deploy/sre-prometheus/ocm-agent/legacy-ingress/100-ocm-agent.PrometheusRule.yaml
  deploy/sre-prometheus/ocm-agent/legacy-ingress/config.yaml
  generated_deploy/sre-prometheus/ocm-agent/100-ocm-agent.PrometheusRule.yaml
  generated_deploy/sre-prometheus/ocm-agent/legacy-ingress/100-ocm-agent.PrometheusRule.yaml
  generated_deploy/sre-prometheus/ocm-agent/legacy-ingress/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1722 Update EBS IOPS PrometheusRule
  deploy/sre-prometheus/aws/ebs-iops-burstbalance/100-aws-ebs-iops-burstbal.promRule.yaml
  deploy/sre-prometheus/aws/ebs-iops-burstbalance/config.yaml
  generated_deploy/sre-prometheus/aws/ebs-iops-burstbalance/100-aws-ebs-iops-burstbal.promRule.yaml
  generated_deploy/sre-prometheus/aws/ebs-iops-burstbalance/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#1680 OSD-16095 - Moving the rosa-oauth-template elements to the hosted control plane
  deploy/rosa-oauth-templates-policies/50-rosa-oauth-tpl-errors.Policy.yaml
  deploy/rosa-oauth-templates-policies/50-rosa-oauth-tpl-login.Policy.yaml
  deploy/rosa-oauth-templates-policies/50-rosa-oauth-tpl-providers.Policy.yaml
  deploy/rosa-oauth-templates/config.yaml
  generated_deploy/acm-policies/50-GENERATED-rosa-oauth-templates.Policy.yaml
  generated_deploy/rosa-oauth-templates-policies/50-rosa-oauth-tpl-errors.Policy.yaml
  generated_deploy/rosa-oauth-templates-policies/50-rosa-oauth-tpl-login.Policy.yaml
  generated_deploy/rosa-oauth-templates-policies/50-rosa-oauth-tpl-providers.Policy.yaml
  generated_deploy/rosa-oauth-templates/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1710 Create RBAC For SD-CICD Role
  deploy/backplane/sdcicd/00-sdcicd.namespace.yml
  deploy/backplane/sdcicd/01-sdcicd-read-only-cluster.ClusterRole.yml
  deploy/backplane/sdcicd/40-sdcicd.SubjectPermission.yml
  deploy/backplane/sdcicd/config.yaml
  generated_deploy/backplane/sdcicd/00-sdcicd.namespace.yml
  generated_deploy/backplane/sdcicd/01-sdcicd-read-only-cluster.ClusterRole.yml
  generated_deploy/backplane/sdcicd/10-sdcicd-read-only-cluster.ClusterRole.yml
  generated_deploy/backplane/sdcicd/20-sdcicd.SubjectPermission.yml
  generated_deploy/backplane/sdcicd/40-sdcicd.SubjectPermission.yml
  generated_deploy/backplane/sdcicd/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1725 Restrict the SDCICD role to int and stage
  deploy/backplane/sdcicd/config.yaml
  generated_deploy/backplane/sdcicd/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm
