Repository openshift/managed-cluster-config, pull requests merged in 2023-03, with the labels that each got.

#1510 MTSRE-989: Seed RHOBS credentials in service clusters
  deploy/rhobs-hypershift-config/00-rhobs-credential-syncset.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#1511 Add network policy label to OBO namespace for HyperShift service clusters
  deploy/hypershift-namespace-labels/01-openshift-observability-operator.patch.yaml
  deploy/hypershift-namespace-labels/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1507 [MTSRE-965] feat: give LPSRE access to restart deployments/statefulsets/deploymentconfigs
  deploy/backplane/lpsre/rhoam/01-rhoam-lpsre-admins-project.ClusterRole.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1515 osd-cluster-ready++
  deploy/osd-cluster-ready/job/10-osd-ready.Job.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1479 Refine installer policy for hyperShift hosted clusters
  resources/sts/4.12/hypershift/InstallerPolicy.json
Labels: approved, lgtm, tide/merge-method-squash

#1508 [OSD-15092] Refine IAM policy files for HyperShift specific operators
  resources/sts/4.12/hypershift/ControlPlaneOperatorPolicy.json
  resources/sts/4.12/hypershift/KubeControllerPolicy.json
  resources/sts/4.12/hypershift/NodePoolManagementPolicy.json
Labels: approved, lgtm, tide/merge-method-squash

#1516 Add tag based conditions to CreateInstanceProfile action for HyperShift installer role
  resources/sts/4.12/hypershift/InstallerPolicy.json
Labels: approved, lgtm

#1517 OSD-15432 use correct secret for HS-MCVW patching
  deploy/hypershift-validating-webhook-patching/10-validating-webhook-patching.Policy.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1519 [osd-15092] Add missing permissions to control plane operator and node pool management operator
  resources/sts/4.12/hypershift/ControlPlaneOperatorPolicy.json
  resources/sts/4.12/hypershift/NodePoolManagementPolicy.json
Labels: approved, lgtm

#1513 Update HyperShfit TailoredProfile
  resources/tailored-profiles/hypershift-cis-tp.yaml
  resources/tailored-profiles/hypershift-pcidss-tp.yaml
Labels: approved, lgtm

#1523 Add condition keys to createSnapshot action hypershift csi operator
  resources/sts/4.12/hypershift/ROSAClusterCSIDriverEBSOperator.json
Labels: approved, lgtm

#1526 Add KMS Provider Credential Policy for hypershift
  resources/sts/4.12/hypershift/sts_hcp_kms_provider_credential_policy.json
Labels: approved, lgtm

#1525 Reformat the hypershift policy names to be compatible with Cluster Service
  resources/sts/4.12/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
  resources/sts/4.12/hypershift/openshift_hcp_cloud_network_config_cloud_credentials_permission_policy.json
  resources/sts/4.12/hypershift/openshift_hcp_cluster_csi_driver_ebs_operator_cloud_credentials_policy.json
  resources/sts/4.12/hypershift/openshift_hcp_cluster_ingress_operator_cloud_credentials_policy.json
  resources/sts/4.12/hypershift/openshift_hcp_control_plane_operator_credentials_policy.json
  resources/sts/4.12/hypershift/openshift_hcp_image_registry_operator_permission_policy.json
  resources/sts/4.12/hypershift/openshift_hcp_kms_provider_credential_policy.json
  resources/sts/4.12/hypershift/openshift_hcp_kube_controller_manager_credentials_policy.json
  resources/sts/4.12/hypershift/sts_hcp_installer_permission_policy.json
  resources/sts/4.12/hypershift/sts_hcp_support_permission_policy.json
  resources/sts/4.12/hypershift/sts_hcp_worker_instance_permission_policy.json
Labels: approved, lgtm

#1409 updates avo sts polcies to allow for creating addl hosted zones
  resources/sts/4.10/openshift_aws_vpce_operator_avo_aws_creds_policy.json
  resources/sts/4.11/openshift_aws_vpce_operator_avo_aws_creds_policy.json
  resources/sts/4.12/openshift_aws_vpce_operator_avo_aws_creds_policy.json
Labels: approved, lgtm, tide/merge-method-squash

#1529 OSD-15224: Add sts acks for 4.13
  deploy/osd-cluster-acks/sts/4.13/config.yaml
  deploy/osd-cluster-acks/sts/4.13/osd-sts-ack_CloudCredential.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#1530 OSD-15146 - updates avo vpce endpoints for v1alpha2
  deploy/osd-avo-resources/fedramp-vpc-endpoints/us-gov-east-1/00-osd-avo-VpcEndpoint.yaml
  deploy/osd-avo-resources/fedramp-vpc-endpoints/us-gov-west-1/00-osd-avo-VpcEndpoint.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1528 OSD-14462 deploy route-monitor-operator to hosted clusters and monitor the console
  deploy/acm-policies/50-GENERATED-hs-hosted-route-monitor-operator.Policy.yaml
  deploy/hs-hosted-route-monitor-operator/config.yaml
  deploy/hs-hosted-route-monitor-operator/console.RouteMonitor.yaml
  deploy/hs-hosted-route-monitor-operator/package.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/generate-policy-config.py
Labels: approved, lgtm

#1521 Integration timeout fix for Hypershift SC and MC
  deploy/osd-oauth-templates/ohss-2561/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1535 Disabe http2 on backplane clusters
  deploy/cluster-ingress-backplane/00-ingress.config.yaml
  deploy/cluster-ingress-backplane/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1532 Add sts policies for 4.13
  resources/sts/4.13/hypershift/README.md
  resources/sts/4.13/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
  resources/sts/4.13/hypershift/openshift_hcp_cloud_network_config_cloud_credentials_permission_policy.json
  resources/sts/4.13/hypershift/openshift_hcp_cluster_csi_driver_ebs_operator_cloud_credentials_policy.json
  resources/sts/4.13/hypershift/openshift_hcp_cluster_ingress_operator_cloud_credentials_policy.json
  resources/sts/4.13/hypershift/openshift_hcp_control_plane_operator_credentials_policy.json
  resources/sts/4.13/hypershift/openshift_hcp_image_registry_operator_permission_policy.json
  resources/sts/4.13/hypershift/openshift_hcp_kms_provider_credential_policy.json
  resources/sts/4.13/hypershift/openshift_hcp_kube_controller_manager_credentials_policy.json
  resources/sts/4.13/hypershift/sts_hcp_installer_permission_policy.json
  resources/sts/4.13/hypershift/sts_hcp_support_permission_policy.json
  resources/sts/4.13/hypershift/sts_hcp_worker_instance_permission_policy.json
  resources/sts/4.13/openshift_aws_vpce_operator_avo_aws_creds_policy.json
  resources/sts/4.13/openshift_capa_controller_manager_credentials_policy.json
  resources/sts/4.13/openshift_cloud_credential_operator_cloud_credential_operator_iam_ro_creds_policy.json
  resources/sts/4.13/openshift_cloud_ingress_operator_cloud_credentials_policy.json
  resources/sts/4.13/openshift_cloud_network_config_controller_cloud_credentials_policy.json
  resources/sts/4.13/openshift_cluster_csi_drivers_ebs_cloud_credentials_policy.json
  resources/sts/4.13/openshift_control_plane_operator_credentials_policy.json
  resources/sts/4.13/openshift_image_registry_installer_cloud_credentials_policy.json
  resources/sts/4.13/openshift_ingress_operator_cloud_credentials_policy.json
  resources/sts/4.13/openshift_kms_provider_credentials_policy.json
  resources/sts/4.13/openshift_kube_controller_manager_credentials_policy.json
  resources/sts/4.13/openshift_machine_api_aws_cloud_credentials_policy.json
  resources/sts/4.13/operator_iam_role_policy.json
  resources/sts/4.13/osd_scp_policy.json
  resources/sts/4.13/sts_installer_core_permission_policy.json
  resources/sts/4.13/sts_installer_permission_policy.json
  resources/sts/4.13/sts_installer_privatelink_permission_policy.json
  resources/sts/4.13/sts_installer_trust_policy.json
  resources/sts/4.13/sts_installer_vpc_permission_policy.json
  resources/sts/4.13/sts_instance_controlplane_permission_policy.json
  resources/sts/4.13/sts_instance_controlplane_trust_policy.json
  resources/sts/4.13/sts_instance_worker_permission_policy.json
  resources/sts/4.13/sts_instance_worker_trust_policy.json
  resources/sts/4.13/sts_ocm_admin_permission_policy.json
  resources/sts/4.13/sts_ocm_permission_policy.json
  resources/sts/4.13/sts_ocm_trust_policy.json
  resources/sts/4.13/sts_ocm_user_trust_policy.json
  resources/sts/4.13/sts_support_permission_policy.json
  resources/sts/4.13/sts_support_trust_policy.json
Labels: approved, lgtm

#1543 deploy route-monitor-operator to hypershift from app-sre repo
  deploy/acm-policies/50-GENERATED-hs-mgmt-route-monitor-operator.Policy.yaml
  deploy/hs-mgmt-route-monitor-operator/package.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#1545 Restrict KMS CreateGrant to EC2
  resources/sts/4.10/sts_support_permission_policy.json
  resources/sts/4.11/sts_support_permission_policy.json
  resources/sts/4.12/sts_support_permission_policy.json
Labels: approved, lgtm

#1546 Add KMS CreateGrant restriction, combine EC2 statement for policy length for HyperShift
  resources/sts/4.12/hypershift/sts_hcp_support_permission_policy.json
Labels: approved, lgtm

#1547 Target hcp namespaces by label instead of regex for route-monitor-operator policy
  deploy/acm-policies/50-GENERATED-hs-mgmt-route-monitor-operator.Policy.yaml
  deploy/hs-mgmt-route-monitor-operator/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1534 Add ability for SREP to add 'reason' metadata header to api requests
  deploy/acm-policies/50-GENERATED-backplane-elevated-sre.Policy.yaml
  deploy/backplane/elevated-sre/00-impersonate-cluster-admin.ClusterRole.yml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1544 SDE-2743 add policy to copy cert to hostedcluster
  deploy/acm-policies/50-GENERATED-rosa-ingress-certificate-policies.Policy.yaml
  deploy/rosa-ingress-certificate-policies/01-rosa-ingress-certificate.Policy.yaml
  deploy/rosa-ingress-certificate-policies/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/generate-policy-config.py
Labels: approved, lgtm

#1538 OSD-14612 - Strip down the SREP support role policy some more
  resources/sts/4.12/hypershift/sts_hcp_support_permission_policy.json
Labels: approved, lgtm, tide/merge-method-squash

#1549 Add openshift-customer-monitoring support to HCP
  deploy/acm-policies/50-GENERATED-osd-customer-monitoring.Policy.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/generate-policy-config.py
Labels: approved, lgtm

#1551 SDA-8595 fix ingress policy
  deploy/acm-policies/50-GENERATED-rosa-ingress-certificate-policies.Policy.yaml
  deploy/rosa-ingress-certificate-policies/01-rosa-ingress-certificate.Policy.yaml
  deploy/rosa-ingress-certificate-policies/02-ingress-default.Policy.yaml
  deploy/rosa-ingress-certificate-policies/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1557 Add action to send public key for serial console
  resources/sts/4.12/hypershift/sts_hcp_support_permission_policy.json
Labels: approved, lgtm

#1554 OSD-15442 Add KCMCrashLooping alert
  deploy/sre-prometheus/100-kube-controller-manager-crashlooping.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1559 Check for generated file changes in PR check
  deploy/acm-policies/50-GENERATED-hs-mgmt-route-monitor-operator.Policy.yaml
  hack/app_sre_pr_check.sh
Labels: approved, lgtm

#1556 Update HyperShift TailoredProfile for CO
  resources/tailored-profiles/hypershift-cis-tp.yaml
  resources/tailored-profiles/hypershift-pcidss-tp.yaml
Labels: approved, lgtm

#1560 Remove unused RMO policy
  deploy/acm-policies/50-GENERATED-hs-mgmt-route-monitor-api.Policy.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1565 Detect any non-generated ACM policies
  hack/app_sre_pr_check.sh
Labels: approved, lgtm

#1569 Remove redundant CreateInstanceProfile action and add missing describeSecurityGroups and describeLoadbalancers action to installer role
  resources/sts/4.12/hypershift/sts_hcp_installer_permission_policy.json
  resources/sts/4.13/hypershift/sts_hcp_installer_permission_policy.json
Labels: approved, lgtm

#1562 [MTSRE-1024]: cert-manager backplane permissions for LPSRE
  deploy/backplane/lpsre/cert-manager/01-cert-manager-lpsre-project.SubjectPermission.yaml
  deploy/backplane/lpsre/cert-manager/config.yaml
  deploy/backplane/lpsre/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  resources/addons-namespaces/main.yaml
Labels: approved, lgtm

#1568 Add openshift-logging namespace support to HCP
  deploy/acm-policies/50-GENERATED-osd-logging-unsupported.Policy.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/generate-policy-config.py
Labels: approved, lgtm

#1561 Adding missing dedicated-admins-project-request role and rolebinding
  deploy/acm-policies/50-GENERATED-osd-project-request-template.Policy.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/generate-policy-config.py
Labels: approved, lgtm

#1573 Remove duplicate elasticloadbalancing:AddTags permission for the KubeControllerManager HCP Policy
  resources/sts/4.12/hypershift/openshift_hcp_kube_controller_manager_credentials_policy.json
Labels: approved, lgtm
