Repository openshift/managed-cluster-config, pull requests merged in 2023-08, with the labels that each got.

#1776 OSD-17552 opentelemetry rbac shouldn't land on SCs
  deploy/backplane/srep/dynatrace/opentelemetry/10-srep-opentelemetry.Role.yml
  deploy/backplane/srep/dynatrace/opentelemetry/20-srep-opentelemetry.RoleBinding.yml
  deploy/backplane/srep/dynatrace/opentelemetry/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1778 Remove OSD-17664 and OSD-17672 jobs
  deploy/osd-17664-reinstall-mgo/README.md
  deploy/osd-17664-reinstall-mgo/config.yaml
  deploy/osd-17664-reinstall-mgo/osd17664.CronJob.yaml
  deploy/osd-17664-reinstall-mgo/pre-4.11/README.md
  deploy/osd-17664-reinstall-mgo/pre-4.11/config.yaml
  deploy/osd-17664-reinstall-mgo/pre-4.11/osd17664.CronJob.yaml
  deploy/osd-17672-fix-obo-sub/README.md
  deploy/osd-17672-fix-obo-sub/config.yaml
  deploy/osd-17672-fix-obo-sub/ohss23921.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1781 [OSD-16014] split the haproxyDown alert for default and non-default ingresscontroller
  deploy/sre-prometheus/100-sre-haproxydown.PrometheusRule.yaml
  deploy/sre-prometheus/legacy-ingress/100-sre-haproxydown.PrometheusRule.yaml
  deploy/sre-prometheus/legacy-ingress/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1782 Revert "OSD-16361: Deprecate custom-domains-operator if legacy-ingress-support label is available "
  deploy/osd-custom-domains/config.yaml
  deploy/osd-rebalance-infra-nodes/06-openshift-custom-domains-operator-pod-rebalance.RoleBinding.yaml
  deploy/osd-rebalance-infra-nodes/legacy-ingress/config.yaml
  deploy/osd-serviceaccounts/aws/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#1784 update infra resize alert
  deploy/sre-prometheus/100-infra-resizing.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#1786 updates images for clamd and suricata to patch CVEs
  deploy/osd-scanning/20-osd-scanning-logger-Daemonset.yaml
  deploy/osd-scanning/30-osd-scanning-scanner-Daemonset.yaml
  deploy/osd-suricata/20-osd-suricata-Daemonset.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1707 Define Hybrid SRE backplane role for HCP team
  deploy/backplane/hybridsre-hcp/hypershift/management-cluster/00-hybridsre-hcp.namespace.yml
  deploy/backplane/hybridsre-hcp/hypershift/management-cluster/20-hybridsre-hcp.SubjectPermission.yml
  deploy/backplane/hybridsre-hcp/hypershift/management-cluster/config.yaml
  docs/backplane/requirements/hybridsre-hcp/20-hypershift-management-cluster.md
  docs/backplane/requirements/hybridsre-hcp/OWNERS
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#1787 OSD-17024 - Legacy ingress labeller cron job
  deploy/osd-legacy-ingress-feature-labeller/00-osd-legacy-ingress-feature-labeller.ServiceAccount.yaml
  deploy/osd-legacy-ingress-feature-labeller/01-osd-legacy-ingress-feature-labeller.ClusterRole.yaml
  deploy/osd-legacy-ingress-feature-labeller/02-osd-legacy-ingress-feature-labeller.ClusterRoleBinding.yaml
  deploy/osd-legacy-ingress-feature-labeller/10-osd-legacy-ingress-feature-labeller.CronJob.yaml
  deploy/osd-legacy-ingress-feature-labeller/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1788 Only target staging hives for legacy ingress labeller
  deploy/osd-legacy-ingress-feature-labeller/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1789 Fix RBAC typo and add better logging for legacy ingress job
  deploy/osd-legacy-ingress-feature-labeller/01-osd-legacy-ingress-feature-labeller.ClusterRole.yaml
  deploy/osd-legacy-ingress-feature-labeller/10-osd-legacy-ingress-feature-labeller.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1791 Skip non-AWS clusters for legacy ingress labeller
  deploy/osd-legacy-ingress-feature-labeller/10-osd-legacy-ingress-feature-labeller.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1793 Add CronJob to OLM Dance custom-domains-operator
  deploy/osd-17042-cdo-olm-dance/README.md
  deploy/osd-17042-cdo-olm-dance/config.yaml
  deploy/osd-17042-cdo-olm-dance/cronjob.yaml
  deploy/osd-17042-cdo-olm-dance/pre-4.11/config.yaml
  deploy/osd-17042-cdo-olm-dance/pre-4.11/cronjob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1794 Add CronJob to OLM Dance custom-domains-operator
  deploy/osd-17042-cdo-olm-dance/01-serviceaccount.yaml
  deploy/osd-17042-cdo-olm-dance/02-role.yaml
  deploy/osd-17042-cdo-olm-dance/03-rolebinding.yaml
  deploy/osd-17042-cdo-olm-dance/04-cronjob.yaml
  deploy/osd-17042-cdo-olm-dance/cronjob.yaml
  deploy/osd-17042-cdo-olm-dance/pre-4.11/01-serviceaccount.yaml
  deploy/osd-17042-cdo-olm-dance/pre-4.11/02-role.yaml
  deploy/osd-17042-cdo-olm-dance/pre-4.11/03-rolebinding.yaml
  deploy/osd-17042-cdo-olm-dance/pre-4.11/04-cronjob.yaml
  deploy/osd-17042-cdo-olm-dance/pre-4.11/cronjob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1792 Migrate InfraNodesNeedResizingSRE to roll-up alert for infra node resize warning alerts.
  deploy/sre-prometheus/100-control-plane-resizing.PrometheusRule.yaml
  deploy/sre-prometheus/100-infra-resizing.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1780 add management-cluster-v2 label selector
  deploy/acm-policies/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1795 Adjust CDO CronJob OLM Dance to remove subscription
  deploy/osd-17042-cdo-olm-dance/02-role.yaml
  deploy/osd-17042-cdo-olm-dance/04-cronjob.yaml
  deploy/osd-17042-cdo-olm-dance/pre-4.11/02-role.yaml
  deploy/osd-17042-cdo-olm-dance/pre-4.11/04-cronjob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1796 remove misleading runbook_url for ES alerts
  deploy/sre-prometheus/extended-logging/101-parsed_elasticsearch_openshift-logging_elasticsearch-prometheus-rules.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1798 fix logic in defining the threshold for infra resize based on memory
  deploy/sre-prometheus/100-infra-resizing.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1799 revert a1ffe8f
  deploy/sre-prometheus/100-control-plane-resizing.PrometheusRule.yaml
  deploy/sre-prometheus/100-infra-resizing.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1801 Re-enable resource-based InfraNodesNeedResizingSRE alert
  deploy/sre-prometheus/100-control-plane-resizing.PrometheusRule.yaml
  deploy/sre-prometheus/100-infra-resizing.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#1803 move route-monitor-operator resources to the package
  deploy/acm-policies/50-GENERATED-hs-hosted-route-monitor-operator.Policy.yaml
  deploy/hs-hosted-route-monitor-operator/api.ClusterURLMonitor.yaml
  deploy/hs-hosted-route-monitor-operator/config.yaml
  deploy/hs-hosted-route-monitor-operator/console.RouteMonitor.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/generate-policy-config.py
Labels: approved, lgtm

#1804 fix bash `if` syntax typo
  deploy/osd-17042-cdo-olm-dance/04-cronjob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1805 Remove CDO OLM Dance CronJob
  deploy/osd-17042-cdo-olm-dance/01-serviceaccount.yaml
  deploy/osd-17042-cdo-olm-dance/02-role.yaml
  deploy/osd-17042-cdo-olm-dance/03-rolebinding.yaml
  deploy/osd-17042-cdo-olm-dance/04-cronjob.yaml
  deploy/osd-17042-cdo-olm-dance/README.md
  deploy/osd-17042-cdo-olm-dance/config.yaml
  deploy/osd-17042-cdo-olm-dance/pre-4.11/01-serviceaccount.yaml
  deploy/osd-17042-cdo-olm-dance/pre-4.11/02-role.yaml
  deploy/osd-17042-cdo-olm-dance/pre-4.11/03-rolebinding.yaml
  deploy/osd-17042-cdo-olm-dance/pre-4.11/04-cronjob.yaml
  deploy/osd-17042-cdo-olm-dance/pre-4.11/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1806 Add ListHostedZonesByName and GetHostedZone to HCP managed installer policy
  resources/sts/4.13/hypershift/sts_hcp_installer_permission_policy.json
Labels: approved, lgtm

#1807 Re-adds olm dance for cdo pre-4.11
  deploy/osd-17042-cdo-olm-dance/pre-4.11/01-serviceaccount.yaml
  deploy/osd-17042-cdo-olm-dance/pre-4.11/02-role.yaml
  deploy/osd-17042-cdo-olm-dance/pre-4.11/03-rolebinding.yaml
  deploy/osd-17042-cdo-olm-dance/pre-4.11/04-cronjob.yaml
  deploy/osd-17042-cdo-olm-dance/pre-4.11/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1808 itn-2023-00101 - Remove CDO's pre-v205 olm objects
  deploy/osd-17042-cdo-olm-dance/pre-4.11/04-cronjob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1810 Ensure annotations exist before patching
  deploy/osd-17042-cdo-olm-dance/pre-4.11/04-cronjob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#1812 Remove 'jq' dependency from job run
  deploy/osd-17042-cdo-olm-dance/pre-4.11/04-cronjob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1809 [OSD-17905] MachineOutOfCompliance alert
  deploy/sre-prometheus/management-cluster/100-machine-out-of-compliance.PrometheusRule.yaml
  deploy/sre-prometheus/management-cluster/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#1814 Remove disable-CPMS CronJob from Management Clusters
  deploy/osd-14634-disable-cpms/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1813 Update Managed Ingress feature labeller to reflect new business requirements
  deploy/osd-legacy-ingress-feature-labeller/10-osd-legacy-ingress-feature-labeller.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1790 Deploy legacy ingress labeller to all production hives
  deploy/osd-legacy-ingress-feature-labeller/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1815 Update CPMS state to Active in mgmt cluster
  deploy/OSD-17901-enable-cpms/config.yaml
  deploy/OSD-17901-enable-cpms/cpms-cluster.state.patch.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#1816 Ensuring that make fails when sss name is uppercase
  deploy/osd-17901-enable-cpms/config.yaml
  deploy/osd-17901-enable-cpms/cpms-cluster.state.patch.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/generate_template.py
Labels: approved, lgtm, tide/merge-method-squash

#1817 cpms .spec.state must be a string
  deploy/osd-17901-enable-cpms/cpms-cluster.state.patch.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1818 OSD-17694 Removes sre-build-test jobs and related resources
  deploy/sre-build-test/00-build-test.Namespace.yaml
  deploy/sre-build-test/10-build-test.ServiceAccount.yaml
  deploy/sre-build-test/20-build-test-ClusterRole.yaml
  deploy/sre-build-test/25-build-test-ClusterRoleBinding.yaml
  deploy/sre-build-test/30-build-test-SubjectPermission.yaml
  deploy/sre-build-test/40-build-test-RoleBinding.yaml
  deploy/sre-build-test/45-build-test-Role.yaml
  deploy/sre-build-test/50-source-build-test.CronJob.yaml
  deploy/sre-build-test/70-stuck-builds.PrometheusRule.yaml
  deploy/sre-build-test/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm
