Repository openshift/managed-cluster-config, pull requests merged in 2023-11, with the labels that each got.

#1918 Add prometheus rule to hive prod to create alert for CGAO
  deploy/sre-prometheus/fedramp/hive-prod/100-cgao-inactive-heartbeatmonitor.yaml
  deploy/sre-prometheus/fedramp/hive-prod/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1920 Ensure CPMS is disabled on 4.14
  deploy/osd-14634-disable-cpms/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1922 OSD-19348: Update Dynatrace Workload Monitoring Alerts
  deploy/sre-prometheus/management-cluster/100-dynatrace-workloads-monitoring.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#1923 No more customer kube-node-unscheduleables
  deploy/ocm-agent-operator-managednotifications/10-managednotifications-cr.yaml
  deploy/sre-prometheus/100-node-unschedulable.PrometheusRule.yaml
  deploy/sre-prometheus/ocm-agent/100-ocm-agent.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#1921 Disable second ingress service log on v4.13+
  deploy/sre-prometheus/ocm-agent/legacy-ingress/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1924 updates muo config for FR to add stage
  deploy/osd-fedramp-managed-upgrade-operator-config/int/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1925 [OSD-18386] Only fire UpgradeConfigValidationFailedSRE after two hours of validation failure
  deploy/sre-prometheus/100-managed-upgrade-operator.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1919 Update worker machinehealthcheck timeout to 10m
  deploy/osd-machine-api/011-machine-api.srep-worker-healthcheck.MachineHealthCheck.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1927 OSD-19663: drop CSRPendingLongDurationSRE from critical to warning
  deploy/sre-prometheus/100-pending-csr.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#1931 update to account for AWS ap regions
  resources/sts/4.14/hypershift/openshift_hcp_image_registry_operator_permission_policy.json
Labels: approved, lgtm

#1929 Remove invalid permission s3:GetBucketReplication
  resources/sts/4.14/sts_installer_core_permission_policy.json
  resources/sts/4.14/sts_installer_permission_policy.json
Labels: approved, lgtm

#1935 Add additional approvers
  OWNERS
Labels: approved, lgtm

#1932 whitelisting addon_operator_reconcile_error
  deploy/cluster-monitoring-config-non-uwm/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config/50-GENERATED-cluster-monitoring-config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  resources/cluster-monitoring-config/config.yaml
Labels: approved, lgtm

#1937 adding condition as requsted by AWS
  resources/sts/4.14/hypershift/openshift_hcp_image_registry_operator_permission_policy.json
Labels: approved, lgtm

#1938 Add supreeth7 as an approver
  OWNERS
Labels: approved, lgtm

#1933 Add KubeletDebuggingHandlersEnabledSRE alert
  deploy/sre-prometheus/management-cluster/100-kubeletconfig-debugging-handlers-enabled.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1939 [OSD-18804] update the node condtion prometheusrules location
  deploy/ocm-agent-operator-managednotifications/node-condition/100-sre-node-condition-managed-notification.ManagedNotification.yaml
  deploy/sre-prometheus/ocm-agent/node-condition/100-ocm-agent-node-condition.PrometheusRule.yaml
  deploy/sre-prometheus/ocm-agent/node-condition/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1942 OSD 19654
  deploy/aws-ssm-agent/01-machineconfig.yaml
  deploy/aws-ssm-agent/README.md
  deploy/aws-ssm-agent/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1945 Make podman compatible with MacOS
  Makefile
Labels: approved, lgtm

#1946 formatting conditions less permissive as requested
  resources/sts/4.14/hypershift/openshift_hcp_image_registry_operator_permission_policy.json
Labels: approved, lgtm

#1947 Only deploy MC alerts to STS MCs
  deploy/sre-prometheus/management-cluster/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1949 Do not reschedule infra pods if there are already the number of infra node pods running on infra nodes
  deploy/osd-rebalance-infra-nodes/07-osd-rebalance-infra-nodes.ConfigMap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#1952 Modify promrule so it doesn't deploy to int/stg hive
  deploy/sre-prometheus/fedramp/hive-prod/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm
