Repository openshift/managed-cluster-config, pull requests merged in 2024-01, with the labels that each got.

#1972 [OSD-20187] Split inodes < 3% alert for workers and controlplanes.
  deploy/ocm-agent-operator-managednotifications/10-managednotifications-cr.yaml
  deploy/sre-prometheus/100-node-filedescriptor-limits.PrometheusRule.yaml
  deploy/sre-prometheus/ocm-agent/100-ocm-agent.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1974 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, lgtm

#1975 Fedramp image verification int master
  deploy/osd-fedramp-machineconfig/int/pre-4.13/51-master-rh-registry-trust.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1976 update scanning and suricata images for CVE patching
  deploy/osd-scanning/20-osd-scanning-logger-Daemonset.yaml
  deploy/osd-scanning/30-osd-scanning-scanner-Daemonset.yaml
  deploy/osd-suricata/20-osd-suricata-Daemonset.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1977 Add openshift-compliance-monkey to managed namespaces
  deploy/osd-managed-resources/managed-namespaces.ConfigMap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  resources/managed/all-osd-resources.yaml
Labels: approved, lgtm

#1978 OSD-18887: updates MUO config for FR for all environments
  deploy/osd-fedramp-managed-upgrade-operator-config/10-managed-upgrade-operator-configmap.yaml
  deploy/osd-fedramp-managed-upgrade-operator-config/config.yaml
  deploy/osd-fedramp-managed-upgrade-operator-config/int/10-managed-upgrade-operator-configmap.yaml
  deploy/osd-fedramp-managed-upgrade-operator-config/int/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#1979 OSD-19703 - Add inital alerts for OADP on MCs
  deploy/sre-prometheus/management-cluster/100-oadp-monitoring.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#1981 add alert for ocm-agent pull secret invalid
  deploy/sre-prometheus/100-ocm-agent-operator.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1969 Fedramp image verification stg
  deploy/osd-fedramp-machineconfig/stg/pre-4.13/51-master-rh-registry-trust.yaml
  deploy/osd-fedramp-machineconfig/stg/pre-4.13/51-worker-rh-registry-trust.yaml
  deploy/osd-fedramp-machineconfig/stg/pre-4.13/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1982 Fedramp image verification prod
  deploy/osd-fedramp-machineconfig/prod/pre-4.13/51-master-rh-registry-trust.yaml
  deploy/osd-fedramp-machineconfig/prod/pre-4.13/51-worker-rh-registry-trust.yaml
  deploy/osd-fedramp-machineconfig/prod/pre-4.13/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1985 Grant SRE read permissions on the autoscaling.openshift.io API group
  deploy/acm-policies/50-GENERATED-backplane-srep.Policy.yaml
  deploy/backplane/srep/10-srep-admins-cluster.ClusterRole.yml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1986 Migrate OADP prometheusrules to openshift-monitoring
  deploy/sre-prometheus/management-cluster/100-oadp-monitoring.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#1988 [OSD-19769] Lower ClusterMonitoringErrorBudgetBurnSRE SLO
  deploy/sre-prometheus/monitoring/100-cluster-monitoring-error-budget-burn.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1991 Bump cgao promrule
  deploy/sre-prometheus/fedramp/hive-prod/100-cgao-inactive-heartbeatmonitor.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1990 OCM-2303 | [HCP] Disable ingress certificate in ACM policy if configmap parameter is true
  deploy/acm-policies/50-GENERATED-rosa-ingress-certificate-policies.Policy.yaml
  deploy/rosa-ingress-certificate-policies/00-ingress-default.Policy.yaml
  deploy/rosa-ingress-certificate-policies/01-rosa-ingress-certificate.Policy.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1948 Use internal OCM endpoint proxy for MUO on non-management clusters
  deploy/managed-upgrade-operator-config/10-managed-upgrade-operator-configmap.yaml
  deploy/managed-upgrade-operator-config/hypershift-mc/10-managed-upgrade-operator-configmap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1993 Revert "Use internal OCM endpoint proxy for MUO on non-management clusters"
  deploy/managed-upgrade-operator-config/10-managed-upgrade-operator-configmap.yaml
  deploy/managed-upgrade-operator-config/hypershift-mc/10-managed-upgrade-operator-configmap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1992 OSD-18436 : Workaround for bug 16655: CreateContainerError due to seccomp error
  deploy/ocpbugs-15043/00-ocpbugs-15043.ServiceAccount.yaml
  deploy/ocpbugs-15043/01-ocpbugs-15043.Role.yaml
  deploy/ocpbugs-15043/02-ocpbugs-15043.RoleBinding.yaml
  deploy/ocpbugs-15043/03-ocpbugs-15043.configmap.yaml
  deploy/ocpbugs-15043/10-ocpbugs-15043.CronJob.yaml
  deploy/ocpbugs-15043/config.yaml
  deploy/ocpbugs-15043/script.sh
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1995 Fix bug with kms:DescribeKey and break out describe actions
  resources/sts/4.14/sts_instance_controlplane_permission_policy.json
  resources/sts/4.15/sts_instance_controlplane_permission_policy.json
Labels: approved, lgtm

#1998 OSD-20527: Adding appropriate attributes to notifications in terms of LogType, severity and references
  deploy/ocm-agent-operator-managednotifications/10-managednotifications-cr.yaml
  deploy/ocm-agent-operator-managednotifications/10-managednotifications-proxy-cr.yaml
  deploy/ocm-agent-operator-managednotifications/10-managednotifications-upgrade-cr.yaml
  deploy/ocm-agent-operator-managednotifications/OWNERS
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#1940 OSD-18515: Handling the KubePersistentVolumeFillingUp alerts on 'openshift-user-workload-monitoring' namespace with the ocm-agent operator
  deploy/ocm-agent-operator-managednotifications/10-managednotifications-cr.yaml
  deploy/sre-prometheus/ocm-agent/100-ocm-agent.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2002 Add ALLOW_CORDON_WORKER_NODE_ENTITY_IDS as a feature flag for MCVW
  deploy/customer-cordon-node-configmap/config.yaml
  deploy/customer-cordon-node-configmap/configmap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/templates/template.yaml
Labels: approved, lgtm

#2001 [OSD-20478] Add recording rule to track sre operators state
  deploy/cluster-monitoring-config-non-uwm/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config-non-uwm/clusters-v4.5/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config-non-uwm/management-clusters/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config/management-clusters/50-GENERATED-cluster-monitoring-config.yaml
  deploy/sre-prometheus/centralized-observability/100-sre-operators-recording-rules.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  resources/cluster-monitoring-config/config.yaml
Labels: approved, lgtm

#2003 Fix references to be an array
  deploy/ocm-agent-operator-managednotifications/10-managednotifications-cr.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2004 OSD-19863 add oidc deleted managedfleetnotification
  deploy/ocm-agent-operator-managedfleetnotifications/README.md
  deploy/ocm-agent-operator-managedfleetnotifications/oidc-deleted-limited-support.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2006 [OSD-19769] Re-enable ClusterMonitoringErrorBudgetBurnSRE alert
  deploy/sre-prometheus/monitoring/100-cluster-monitoring-error-budget-burn.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2000 change cmo to remoteWrite directly, using oauth2
  deploy/cluster-monitoring-config-non-uwm/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config-non-uwm/clusters-v4.5/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config-non-uwm/management-clusters/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config/management-clusters/50-GENERATED-cluster-monitoring-config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  resources/cluster-monitoring-config/config.yaml
  scripts/templates/template.yaml
Labels: approved, lgtm

#1963 Update LPRSE permissions for ACS
  deploy/backplane/lpsre/acs/01-acs-lpsre-admins.SubjectPermission.yaml
  deploy/backplane/lpsre/acs/02-acs-lpsre-admins-project.ClusterRole.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm
