Repository openshift/managed-cluster-config, pull requests merged in 2024-08, with the labels that each got.

#2182 Revert disable the UpgradeConfigSyncFailureOver4HrSRE patch
  deploy/sre-prometheus/100-managed-upgrade-operator.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2181 Update ClusterOperatorDegradedSRE Alert
  deploy/sre-prometheus/100-cluster-version-operator.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#2184 OSD-19661 Fix newline with yaml
  deploy/sre-prometheus/100-cluster-version-operator.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2185 OSD-19661 Fix prometheus rule for UpgradeConfigSyncFailureOver4HrSRE
  deploy/sre-prometheus/100-managed-upgrade-operator.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2183 Enable pre-health check feature in managed-upgrade-operator
  deploy/managed-upgrade-operator-config/10-managed-upgrade-operator-configmap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2186 removing openshift-cluster-api-gcp from WIF templates
  resources/wif/4.14/vanilla.yaml
  resources/wif/4.15/vanilla.yaml
  resources/wif/4.16/vanilla.yaml
Labels: approved, lgtm

#2187 wif: adding permission to deployer
  resources/wif/4.14/vanilla.yaml
  resources/wif/4.15/vanilla.yaml
  resources/wif/4.16/vanilla.yaml
Labels: approved, lgtm

#2188 OSD-20975: Not deploying MVO on GCP WIF clusters
  deploy/velero-configuration/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2084 softens the language about node troubleshooting
  deploy/ocm-agent-operator-managednotifications/10-managednotifications-cr.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: lifecycle/rotten, approved, lgtm

#2190 [OSD-24939] This commit adds back the STS roles needed by AVO in the …
  resources/sts/4.13/openshift_aws_vpce_operator_avo_aws_creds_policy.json
  resources/sts/4.14/openshift_aws_vpce_operator_avo_aws_creds_policy.json
Labels: approved, lgtm

#2165 Adding machineautoscalers RBAC and requirements CEE RBAC + Requirements
  deploy/acm-policies/50-GENERATED-backplane-cee.Policy.yaml
  deploy/backplane/cee/01-cee-cluster-readers-cluster.ClusterRole.yml
  docs/backplane/requirements/cee/20-machineautoscaler.md
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2194 [OSD-24939] After discussing these changes further within the FedRamp…
  resources/sts/4.15/openshift_aws_vpce_operator_avo_aws_creds_policy.json
  resources/sts/4.16/openshift_aws_vpce_operator_avo_aws_creds_policy.json
Labels: approved, lgtm

#2191 OSD-23975 Add new record rule for MUO prehealth check result
  deploy/cluster-monitoring-config-non-uwm/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config-non-uwm/clusters-v4.5/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config-non-uwm/management-clusters/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config/management-clusters/50-GENERATED-cluster-monitoring-config.yaml
  deploy/sre-prometheus/centralized-observability/100-sre-internal-recording-rules.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  resources/cluster-monitoring-config/config.yaml
Labels: approved, lgtm

#2196 Updating the RLs and FLs list for MCC
  OWNERS_ALIASES
Labels: approved, lgtm

#2195 OSD-24693 enable notifciation feature in Managed upgrade operator
  deploy/managed-upgrade-operator-config/10-managed-upgrade-operator-configmap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2192 OHSS-36254: ACS Add packagemanifests cluster permission
  deploy/acm-policies/50-GENERATED-backplane-acs.Policy.yaml
  deploy/backplane/acs/01-acs-admins-cluster.ClusterRole.yaml
  docs/backplane/requirements/acs/10-acs-managed-service.md
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#2193 [OSD-24944] Mgo ns in hcp
  deploy/acm-policies/50-GENERATED-osd-must-gather-operator.Policy.yaml
  deploy/osd-must-gather-operator/01-openshift-must-gather-operator.Namespace.yaml
  deploy/osd-must-gather-operator/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/generate-policy-config.py
Labels: approved, lgtm

#2199 Allow SREP to get/list/watch scheduling.hypershift.openshift.io resources
  deploy/backplane/srep/hypershift/management-cluster/10-srep-management-cluster-cluster.ClusteRole.yml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2202 update 4.17 WIF template
  resources/wif/4.17/vanilla.yaml
Labels: approved, lgtm

#2203 wif template: reducing permissions of 4.17 osd-deployer
  resources/wif/4.17/vanilla.yaml
Labels: approved, lgtm
