Repository openshift/managed-cluster-config, pull requests merged in 2024-04, with the labels that each got.

#2068 MTSRE-1684 fixing namespace for service account mapping.
  deploy/backplane/acs/01-acs-admins.SubjectPermission.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2069 SDCICD-1254: remove osd-cluster-metadata
  deploy/osd-cluster-metadata/10-osd-cluster-metadata.openshift-config.ConfigMap.yaml
  deploy/osd-cluster-metadata/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2070 Remove r7i.metal-48xl from the metal machine healthcheck based on QE …
  deploy/osd-machine-api/011-machine-api.srep-worker-healthcheck.MachineHealthCheck.yaml
  deploy/osd-machine-api/012-machine-api.srep-metal-worker-healthcheck.MachineHealthCheck.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2067 begin scan migration, rm from FR stg/int
  deploy/osd-scanning/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2071 Update the OBO prometheus rules
  deploy/sre-prometheus/ocm-agent/obo-monitoring/100-audit-webhook-cloud-watch-errors.PrometheusRule.yaml
  deploy/sre-prometheus/ocm-agent/obo-monitoring/100-oidc-missing.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2066 Separates UWM and Cluster Monitoring ErrorBudgetBurn Alerts
  deploy/ocm-agent-operator-managednotifications/10-managednotifications-cr.yaml
  deploy/sre-prometheus/monitoring/100-cluster-monitoring-error-budget-burn.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2053 OCMAgentServiceLogsSentExceedingLimit Feature
  deploy/sre-prometheus/100-ocm-agent-operator.PrometheusRule.yaml
  deploy/sre-prometheus/ocm-agent/100-ocm-agent.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2072 ITN-56: Fix OSD-21066 cronjob
  deploy/osd-21066-camo-olm-dance/00-roles.yaml
  deploy/osd-21066-camo-olm-dance/01-cronjob.yaml
  deploy/osd-21066-camo-olm-dance/README.md
  deploy/osd-21066-camo-olm-dance/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2073 added /health so console would curl lightweight health endpoint
  deploy/ocm-agent-operator-managednotifications/10-managednotifications-cr.yaml
  deploy/osd-route-monitor-operator/100-openshift-route-monitor-operator.console.RouteMonitor.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2074 Revert "ITN-56: Fix OSD-21066 cronjob"
  deploy/osd-21066-camo-olm-dance/00-roles.yaml
  deploy/osd-21066-camo-olm-dance/01-cronjob.yaml
  deploy/osd-21066-camo-olm-dance/README.md
  deploy/osd-21066-camo-olm-dance/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2076 OSD-21045 : Adding in 4.16 STS policies
  resources/sts/4.16/hypershift/README.md
  resources/sts/4.16/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
  resources/sts/4.16/hypershift/openshift_hcp_cloud_network_config_cloud_credentials_permission_policy.json
  resources/sts/4.16/hypershift/openshift_hcp_cluster_csi_driver_ebs_operator_cloud_credentials_policy.json
  resources/sts/4.16/hypershift/openshift_hcp_cluster_ingress_operator_cloud_credentials_policy.json
  resources/sts/4.16/hypershift/openshift_hcp_control_plane_operator_credentials_policy.json
  resources/sts/4.16/hypershift/openshift_hcp_image_registry_operator_permission_policy.json
  resources/sts/4.16/hypershift/openshift_hcp_kms_provider_credential_policy.json
  resources/sts/4.16/hypershift/openshift_hcp_kube_controller_manager_credentials_policy.json
  resources/sts/4.16/hypershift/sts_extended_hcp_support_permission_policy.json
  resources/sts/4.16/hypershift/sts_hcp_installer_permission_policy.json
  resources/sts/4.16/hypershift/sts_hcp_support_permission_policy.json
  resources/sts/4.16/hypershift/sts_hcp_worker_instance_permission_policy.json
  resources/sts/4.16/openshift_aws_vpce_operator_avo_aws_creds_policy.json
  resources/sts/4.16/openshift_capa_controller_manager_credentials_policy.json
  resources/sts/4.16/openshift_cloud_credential_operator_cloud_credential_operator_iam_ro_creds_policy.json
  resources/sts/4.16/openshift_cloud_ingress_operator_cloud_credentials_policy.json
  resources/sts/4.16/openshift_cloud_network_config_controller_cloud_credentials_policy.json
  resources/sts/4.16/openshift_cluster_csi_drivers_ebs_cloud_credentials_policy.json
  resources/sts/4.16/openshift_control_plane_operator_credentials_policy.json
  resources/sts/4.16/openshift_image_registry_installer_cloud_credentials_policy.json
  resources/sts/4.16/openshift_ingress_operator_cloud_credentials_policy.json
  resources/sts/4.16/openshift_kms_provider_credentials_policy.json
  resources/sts/4.16/openshift_kube_controller_manager_credentials_policy.json
  resources/sts/4.16/openshift_machine_api_aws_cloud_credentials_policy.json
  resources/sts/4.16/operator_iam_role_policy.json
  resources/sts/4.16/osd_scp_policy.json
  resources/sts/4.16/shared_vpc_openshift_ingress_operator_cloud_credentials_policy.json
  resources/sts/4.16/sts_installer_core_permission_policy.json
  resources/sts/4.16/sts_installer_permission_policy.json
  resources/sts/4.16/sts_installer_privatelink_permission_policy.json
  resources/sts/4.16/sts_installer_trust_policy.json
  resources/sts/4.16/sts_installer_vpc_permission_policy.json
  resources/sts/4.16/sts_instance_controlplane_permission_policy.json
  resources/sts/4.16/sts_instance_controlplane_trust_policy.json
  resources/sts/4.16/sts_instance_worker_permission_policy.json
  resources/sts/4.16/sts_instance_worker_trust_policy.json
  resources/sts/4.16/sts_ocm_admin_permission_policy.json
  resources/sts/4.16/sts_ocm_permission_policy.json
  resources/sts/4.16/sts_ocm_trust_policy.json
  resources/sts/4.16/sts_ocm_user_trust_policy.json
  resources/sts/4.16/sts_support_permission_policy.json
  resources/sts/4.16/sts_support_trust_policy.json
Labels: approved, lgtm

#2079 OSD-22258: need to use full kind name to avoid confusion
  deploy/osd-curated-operatorsources-revert/01-osd-patch-subscription-source.ClusterRole.yaml
  deploy/osd-curated-operatorsources-revert/10-osd-patch-subscription-source.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2080 OSD-22258: fix ClusterRole from previous change
  deploy/osd-curated-operatorsources-revert/01-osd-patch-subscription-source.ClusterRole.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2078 Copy the extended support policy forward to 4.15 and 4.16 hypershift STS definitions
  resources/sts/4.15/hypershift/sts_extended_hcp_support_permission_policy.json
  resources/sts/4.16/hypershift/sts_extended_hcp_support_permission_policy.json
Labels: approved, lgtm

#2077 Add patch for default ingress router replicas to 3, based on the Org ID of the ClusterDeployment
  deploy/osd-ingress/routerreplicas-osd-20989/10-routerreplics.ingresscontroller.yaml
  deploy/osd-ingress/routerreplicas-osd-20989/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2081 add addon-acs-fleetshard-qa perm which is used for ACS staging env clusters
  deploy/backplane/acs/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2083 Fix syntax error preventing rollout
  deploy/osd-ingress/routerreplicas-osd-20989/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/templates/template.yaml
Labels: approved, lgtm

#2086 Add ec2:DescribeDhcpOptions to CAPA controller for HCP
  resources/sts/4.14/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
  resources/sts/4.15/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
  resources/sts/4.16/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
Labels: approved, lgtm

#2075 Additional aggregate cluster role and access for ACS:CS.
  deploy/backplane/acs/01-acs-admins-cluster-aggregate.ClusterRole.yaml
  deploy/backplane/acs/01-acs-admins-project.ClusterRole.yaml
  deploy/backplane/acs/02-acs-admins.SubjectPermission.yaml
  docs/backplane/requirements/acs/10-acs-managed-service.md
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#2088 ROX-23697: Add additional ACS-CS roles
  deploy/backplane/acs/01-acs-admins-cluster-aggregate.ClusterRole.yaml
  deploy/backplane/acs/01-acs-admins-project.ClusterRole.yaml
  deploy/backplane/acs/02-acs-openshift-ingress-role.yml
  deploy/backplane/acs/02-acs-openshift-ingress-rolebinding.yml
  deploy/backplane/acs/03-acs-openshift-monitoring-role.yml
  deploy/backplane/acs/03-acs-openshift-monitoring-rolebinding.yml
  deploy/backplane/acs/03-acs-rhacs-observability-role.yml
  deploy/backplane/acs/03-acs-rhacs-observability-rolebinding.yml
  docs/backplane/requirements/acs/10-acs-managed-service.md
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#2091 Consolidate image registry config patches
  deploy/osd-registry/cluster.Config.patch.yaml
  deploy/osd-registry/cluster.Config.removeNodeSelector.patch.yaml
  deploy/osd-registry/config.yaml
  deploy/osd-registry/legacy/cluster.Config.patch.yaml
  deploy/osd-registry/legacy/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#2043 Add route-monitor-operator to sre:operators:succeeded recording rule
  deploy/sre-prometheus/centralized-observability/100-sre-operators-recording-rules.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2093 Fix addon-acs-fleetshard typo for qe
  deploy/backplane/acs/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2095 ROX-23697: add ACS-CS backplane console permissions
  deploy/backplane/acs/03-acs-openshift-monitoring-role.yml
  deploy/backplane/acs/04-acs-openshift-console-role.yml
  deploy/backplane/acs/04-acs-openshift-console-rolebinding.yml
  deploy/backplane/acs/05-acs-rhacs-observability-role.yml
  deploy/backplane/acs/05-acs-rhacs-observability-rolebinding.yml
  docs/backplane/requirements/acs/10-acs-managed-service.md
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2064 feat(OSD-20591,OSD-20593): remove cpms disabelement cronjobs
  deploy/osd-14634-disable-cpms/00-osd-disable-cmps.ServiceAccount.yaml
  deploy/osd-14634-disable-cpms/01-osd-disable-cpms.Role.yaml
  deploy/osd-14634-disable-cpms/02-osd-disable-cpms.RoleBinding.yaml
  deploy/osd-14634-disable-cpms/10-osd-disable-cpms.CronJob.yaml
  deploy/osd-14634-disable-cpms/config.yaml
  deploy/osd-17901-enable-cpms/config.yaml
  deploy/osd-17901-enable-cpms/cpms-cluster.state.patch.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2100 Enable cpms with canary rollout in eu-west-2
  deploy/osd-20594-enable-cpms/config.yaml
  deploy/osd-20594-enable-cpms/cpms-cluster.state.patch.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2087 [OSD-17651] Send all UWM alerts to the CU
  deploy/ocm-agent-operator-managednotifications/10-managednotifications-cr.yaml
  deploy/sre-prometheus/monitoring/100-cluster-monitoring-error-budget-burn.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2105 Enable CPMS fleet wide for existing clusters
  deploy/osd-20594-enable-cpms/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2106 ROX-23744: Add ACSCS backplane ingress read
  deploy/backplane/acs/01-acs-admins-cluster-aggregate.ClusterRole.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2102 [MTSRE-1684] enable backplane-acs-admins-cluster role
  deploy/backplane/acs/01-acs-admins-cluster.ClusterRole.yaml
  deploy/backplane/acs/02-acs-admins.SubjectPermission.yaml
  docs/backplane/requirements/acs/10-acs-managed-service.md
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2107 Remove cpms activation patch
  deploy/osd-20594-enable-cpms/config.yaml
  deploy/osd-20594-enable-cpms/cpms-cluster.state.patch.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2104 OSD-22494: Update list for Critical Alerts in MUO IgnoreCritical List
  deploy/managed-upgrade-operator-config/10-managed-upgrade-operator-configmap.yaml
  deploy/managed-upgrade-operator-config/hypershift-mc/10-managed-upgrade-operator-configmap.yaml
  deploy/osd-fedramp-managed-upgrade-operator-config/10-managed-upgrade-operator-configmap.yaml
  deploy/osd-fedramp-managed-upgrade-operator-config/hive-prod01/10-managed-upgrade-operator-configmap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference
