Repository openshift/managed-cluster-config, pull requests merged in 2024-05, with the labels that each got.

#2094 Refactors the upstream PDBLimit alert
  deploy/sre-prometheus/100-sre-podDisruptionBudget.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2111 ROX-23744: ACSCS additional permissions
  deploy/backplane/acs-integration/05-acs-integration-rhacs-observability-role.yml
  deploy/backplane/acs-integration/05-acs-integration-rhacs-observability-rolebinding.yml
  deploy/backplane/acs-integration/config.yaml
  deploy/backplane/acs/01-acs-admins-cluster.ClusterRole.yaml
  deploy/backplane/acs/01-acs-admins-project.ClusterRole.yaml
  deploy/backplane/acs/04-acs-openshift-machine-api-role.yml
  deploy/backplane/acs/04-acs-openshift-machine-api-rolebinding.yml
  docs/backplane/requirements/acs/10-acs-managed-service-nonprod.md
  docs/backplane/requirements/acs/10-acs-managed-service.md
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2113 Update OSD Cluster Ready version
  deploy/osd-cluster-ready/job/10-osd-ready.Job.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2110 OSD-15299: NodeFileDescriptorLimit alert link to SOP instead of runbook
  deploy/sre-prometheus/100-node-filedescriptor-limits.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2114 Update 10-managed-upgrade-operator-configmap.yaml
  deploy/managed-upgrade-operator-config/10-managed-upgrade-operator-configmap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2108 OSD-21162: Add MachineHealthCheckUnterminatedShortCircuitSRE alert
  deploy/sre-prometheus/100-machine-health-check-unterminated-short-circuit.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2117 Refactors alert definition.
  deploy/sre-prometheus/100-sre-podDisruptionBudget.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2115 ROX-23744: additional acscs permissions
  deploy/backplane/acs/01-acs-admins-cluster.ClusterRole.yaml
  deploy/backplane/acs/02-acs-admins.SubjectPermission.yaml
  deploy/backplane/acs/04-acs-openshift-machine-api-role.yml
  deploy/backplane/acs/04-acs-openshift-machine-api-rolebinding.yml
  docs/backplane/requirements/acs/10-acs-managed-service.md
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2121 Mcs requirements
  deploy/acm-policies/50-GENERATED-backplane-cee.Policy.yaml
  deploy/backplane/cee/01-cee-cluster-readers-cluster.ClusterRole.yml
  docs/backplane/requirements/cee/10-egressip.md
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#2128 chore: offboard supreeth
  OWNERS
Labels: approved, lgtm

#2130 OSD-22575: add permissions to dedicated-reader and dedicated-admin to view console/monitoring tab data
  deploy/acm-policies/50-GENERATED-rbac-permissions-operator-config.Policy.yaml
  deploy/rbac-permissions-operator-config/05-osd-readers.ClusterRole.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2132 [OSD-22043] Update sre-operators recording rule
  deploy/sre-prometheus/centralized-observability/100-sre-operators-recording-rules.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2127 [OSD-21742] - Added admin gates for 4.16
  deploy/osd-cluster-acks/ocp/4.16/admin-gates.yaml
  deploy/osd-cluster-acks/ocp/4.16/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm
