Repository openshift/managed-cluster-config, pull requests merged in 2024-06, with the labels that each got.

#2129 SDCICD-1292: set MGO NS resourceApplyMode=Upsert
  deploy/osd-must-gather-operator/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2134 removes fedramp clusters from commercial specific sss
  deploy/cloud-ingress-operator-configuration/routerreplicas-osd-8028/config.yaml
  deploy/crio-loglinking/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2135 Adds 4.16 version gates to enable 4.16 upgrades.
  deploy/osd-cluster-acks/sts/4.16/config.yaml
  deploy/osd-cluster-acks/sts/4.16/osd-sts-ack_CloudCredential.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2137 OSD-23863: disable KubeletDebuggingHandlersEnabledSRE alert on int/staging
  deploy/sre-prometheus/management-cluster/production/100-kubeletconfig-debugging-handlers-enabled.PrometheusRule.yaml
  deploy/sre-prometheus/management-cluster/production/README.md
  deploy/sre-prometheus/management-cluster/production/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2139 Excludes openshift-cnv namespace
  deploy/sre-prometheus/100-sre-podDisruptionBudget.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#2141 [osd-22081] Fix patchType field capitalization.
  deploy/osd-dns-default/dns-default.Dns.patch.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2142 Revert osd 22081
  deploy/osd-dns-default/README.md
  deploy/osd-dns-default/config.yaml
  deploy/osd-dns-default/dns-default.Dns.patch.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2146 Remove the gate-sts key from selectorsyncset
  deploy/osd-cluster-acks/sts/4.16/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2144 [OSD-22081] Put dns-default pods on infras
  deploy/osd-dns-default/README.md
  deploy/osd-dns-default/config.yaml
  deploy/osd-dns-default/dns-default.Dns.patch.yaml
  deploy/osd-rebalance-infra-nodes/07-osd-rebalance-infra-nodes.ConfigMap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2145 Add new 4.16 permissions for CAPI in the installer
  resources/sts/4.16/sts_installer_core_permission_boundary_policy.json
  resources/sts/4.16/sts_installer_permission_policy.json
Labels: approved, lgtm

#2149 OSD-22635: remove SRE role ability pod exec and attach
  deploy/acm-policies/50-GENERATED-backplane-srep.Policy.yaml
  deploy/backplane/lpsre/rhmi/01-rhmi-lpsre-admins-project.ClusterRole.yaml
  deploy/backplane/lpsre/rhoam/01-rhoam-lpsre-admins-project.ClusterRole.yaml
  deploy/backplane/srep/10-srep-admins-project.ClusterRole.yml
  docs/backplane/requirements/srep/10-managed-ocp.md
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2150 Add missing 4.16 upgrade ack: https://access.redhat.com/articles/7031404
  deploy/osd-cluster-acks/ocp/4.16/admin-gates.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#2140 OCPBUGS-25341 - Add job to refresh packageserver csv across fleet
  deploy/ocpbugs-25341/01-serviceaccount.yaml
  deploy/ocpbugs-25341/02-role.yaml
  deploy/ocpbugs-25341/03-rolebinding.yaml
  deploy/ocpbugs-25341/04-job.yaml
  deploy/ocpbugs-25341/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2147 ROX-24728: additional ACS permissions
  deploy/backplane/acs-integration/01-acs-integration-rhacs-observability-role.yml
  deploy/backplane/acs-integration/01-acs-integration-rhacs-observability-rolebinding.yml
  deploy/backplane/acs/01-acs-admins-cluster.ClusterRole.yaml
  deploy/backplane/acs/01-acs-admins-project.ClusterRole.yaml
  docs/backplane/requirements/acs/10-acs-managed-service.md
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2154 ROX-24901: Allow ACS SRE to delete pods
  deploy/backplane/acs/01-acs-admins-project.ClusterRole.yaml
  docs/backplane/requirements/acs/10-acs-managed-service.md
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2153 Adding permissions in backplane for CEE to support ACS:CS
  deploy/acm-policies/50-GENERATED-backplane-cee-sp.Policy.yaml
  deploy/backplane/cee/40-cee.SubjectPermission.yml
  docs/backplane/requirements/README.md
  docs/backplane/requirements/cee/40-backplane-cee.md
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2148 [OSD-22254] initial permissions for gcp wif
  resources/wif/4.14/vanilla.yaml
  resources/wif/4.15/vanilla.yaml
  resources/wif/4.16/vanilla.yaml
  resources/wif/README.md
Labels: approved, lgtm, tide/merge-method-squash
