Repository openshift/managed-cluster-config, pull requests merged in 2024-07, with the labels that each got.

#2155 disable UpgradeConfigSyncFailureOver4HrSRE alert for 4.16 temporary
  deploy/sre-prometheus/100-managed-upgrade-operator.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2151 Add comment about individual maintainers
  OWNERS
Labels: approved, lgtm

#2157 [SDCICD-1292] Remove osd-must-gather-operator SSS containing MGO namespace
  deploy/acm-policies/50-GENERATED-osd-must-gather-operator.Policy.yaml
  deploy/osd-must-gather-operator/01-openshift-must-gather-operator.Namespace.yaml
  deploy/osd-must-gather-operator/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  hack/app_sre_pr_check.sh
  scripts/generate-policy-config.py
Labels: approved, lgtm

#2158 [OHSS-35778] Revert running dns pods on infra nodes.
  deploy/osd-dns-default/README.md
  deploy/osd-dns-default/config.yaml
  deploy/osd-dns-default/dns-default.Dns.patch.yaml
  deploy/osd-rebalance-infra-nodes/07-osd-rebalance-infra-nodes.ConfigMap.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2156 add ACM Policies for ACS backplane
  deploy/acm-policies/50-GENERATED-backplane-acs.Policy.yaml
  deploy/backplane/acs/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/generate-policy-config.py
Labels: approved, lgtm

#2159 [OHSS-32768] Add a job to remove the added dns tolerations.
  deploy/osd-22018-remove-dns-tolerations/01-serviceaccount.yaml
  deploy/osd-22018-remove-dns-tolerations/02-role.yaml
  deploy/osd-22018-remove-dns-tolerations/03-rolebinding.yaml
  deploy/osd-22018-remove-dns-tolerations/04-job.yaml
  deploy/osd-22018-remove-dns-tolerations/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2163 Fleet-wide custom-domains-operator
  deploy/osd-24397/00-roles.yaml
  deploy/osd-24397/01-job.yaml
  deploy/osd-24397/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2164 OSD-24397 Fix typo to OLM Version Check
  deploy/osd-24397/01-job.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2166 Correct bundle version
  deploy/osd-24397/01-job.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2168 [backplane/lpsre] add missing matchLabel for addon-acs-fleetshard-qe
  deploy/backplane/lpsre/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2171 ROX-25275: Add permissions to read ACS addon objects for ACS team
  deploy/acm-policies/50-GENERATED-backplane-acs.Policy.yaml
  deploy/backplane/acs/01-acs-admins-project.ClusterRole.yaml
  docs/backplane/requirements/acs/10-acs-managed-service.md
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2172 OSD-24336 Update Suricata and Log Cleaner SHA
  deploy/osd-suricata/20-osd-suricata-Daemonset.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2167 Remove remediation for CDO CSV out of date
  deploy/osd-24397/00-roles.yaml
  deploy/osd-24397/01-job.yaml
  deploy/osd-24397/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#2101 [OCPBUGS-15043] fix cronjob failing to detect seccomp issues
  deploy/ocpbugs-15043/01-ocpbugs-15043.Role.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2174 Restore MGO's NS, but for fedramp only
  deploy/01-openshift-must-gather-operator.Namespace.yaml
  deploy/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2175 [OSD-19661] add sre-cluster-version-operator PrometheusRule
  deploy/sre-prometheus/100-cluster-version-operator.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2179 Reformat wif templates
  resources/wif/4.14/vanilla.yaml
  resources/wif/4.15/vanilla.yaml
  resources/wif/4.16/vanilla.yaml
Labels: approved, lgtm

#2173 Adds CloudCredentials annotation for 4.15 GCP Upgrades
  deploy/osd-cluster-acks/gcp/4.15/config.yaml
  deploy/osd-cluster-acks/gcp/4.15/osd-gcp-ack_CloudCredential.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm
