Repository openshift/managed-cluster-config, pull requests merged in 2024-02, with the labels that each got.

#2008 Add Benson to team leads
  OWNERS_ALIASES
Labels: approved, lgtm

#2009 fix gpg error for marketplace operators
  deploy/osd-fedramp-machineconfig/int/pre-4.13/51-master-rh-registry-trust.yaml
  deploy/osd-fedramp-machineconfig/int/pre-4.13/51-worker-rh-registry-trust.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#2010 [OSD-20478] Filter only for SRE Operators in the sre operators record…
  deploy/sre-prometheus/centralized-observability/100-sre-operators-recording-rules.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2011 [OSD-20479] Add addon-operator to sre operators recording rule
  deploy/sre-prometheus/centralized-observability/100-sre-operators-recording-rules.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1863 deprecate direct deployment method
  README.md
  scripts/generate_template.py
Labels: approved, lgtm

#2013 stage fedramp fix gpg error for marketplace operators
  deploy/osd-fedramp-machineconfig/prod/pre-4.13/51-master-rh-registry-trust.yaml
  deploy/osd-fedramp-machineconfig/prod/pre-4.13/51-worker-rh-registry-trust.yaml
  deploy/osd-fedramp-machineconfig/stg/pre-4.13/51-master-rh-registry-trust.yaml
  deploy/osd-fedramp-machineconfig/stg/pre-4.13/51-worker-rh-registry-trust.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2016 Update sre-infra-resizing-alerts to critical
  deploy/sre-prometheus/100-infra-resizing.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#2018 Remove log linking workaround in 4.15
  deploy/crio-loglinking/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2019 ensure CPMS is disabled on 4.15 for now
  deploy/osd-14634-disable-cpms/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2023 backplane owners allow parent owners
  deploy/backplane/OWNERS
Labels: approved, lgtm

#1867 add region leads as OWNERS for alerts
  OWNERS_ALIASES
  deploy/sre-prometheus/OWNERS
  hack/OWNERS
Labels: lifecycle/rotten, approved, lgtm

#2022 Grant LPSRE read permissions to Dynatrace namespace resources
  deploy/backplane/lpsre/dynatrace/01-lpsre-dynatrace.Role.yml
  deploy/backplane/lpsre/dynatrace/02-lpsre-dynatrace.RoleBinding.yml
  deploy/backplane/lpsre/dynatrace/config.yaml
  deploy/backplane/lpsre/dynatrace/otel/01-lpsre-otel.Role.yml
  deploy/backplane/lpsre/dynatrace/otel/02-lpsre-otel.RoleBinding.yml
  deploy/backplane/lpsre/dynatrace/otel/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2024 [OSD-20486] Adding an automated SL when KubeNodeUnschedulableSRE alerting and changing the alert severity to Warning
  deploy/ocm-agent-operator-managednotifications/10-managednotifications-cr.yaml
  deploy/sre-prometheus/100-node-unschedulable.PrometheusRule.yaml
  deploy/sre-prometheus/ocm-agent/100-ocm-agent.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#2020 OSD-20677 schedule monitoring-plugin pods onto infra nodes
  deploy/osd-monitoring-plugin/00-cluster-monitoring-config.ConfigMap.yaml
  deploy/osd-monitoring-plugin/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2029 [OSD-21260] hold fire for the node condition alerts to avoid flipping notification sending
  deploy/sre-prometheus/ocm-agent/node-condition/100-ocm-agent-node-condition.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#1999 AUTH-478: osd-suricata - add proper pod-security labels
  deploy/osd-ids-tester/100-ids-tester.Namespace.yaml
  deploy/osd-suricata/00-osd-suricata-Namespace.yaml
  deploy/osd-suricata/hypershift-management-cluster/00-osd-suricata-Namespace.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2026 SDCICD-1229: add cluster metadata cm
  deploy/osd-cluster-metadata/10-osd-cluster-metadata.openshift-config.ConfigMap.yaml
  deploy/osd-cluster-metadata/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/generate_template.py
Labels: approved, lgtm, jira/valid-reference

#2030 SDCICD-1229: fup: s/enableResourceParameters/enableResourceTemplates/g
  deploy/osd-cluster-metadata/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/generate_template.py
Labels: approved, lgtm, jira/valid-reference
