Repository openshift/managed-cluster-config, pull requests merged in 2024-12, with the labels that each got.

#2258 (OSD-25580) Ship Network Live Migration Metrics to Telemetry
  deploy/sdn-ovn-migration/100-network-live-migration.PrometheusRule.yaml
  deploy/sdn-ovn-migration/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  resources/cluster-monitoring-config/config.yaml
Labels: approved, lgtm, tide/merge-method-squash

#2287 Add RMO OLM dance cron job
  deploy/rmo-olm-dance/00-roles.yaml
  deploy/rmo-olm-dance/01-cronjob.yaml
  deploy/rmo-olm-dance/config.yaml
  deploy/rmo-olm-dance/readme.md
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2289 Remove RMO OLM Dance Cron Job
  deploy/rmo-olm-dance/00-roles.yaml
  deploy/rmo-olm-dance/01-cronjob.yaml
  deploy/rmo-olm-dance/config.yaml
  deploy/rmo-olm-dance/readme.md
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2288 Update fedramp ntp to use aws ntp server
  deploy/osd-fedramp-machineconfig/00-fedramp-chrony-master.yaml
  deploy/osd-fedramp-machineconfig/00-fedramp-chrony-worker.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2285 OSD-26221: update automated HCP OIDC limited support timing and messaging
  deploy/ocm-agent-operator-managedfleetnotifications/oidc-deleted-limited-support.yaml
  deploy/sre-prometheus/ocm-agent/obo-monitoring/100-oidc-missing.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2291 revert fedramp ntp update
  deploy/osd-fedramp-machineconfig/00-fedramp-chrony-master.yaml
  deploy/osd-fedramp-machineconfig/00-fedramp-chrony-worker.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2292 Fix: remove whitespace at end of OIDC limited support message
  deploy/ocm-agent-operator-managedfleetnotifications/oidc-deleted-limited-support.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2284 ROX-26660: backplane permissions for rhobs, grafana and gitops CRs
  .gitignore
  deploy/acm-policies/50-GENERATED-backplane-acs.Policy.yaml
  deploy/backplane/acs/01-acs-admins-cluster.ClusterRole.yaml
  deploy/backplane/acs/05-acs-rhacs-observability-role.yml
  deploy/backplane/acs/06-acs-openshift-gitops-role.yml
  deploy/backplane/acs/06-acs-openshift-gitops-rolebinding.yml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2295 OSD-27041: remove 'viewer' from srep service cluster permissions
  deploy/backplane/srep/hypershift/service-cluster/20-srep.SubjectPermission.yml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2276 OSD-26236 leaver process member removal
  deploy/osd-avo-resources/OWNERS
  deploy/osd-fedramp-managed-upgrade-operator-config/OWNERS
Labels: approved, lgtm

#2297 ensure 4.17 policy is at parity with current changes
  resources/sts/4.17/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
Labels: approved, lgtm

#2283 XCMSTRAT-781: Shared VPC for HCP Policies
  resources/sts/4.17/hypershift/openshift_hcp_shared_vpc_route_53_credentials_policy.json
  resources/sts/4.17/hypershift/openshift_hcp_shared_vpc_vpc_endpoint_credentials_policy.json
Labels: approved, lgtm, jira/valid-reference

#2299 OSD-26960: Reinstall the ocm-agent-operator across the fleet
  deploy/osd-26960/00-roles.yaml
  deploy/osd-26960/01-cronjob.yaml
  deploy/osd-26960/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2300 Correct API version for CronJob in ocm-agent-operator reinstall
  deploy/osd-26960/01-cronjob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2301 OSD-26960: Remove reinstall-operator for ocm-agent-operator
  deploy/osd-26960/00-roles.yaml
  deploy/osd-26960/01-cronjob.yaml
  deploy/osd-26960/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2302 ITN-281: olm dance ocm-agent-operator
  deploy/osd-26960/00-roles.yaml
  deploy/osd-26960/01-cronjob.yaml
  deploy/osd-26960/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2303 Fix oao olm dance cronjob to ignore cases where resources are missing
  deploy/osd-26960/01-cronjob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#2304 Fix olm dance cronjob to use FQDN for objects to delete
  deploy/osd-26960/01-cronjob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2305 Fix oao olm dance csv/installplan listing
  deploy/osd-26960/01-cronjob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2306 Remove oao olm-dance cronjob
  deploy/osd-26960/00-roles.yaml
  deploy/osd-26960/01-cronjob.yaml
  deploy/osd-26960/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2298 AUTH-482: set required-scc for openshift workloads
  deploy/osd-cluster-ready/job/10-osd-ready.Job.yaml
  deploy/osd-rebalance-infra-nodes/10-osd-rebalance-infra-nodes.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2308 Add notice about CAD's backplane requirement
  deploy/backplane/configuration-anomaly-detection/README.md
Labels: approved, lgtm

#2309 OSD-27279: Ensure ClusterMonitoringErrorBudgetBurnSRE alert excludes user-workload-monitoring failure reasons
  deploy/sre-prometheus/monitoring/100-cluster-monitoring-error-budget-burn.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2310 OSD-25974 - Update PromRule to monitor OTELCollector
  deploy/sre-prometheus/management-cluster/100-dynatrace-workloads-monitoring.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2311 RMO OLM dance cron job
  deploy/rmo-olm-dance/00-roles.yaml
  deploy/rmo-olm-dance/01-cronjob.yaml
  deploy/rmo-olm-dance/config.yaml
  deploy/rmo-olm-dance/readme.md
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2312 RMO OLM dance cron job removal
  deploy/rmo-olm-dance/00-roles.yaml
  deploy/rmo-olm-dance/01-cronjob.yaml
  deploy/rmo-olm-dance/config.yaml
  deploy/rmo-olm-dance/readme.md
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm
