Repository openshift/managed-cluster-config, pull requests merged in 2025-09, with the labels that each got.

#2503 Adding RBAC for MVO to OADP Migration help
  deploy/velero-configuration/120-velero.Secret-Role.yaml
  deploy/velero-configuration/130-velero.Secret-RoleBinding.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2495 SREP-1000: Add supplemental node-exporter to collect ethtool AWS packet drop metrics
  deploy/srep-1000-ethtool-exporter/00-Namespace.yaml
  deploy/srep-1000-ethtool-exporter/01-ServiceAccount.yaml
  deploy/srep-1000-ethtool-exporter/02-Role.yaml
  deploy/srep-1000-ethtool-exporter/03-RoleBinding.yaml
  deploy/srep-1000-ethtool-exporter/05-ClusterRoleBinding.yaml
  deploy/srep-1000-ethtool-exporter/06-SecurityContextConstraints.yaml
  deploy/srep-1000-ethtool-exporter/07-ConfigMap.yaml
  deploy/srep-1000-ethtool-exporter/08-Secret.yaml
  deploy/srep-1000-ethtool-exporter/09-DaemonSet.yaml
  deploy/srep-1000-ethtool-exporter/10-Service.yaml
  deploy/srep-1000-ethtool-exporter/11-ServiceMonitor.yaml
  deploy/srep-1000-ethtool-exporter/README.md
  deploy/srep-1000-ethtool-exporter/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#2511 added OWNERS to wif directory
  resources/wif/OWNERS
Labels: approved, lgtm

#2517 Add hypershift autoscaler podmonitor for srep-1665
  deploy/hypershift-autoscaler-podmonitor/01-autoscaler-podmonitor.yaml
  deploy/hypershift-autoscaler-podmonitor/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2516 SREP-1813: HCP Log Forwarding for Management Clusters
  deploy/hypershift-control-plane-log-forwarding/00-namespace.yaml
  deploy/hypershift-control-plane-log-forwarding/10-clusterrole.yaml
  deploy/hypershift-control-plane-log-forwarding/10-security-context-constraint.yaml
  deploy/hypershift-control-plane-log-forwarding/10-serviceaccount.yaml
  deploy/hypershift-control-plane-log-forwarding/15-clusterrolebinding.yaml
  deploy/hypershift-control-plane-log-forwarding/30-vector-config.yaml
  deploy/hypershift-control-plane-log-forwarding/50-daemonset.yaml
  deploy/hypershift-control-plane-log-forwarding/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2522 removes hive SSS interpolation from vector config vars
  deploy/hypershift-control-plane-log-forwarding/30-vector-config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2524 Maint: update managedfleetnotification SSS and docs
  deploy/ocm-agent-operator-managedfleetnotifications/OWNERS
  deploy/ocm-agent-operator-managedfleetnotifications/README.md
  deploy/ocm-agent-operator-managedfleetnotifications/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2520 Add CLAUDE.md documentation
  CLAUDE.md
Labels: approved, lgtm

#2527 Drop KubeControllerManager CrashLooping stop gap alert from classic
  deploy/sre-prometheus/100-kube-controller-manager-crashlooping.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm
