Repository openshift/managed-cluster-config, pull requests merged in 2025-05, with the labels that each got.

#2419 OSD-28970 add 6 metrics for central observility
  deploy/management-cluster-prometheus-metrics/50-GENERATED-cluster-monitoring-config.yaml
  deploy/management-cluster-prometheus-metrics/config.yaml
  deploy/sre-prometheus/centralized-observability/100-sre-internal-slo-recording-rules.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2425 defined wif admin gate for v4.19
  deploy/osd-cluster-acks/wif/4.19/config.yaml
  deploy/osd-cluster-acks/wif/4.19/osd-wif-ack_CloudCredential.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: needs-ok-to-test, approved, lgtm

#2429 Revert "[OSD-28131] OBO CSV Cleanup CronJob for Hypershift SC clusters"
  deploy/obo-removal-for-sc-clusters/01-ClusterRole.yaml
  deploy/obo-removal-for-sc-clusters/02-CronJob.yaml
  deploy/obo-removal-for-sc-clusters/README.md
  deploy/obo-removal-for-sc-clusters/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2431 Add myself to functional lead now
  OWNERS_ALIASES
Labels: approved, lgtm

#2432 Revert OCPBUGS-25341 workaround: remove sre-replace-packageserver-csv…
  deploy/ocpbugs-25341/01-serviceaccount.yaml
  deploy/ocpbugs-25341/02-role.yaml
  deploy/ocpbugs-25341/03-rolebinding.yaml
  deploy/ocpbugs-25341/04-job.yaml
  deploy/ocpbugs-25341/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2435 Removes legacy brand policy creation
  deploy/acm-policies/50-GENERATED-rosa-console-legacy-branding-configmap.Policy.yaml
  deploy/acm-policies/50-GENERATED-rosa-console-legacy-branding.Policy.yaml
  deploy/rosa-console-legacy-branding-configmap/config.yaml
  deploy/rosa-console-legacy-branding/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/generate-policy-config.py
Labels: approved, lgtm

#2433 SREP-400: Refactor CAPI annotator job
  deploy/osd-25821-capa-annotator/04-ConfigMap.yaml
  deploy/osd-25821-capa-annotator/10-CronJob-4-14.yaml
  deploy/osd-25821-capa-annotator/10-CronJob-4-15.yaml
  deploy/osd-25821-capa-annotator/10-CronJob-4-16.yaml
  deploy/osd-25821-capa-annotator/10-CronJob-4-17.yaml
  deploy/osd-25821-capa-annotator/README.md
  deploy/osd-25821-capa-annotator/generate_configmap.sh
  deploy/osd-25821-capa-annotator/patch.sh
  deploy/osd-25821-capa-annotator/should_patch.py
  deploy/osd-25821-capa-annotator/tests.py
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#2437 Reverts ROSA Branding changes to unblock promotion
  Makefile
  deploy/acm-policies/50-GENERATED-rosa-console-branding-configmap.Policy.yaml
  deploy/acm-policies/50-GENERATED-rosa-console-branding.Policy.yaml
  deploy/rosa-console-branding-configmap/OWNERS
  deploy/rosa-console-branding-configmap/config.yaml
  deploy/rosa-console-branding-configmap/rosa-brand-logo.yaml
  deploy/rosa-console-branding/config.yaml
  deploy/rosa-console-branding/rosa-branding.Console.yaml
  deploy/rosa-console-legacy-branding/OWNERS
  deploy/rosa-console-legacy-branding/config.yaml
  deploy/rosa-console-legacy-branding/rosa-branding.Console.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/generate-policy-config.py
Labels: approved, lgtm
