Repository openshift/managed-cluster-config, pull requests merged in 2025-03, with the labels that each got.

#2370 OSD-27897: Add pki-operator-annotator configuration for 4.15
  deploy/ocpbugs-48519/10-CronJob-4-15.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2365 OSD-27878 - Delete po in DT namespace without bp elevate
  deploy/backplane/srep/dynatrace/10-srep-dynatrace.Role.yml
  deploy/backplane/srep/dynatrace/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2371 OSD-26790: Adding UpgradeStateNotificationFailureSRE alert
  deploy/sre-prometheus/100-managed-upgrade-operator.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2372 OSD-28572: Avoiding SlowCustomerWebhookSRE eval to fail when there are several configs for a given webhook name
  deploy/sre-prometheus/ocm-agent/100-customer-webooks.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2373 Remove control plane operator image pin annotation from all clusters
  deploy/ocpbugs-48519/04-ConfigMap.yaml
  deploy/ocpbugs-48519/patch.sh
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2377 swap to job and fix some logic
  deploy/osd-route-monitor-operator-reinstall/04-openshift-route-monitor-operator.CronJob.yaml
  deploy/osd-route-monitor-operator-reinstall/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#2375 OSD-28722: re-add view aggregation to SRE-P service cluster access
  deploy/backplane/srep/hypershift/service-cluster/20-srep.SubjectPermission.yml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2381 Revert the RMO re-install cron
  deploy/osd-route-monitor-operator-reinstall/01-openshift-route-monitor-operator.ServiceAccount.yaml
  deploy/osd-route-monitor-operator-reinstall/02-openshift-route-monitor-operator.Role.yaml
  deploy/osd-route-monitor-operator-reinstall/03-openshift-route-monitor-operator.RoleBinding.yaml
  deploy/osd-route-monitor-operator-reinstall/04-openshift-route-monitor-operator.CronJob.yaml
  deploy/osd-route-monitor-operator-reinstall/README.md
  deploy/osd-route-monitor-operator-reinstall/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2382 OCM Agent Operator Perform Re-install
  deploy/osd-27575/01-ClusterRole.yaml
  deploy/osd-27575/02-CronJob.yaml
  deploy/osd-27575/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2368 OSD-27692: New crontab to clean backplane remediation RBACs in case the remediation was not properly deleted
  deploy/osd-delete-backplane-remediation-rbacs/00-delete-backplane-remediation-rbacs.namespace.yml
  deploy/osd-delete-backplane-remediation-rbacs/10-delete-backplane-remediation-rbacs.rbac.yaml
  deploy/osd-delete-backplane-remediation-rbacs/20-delete-backplane-remediation-rbacs.CronJob.yaml
  deploy/osd-delete-backplane-remediation-rbacs/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2387 OCM Agent Operator Revert Re-install
  deploy/osd-27575/01-ClusterRole.yaml
  deploy/osd-27575/02-CronJob.yaml
  deploy/osd-27575/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2386 OSD-27692: Making sure that the new crontab cleaning up backplane remediation RBACs can run successfully
  deploy/osd-delete-backplane-remediation-rbacs/10-delete-backplane-remediation-rbacs.rbac.yaml
  deploy/osd-delete-backplane-remediation-rbacs/20-delete-backplane-remediation-rbacs.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2388 OSD-27692: Making sure that the new crontab cleaning up backplane remediation RBACs can run successfully - adding back the ClusterRoleBinding
  deploy/osd-delete-backplane-remediation-rbacs/15-delete-backplane-remediation-rbacs.rbac.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2390 Fix OAO reinstall
  deploy/osd-27575/01-ClusterRole.yaml
  deploy/osd-27575/02-CronJob.yaml
  deploy/osd-27575/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2389 OSD-27692: Making sure that the new crontab cleaning up backplane remediation RBACs can run successfully - correcting the cronjob script
  deploy/osd-delete-backplane-remediation-rbacs/20-delete-backplane-remediation-rbacs.CronJob.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2392 Revert - #2390 Fix OAO reinstall commit
  deploy/osd-27575/01-ClusterRole.yaml
  deploy/osd-27575/02-CronJob.yaml
  deploy/osd-27575/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2393 Re-install OCM Agent Operator New Logic
  deploy/osd-27575/01-ClusterRole.yaml
  deploy/osd-27575/02-Job.yaml
  deploy/osd-27575/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#2394 OSD-26960: Drop ocm-agent-operator reinstall Job
  deploy/osd-27575/01-ClusterRole.yaml
  deploy/osd-27575/02-Job.yaml
  deploy/osd-27575/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2395 OSD-26790: olm dance muo
  deploy/osd-26790/00-roles.yaml
  deploy/osd-26790/01-cronjob.yaml
  deploy/osd-26790/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2380 [OSD 28223] Handle worker (node filesystem) alert using ocm-agent
  deploy/ocm-agent-operator-managednotifications/10-managednotifications-cr.yaml
  deploy/sre-prometheus/100-node-filedescriptor-limits.PrometheusRule.yaml
  deploy/sre-prometheus/ocm-agent/100-ocm-agent.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2396 OSD-26790: Revoke MUO OLM dance
  deploy/osd-26790/00-roles.yaml
  deploy/osd-26790/01-cronjob.yaml
  deploy/osd-26790/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2356 [OSD-28131] OBO CSV Cleanup CronJob for Hypershift SC clusters
  deploy/obo-removal-for-sc-clusters/01-ClusterRole.yaml
  deploy/obo-removal-for-sc-clusters/02-CronJob.yaml
  deploy/obo-removal-for-sc-clusters/README.md
  deploy/obo-removal-for-sc-clusters/config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2397 OSD-27299: Making sure operators installed in user workload namespaces are ignored in case the same operator is installed in an openshift namespace
  deploy/sre-prometheus/centralized-observability/100-sre-operators-recording-rules.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference
