Repository openshift/managed-cluster-config, pull requests merged in 2025-04, with the labels that each got.

#2201 Added package-operator metrics
  deploy/cluster-monitoring-config-non-uwm/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config-non-uwm/clusters-v4.5/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config-non-uwm/management-clusters/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config-non-uwm/pre-4.11/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config/management-clusters/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config/pre-4.11/50-GENERATED-cluster-monitoring-config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  resources/cluster-monitoring-config/config.yaml
Labels: approved, lgtm

#2401 Maint(OSD-29242): exclude openshift-cluster-observability-operator fr…
  deploy/sre-prometheus/100-sre-podDisruptionBudget.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2403 Added 4.19 IAM policies to sts/
  resources/sts/4.19/hypershift/README.md
  resources/sts/4.19/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
  resources/sts/4.19/hypershift/openshift_hcp_cloud_network_config_cloud_credentials_permission_policy.json
  resources/sts/4.19/hypershift/openshift_hcp_cluster_csi_driver_ebs_operator_cloud_credentials_policy.json
  resources/sts/4.19/hypershift/openshift_hcp_cluster_ingress_operator_cloud_credentials_policy.json
  resources/sts/4.19/hypershift/openshift_hcp_control_plane_operator_credentials_policy.json
  resources/sts/4.19/hypershift/openshift_hcp_image_registry_operator_permission_policy.json
  resources/sts/4.19/hypershift/openshift_hcp_kms_provider_credential_policy.json
  resources/sts/4.19/hypershift/openshift_hcp_kube_controller_manager_credentials_policy.json
  resources/sts/4.19/hypershift/openshift_hcp_shared_vpc_route_53_credentials_policy.json
  resources/sts/4.19/hypershift/openshift_hcp_shared_vpc_vpc_endpoint_credentials_policy.json
  resources/sts/4.19/hypershift/sts_extended_hcp_support_permission_policy.json
  resources/sts/4.19/hypershift/sts_hcp_installer_permission_policy.json
  resources/sts/4.19/hypershift/sts_hcp_support_permission_policy.json
  resources/sts/4.19/hypershift/sts_hcp_worker_instance_permission_policy.json
  resources/sts/4.19/openshift_aws_vpce_operator_avo_aws_creds_policy.json
  resources/sts/4.19/openshift_capa_controller_manager_credentials_policy.json
  resources/sts/4.19/openshift_cloud_credential_operator_cloud_credential_operator_iam_ro_creds_policy.json
  resources/sts/4.19/openshift_cloud_ingress_operator_cloud_credentials_policy.json
  resources/sts/4.19/openshift_cloud_network_config_controller_cloud_credentials_policy.json
  resources/sts/4.19/openshift_cluster_csi_drivers_ebs_cloud_credentials_policy.json
  resources/sts/4.19/openshift_control_plane_operator_credentials_policy.json
  resources/sts/4.19/openshift_image_registry_installer_cloud_credentials_policy.json
  resources/sts/4.19/openshift_ingress_operator_cloud_credentials_policy.json
  resources/sts/4.19/openshift_kms_provider_credentials_policy.json
  resources/sts/4.19/openshift_kube_controller_manager_credentials_policy.json
  resources/sts/4.19/openshift_machine_api_aws_cloud_credentials_policy.json
  resources/sts/4.19/operator_iam_role_policy.json
  resources/sts/4.19/osd_scp_policy.json
  resources/sts/4.19/shared_vpc_openshift_ingress_operator_cloud_credentials_policy.json
  resources/sts/4.19/sts_installer_core_permission_boundary_policy.json
  resources/sts/4.19/sts_installer_permission_policy.json
  resources/sts/4.19/sts_installer_privatelink_permission_boundary_policy.json
  resources/sts/4.19/sts_installer_trust_policy.json
  resources/sts/4.19/sts_installer_vpc_permission_boundary_policy.json
  resources/sts/4.19/sts_instance_controlplane_permission_policy.json
  resources/sts/4.19/sts_instance_controlplane_trust_policy.json
  resources/sts/4.19/sts_instance_worker_permission_policy.json
  resources/sts/4.19/sts_instance_worker_trust_policy.json
  resources/sts/4.19/sts_ocm_admin_permission_policy.json
  resources/sts/4.19/sts_ocm_permission_policy.json
  resources/sts/4.19/sts_ocm_trust_policy.json
  resources/sts/4.19/sts_ocm_user_trust_policy.json
  resources/sts/4.19/sts_support_permission_policy.json
  resources/sts/4.19/sts_support_trust_policy.json
Labels: approved, lgtm

#2404 Added 4.19 IAM policies to wif/
  resources/wif/4.19/vanilla.yaml
Labels: approved, lgtm

#2408 Rescope capa
  resources/sts/4.17/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
  resources/sts/4.18/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
Labels: approved, lgtm

#2410 Fix OCMAgentResponseFailureServiceLogsSRE alert
  deploy/sre-prometheus/100-ocm-agent-operator.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2411 Force CAMO to re-install w/ `olm.skipRange` annotations
  deploy/configure-alertmanager-operator-reinstall/config.yaml
  deploy/configure-alertmanager-operator-reinstall/job.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#2405 [OSD-29363] Move metrics-server to infra nodes
  deploy/cluster-monitoring-config-non-uwm/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config-non-uwm/clusters-v4.5/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config-non-uwm/management-clusters/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config-non-uwm/pre-4.11/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config/management-clusters/50-GENERATED-cluster-monitoring-config.yaml
  deploy/cluster-monitoring-config/pre-4.11/50-GENERATED-cluster-monitoring-config.yaml
  deploy/osd-fedramp-cluster-monitoring-config/50-GENERATED-cluster-monitoring-config.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  resources/cluster-monitoring-config/config.yaml
Labels: approved, lgtm

#2414 remove CAMO celanup job
  deploy/configure-alertmanager-operator-reinstall/config.yaml
  deploy/configure-alertmanager-operator-reinstall/job.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, tide/merge-method-squash

#2415 OSD-29046: Fixing SlowCustomerWebhookSRE, Not to trigger if service name missing
  deploy/sre-prometheus/ocm-agent/100-customer-webooks.PrometheusRule.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm, jira/valid-reference

#2418 OSD-29569: increases supported storage quota to 20TB
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
  scripts/templates/template.yaml
Labels: approved, lgtm, jira/valid-reference

#2417 Added sts admin ack for 4.19
  deploy/osd-cluster-acks/sts/4.19/config.yaml
  deploy/osd-cluster-acks/sts/4.19/osd-sts-ack_CloudCredential.yaml
  hack/00-osd-managed-cluster-config-integration.yaml.tmpl
  hack/00-osd-managed-cluster-config-production.yaml.tmpl
  hack/00-osd-managed-cluster-config-stage.yaml.tmpl
Labels: approved, lgtm

#2421 Conditioned create tags network interfaces with run instances block
  resources/sts/hypershift/openshift_hcp_capa_controller_manager_credentials_policy.json
Labels: approved, lgtm
